export default{
    "d_queenintro": "퀸즈 키트1",
    "d_esperintro": "천연 100%",
    "d_auroraintro": "벚꽃개화",
    "d_leointro": "메카 메이헴",
    "d_idolintro": "노래하고 춤추고",
    "d_esperpuzzle1": "퍼즐 키트",
    "d_aurorareprogram": "퍼즐 키트",
    "d_aurorastarter1": "사쿠라 Mk-1",
    "d_idolstarter1": "노래하고 춤추고",
    "d_esperstarter1": "천연 100%",
    "d_queenchess": "체크메이트",
    "d_esperdungeon1": "천연 100%",
    "d_esperdungeon2": "연말",
    "d_esperdungeon3": "마그나 마기카에",
    "d_auroradungeon1": "벚꽃개화",
    "d_auroradungeonspirit": "정령의 부름",
    "d_idoldungeon1": "센터 스테이지",
    "d_idoldungeonmahou": "마음 속 시련",
    "d_leodungeon1": "메카 메이헴",
    "d_dragoondungeon1": "옛것과 새로움",
    "d_dragoondungeon2": "더욱 사이좋게",
    "d_dragoondungeoninf": "호기심은 끝없이",
    "d_omegadungeon1": "군대를 통솔하는 자",
    "d_collabeden": "에덴즈 엣지",
    "d_collabcross": "월드 시커",
    "d_collabvault": "보이드 볼트",
    "d_collabnova": "Supernova의 흔적",
    "d_auroraside1": "벚꽃 Mk-2",
    "d_queenside1": "여왕친위대",
    "d_queenomegaduel": "여왕친위대",
    "d_idolside1": "라이브 스테이지",
    "d_idolside2": "라이브 스테이지",
    "d_dragoonstory1": "신화와 전설",
    "d_dragoonstoryflame": "태초의 불",
    "d_esperside1": "프레젠테이션용 키트",
    "d_esperside2": "프레젠테이션용 키트?",
    "d_leoside1": "메카 키트",
    "d_leoside2": "파이어 키트",
    "d_idolexpuzzle1": "퍼즐 키트",
    "d_leoexpuzzle1": "퍼즐 키트",
    "d_expuzzlemage": "퍼즐 키트",
    "d_collabedendemo": "에덴즈 엣지",
    "d_collabcrossdemo": "월드 시커",
    "d_collabvaultdemo": "보이드 볼트",
    "d_collabnovademo": "Supernova의 흔적",
    "e_boss1effect_spawn": "<key>{0}</>장의 미니언 카드를 소환한다",
    "e_boss1effect_spawn_upgrade": "<key>{0}</>장의 미니언 카드를 소환하고, <uadd>[</>이 카드의 카운터 수만큼<health>체력</>을 증가시킨다<uadd>]</>",
    "e_boss1effect_splash": "상대 필드 위에 있는 모든 카드에 <uadd>[</><magic>{0}</><uadd>]</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_boss1effect_splashtrigger": "카드가 파괴될 때마다 상대 필드 위에 있는 모든 카드에<magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_boss2effect_aoe": "상대 필드 위에 있는 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_boss2effect_passive": "이 카드를 제외한 자신의 필드 위의 카드 1장당, 자신이 받는 모든 대미지를 1 줄인다 (현재：<key>-{0}</>)",
    "e_boss2effect_spawn": "이 카드가 대미지를 받았을 때, 받은 대미지와 같은 수치의 체력을 가진 미니언을 소환한다",
    "e_boss2effect_superspawn": "자신의 필드 위의 하나를 제외한 모든 빈 슬롯에 미니언을 소환한다. 소환된 미니언의 체력은 자신의 필드 위에 있는 빈 슬롯의 수<key>x{0}</>와 같아진다 (현재：<health>{1}</>)",
    "e_boss3effect_blast": "필드 위의 특수효과를 가지지 않은 카드를 모두 파괴한다. 파괴될 때마다 <img id=\"\"player_health\"\"/>에{0} 대미지를 준다",
    "e_boss3effect_control": "상대 필드 위에 있는 모든 카드를 아군으로 만들고, 특수효과를 제거한다",
    "e_boss3effect_spawn": "미니언 카드를 <key>3</>장 소환하고, 자신의 트래쉬를 비운다",
    "e_boss3effect_spawn_super": "미니언 카드를 <key>{0}</>장 소환하고, 자신의 트래쉬를 비운다. 소환된 미니언 카드는 이 카드의 <key>카운터</> 수에 따라 <health>체력이+1</>된다. 그 후, 이 카드의 <key>카운터</>를 1 늘린다",
    "e_boss3effect_protection": "이 카드가 받는 모든 대미지를 <key>0</>으로 한다. 상대 필드 위에 특수효과가 없는 카드가 정확히 <key>{0}</>장 있는 경우에는 이 효과가 적용되지 않는다 (현재：{1}/{0}장)",
    "e_boss4effect_dagger_move": "상대의 카드가 공격할 시, 그 카드의 왼쪽 또는 오른쪽으로 1 슬롯, 추가로 후열 슬롯으로 이동한다. 이동한 곳에 다른 카드가 있을 경우, 그 카드와 위치를 바꾼다",
    "e_boss4effect_scythe_destruct": "자신의 필드 위에 있는 모든 카드의 공격력을 <key>{0}</> 올린다",
    "e_boss4effect_scythe_move": "상대의 카드가 공격할 시, 그 카드의 정면으로 이동한다. 이동한 곳에 다른 카드가 있을 경우, 그 카드와 위치를 바꾼다",
    "e_boss4effect_spawn": "미니언 카드를 1장 소환한다",
    "e_boss4effect_superspawn": "상대 필드의 전열이면서, 이 카드와 같은 세로열의 위치에 상대의 <key>soul</>을 소환한다. 소환한 곳에 다른 카드가 있을 경우, 그 카드를 덮어쓴다",
    "e_boss4effect_soul_death": "이 카드가 필드에서 트래쉬로 보내졌을 때, 게임에서 패배한다",
    "e_boss4effect_weapondeath": "이 카드가 필드에서 트래쉬로 보내졌을 때, 자신의 필드 위에 있는 모든 카드의 공격력을 <key>{0}</> 올린다",
    "e_boss5effect_1": "<key>Reprogram</>이 사용되면 공격력이 1 올라간다",
    "e_boss5effect_2": "이 카드가 대미지를 받으면 카운터를 1 늘린다. 이 카드가 이미 카운터를 가지고 있는 경우에는 카운터를 리셋하고 그 대미지를 무효로 한다",
    "e_boss5effect_bombminion": "자신의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, <img id=\"\"player_health\"\"/>에{0} 대미지를 준다",
    "e_boss5effect_left1": "상대는 패를 버리고, 버린 카드와 같은 수의 카드를 드로우한다",
    "e_boss5effect_left2": "상대 필드의 전열이면서, 이 카드와 같은 세로열의 위치에 미니언 카드를 1장 소환한다. 소환한 곳에 다른 카드가 있을 경우, 그 카드를 덮어쓴다",
    "e_boss5effect_right1": "상대의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_boss5effect_right2": "자신의 필드에 미니언 카드를 {0}장 소환한다",
    "e_bossb1_1": "상대 필드의 빈 슬롯 수 <key>x{1}</>와 같은 수치의 체력을 가진 미니언 카드를 1장 소환한다(최저 수치는 <health>1</>). 그리고 상대 필드 위의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_bossb1_2": "이 카드에 카운터가 있는 동안, 상대가 패에서 카드를 꺼냈을 때, 이 카드로 공격한다",
    "e_bossb1_3": "이 카드의 카운터를 {0} 늘린다(최대：{0}). 카운터 1개당, 아군의 카드가 받는 모든 대미지를 1 줄인다. 이 카드가 대미지를 받았을 경우, 카운터를 1 줄인다",
    "e_bossb1_minion_1": "<img id=\"\"player_health\"\"/>에 이 카드의 공격력과 같은 수치의 대미지를 준다",
    "e_bossb1_minion_2": "상대의 카드가 필드 위를 이동했을 때, 그 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_bossb2_1": "자신의 필드 위의 랜덤한 위치에 랜덤한 수치의 카운터를 가진 미니언 카드를 {0}장 소환한다 (최소 {1} 최대 {2})",
    "e_bossb2_2": "필드 위에 있는 모든 카드의 카운터를 {0} 늘린다 (카드 1장당, 카운터는 최대 {1})",
    "e_bossb2_3": "카운터가 있는 카드가 대미지를 받았을 때, 그 카드의 카운터를 1 줄이고 대미지를 0으로 한다",
    "e_bossb2_minion_1": "이 카드가 다른 카드에 대미지를 주었을 때, 대상의 체력을 <health>0</>으로 하지 못한 경우, <img id=\"\"player_health\"\"/>에{0} 대미지를 준다",
    "e_bossb3_1": "자신의 필드 위의 랜덤한 위치에 <key>{0}</>장의 미니언 카드를 소환한다. 이 카드에 카운터가 있는 경우에는 <key>{1}</>장의 미니언 카드를 소환한다. 그 후, 이 카드의 카운터를 <key>{2}</> 늘린다 (최대：{2})",
    "e_bossb3_2": "이 카드가 대미지를 받았을 때, 이 카드에 있는 카운터의 수만큼 대미지를 줄인다(현재：<key>-{0}</>). 그 후, 이 카드의 카운터를 1 줄인다. 이 카드의 카운터 수보다 많은 대미지를 받은 경우, 카운터를 리셋한다",
    "e_bossb3_3": "자신의 카드가 1장 파괴될 때마다, 자신의 필드 위에 있는 다른 모든 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다",
    "e_bossb3_minion_1": "{0}번 공격한다",
    "e_bossb3_minion_2": "<physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지로 공격한다",
    "e_bossb3_minion_3": "상대의 모든 카드에 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_bossb3_minion_4": "자신의 필드의 랜덤한 슬롯에 {0}장의 미니언 카드를 소환한다",
    "e_bossb4_1": "상대의 패에 있는 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, 상대가 패에 가지고 있던 카드의 수에 따라 자신의 필드의 랜덤한 슬롯에 미니언 카드를 소환한다",
    "e_bossb4_2": "카드가 파괴될 때마다 이 카드의 카운터를 1 늘린다. 이 카드에 <key>{0}</>이상의 카운터가 있을 경우, 카운터를 0으로 리셋하고 필드 위의 모든 카드에 <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_bossb4_3": "상대의 모든 카드에 이 카드의 카운터 수와 같은 수치의 <magic>마법 대미지</>를 준다 (최소：1 대미지) (현재：<magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_bossb5_1": "체력이 <key>X</>인 미니언 카드를 <key>X</>장 소환한다. <key>X</>는 이 카드의 <attack>공격력</>이 된다 (현재：<key>{0}</>)",
    "e_bossb5_2": "이 카드가 공격해서 <key>0</> 이상의 대미지를 준 경우, 상대 필드 위에 있는 다른 <expose>언커버</> 상태의 카드를 모두 <void>보이드</>한다",
    "e_bossb5_3": "이 카드의 공격력이 <attack>{0}</> 올라간다",
    "e_bossb6_1": "상대의 트래쉬를 덱으로 되돌린 후, 셔플 시키고 상대 필드의 카드를 모두 1열 후열로 밀어낸다. 후열에 있던 카드는 덱으로 돌아간다. 그 후, 상대는 패가 <key>5</>장이 될 때까지 카드를 드로우한다",
    "e_bossb6_2": "자신의 필드 위에 있는 다른 카드가 대미지를 받았을 때, 그 카드가 받은 대미지와 같은 수의 카운터를 이 카드에 추가한다(최대：<key>{0}</>). 이미 이 카드에 <key>{0}</>이상의 카운터가 있을 경우, 이 효과는 적용되지 않는다",
    "e_bossb6_3": "이 카드는 카운터의 수까지만 대미지를 받는다(카운터가 0일 경우에는 0 대미지). 이 카드가 대미지를 받은 경우, 받은 대미지와 같은 수의 카운터가 감소한다",
    "e_bossb6_extra_1": "이 카드의 카운터 수에 따라서 미니언 카드를 소환한다(최소：<key>1</>장). 그 후, 이 카드의 카운터를 1 늘린다 (최대：<key>{0}</>)",
    "e_bossb7_1": "상대 필드에 있는 카드의 수와 같은 수의 미니언을 소환한다 (최소：<key>{0}</>장)",
    "e_bossb7_2": "자신의 카드가 1장 파괴될 때마다 이 카드의 카운터를 1 늘린다. 이 카드에 카운터가 <key>{0}</> 이상 있을 경우, 카운터를 리셋하고 자신의 필드 위에 있는 모든 카드로 공격한다",
    "e_bossb7_3": "이 카드의 카운터 수와 같은 횟수로 공격한다 (최소：<key>1</>회) (현재：<key>{0}</>회)",
    "e_bossb8_1": "자신의 필드 위의 미니언 카드를 모두 파괴하고, 파괴될 때마다 <img id=\"\"player_health\"\"/>에 <key>{1}</> 대미지를 준다. 그 후, 자신의 필드에 <key>{0}</>장의 미니언 카드를 소환한다",
    "e_bossb8_2": "상대가 카드를 꺼냈을 때, 이 카드의 카운터와 같은 수의 <attack>공격력</>과 <health>체력</>을 가진 미니언 카드를 소환하고(최소 <attack>1</>|<health>1</>), 이 카드의 카운터를 1 늘린다",
    "e_bossb8_3": "상대의 모든 카드에 <key>X</><img id=\"\"dmg_magic\"\"/>만큼의 <magic>마법 대미지</>를 준다. <key>X</>은 이 카드의 카운터 수가 된다(최소：<magic>1</><img id=\"\"dmg_magic\"\"/>대미지). 그 후, 이 카드의 카운터를 리셋한다",
    "e_bossb8_minion_1": "이 카드와 같은 세로열에 있는 카드는 다른 세로열의 카드에 대미지를 줄 수 없다",
    "e_bossb8_minion_2": "이 카드와 같은 세로열에 있는 상대의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_bossb9_1": "이 카드의 <attack>공격력</>과 같은 <attack>공격력</>과 <health>체력</>을 가진 미니언 카드를 <key>{0}</>장 소환한다. 그 카드에 <key>4</> 카운터가 있을 경우, <key>4</>장의 미니언 카드를 소환한다. 이 카드에 <key>8</>개의 카운터가 있는 경우, <key>8</>장의 미니언 카드를 소환한다",
    "e_bossb9_2": "상대가 카드를 꺼내거나 <key>턴 드로우를 할 때마다, 이 카드의 카운터를 1 늘린다. 카운터가 <key>{0}</>인 경우, 이 카드의 카운터를 리셋하고 <attack>공격력</>을 <attack>{1}</> 올린다",
    "e_bossb9_3": "이 카드에 <key>4</> 또는 <key>8</> 카운터가 없는 경우, 자신의 카드가 받는 모든 대미지를 <key>{0}</> 줄인다",
    "e_bossb9_minion_1": "이 카드가 다른 카드에 대미지를 주거나 대미지를 받은 경우, 다른 카드를 <void>보이드</>한다. 이 효과를 발동하기 위해서는 이 카드가 필드에 나와 있어야 한다",
    "e_bosscomet1_1": "이 카드가 0 이상의 대미지를 받으면, 그곳에 미니언 카드를 1장 소환하고 랜덤한 슬롯으로 이동한다. 그 대미지로 이 카드가 파괴되었을 경우, 이 효과는 적용되지 않는다",
    "e_bosscomet1_2": "<physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지로 4번 공격한다",
    "e_bosscomet1_minion": "이 카드와 다른 이름을 가진 자신의 카드는 대미지를 받지 않는다",
    "e_bosscomet2_1": "이 카드가 대미지를 받을 때마다, {0}턴 <key>서스펜드</>하고 카운터를 1 늘린다. 이 카드에 카운터가 {1}개 있을 때, 카운터를 리셋하고 상대 필드 위에 있는 모든 카드에 <magic>{2}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, <img id=\"\"player_health\"\"/>에도 같은 대미지를 준다",
    "e_bosscomet3_1": "랜덤한 수치의 체력과 공격력을 가진 미니언 카드를 {0}장 소환한다. 상대의 트래쉬에 {1}장 이상의 <key>Corruption</> 카드가 있을 경우에는 스테이터스가 <attack>{2}</>|<health>{3}</>인 미니언 카드를 소환한다. 그 후, 이 카드를 랜덤한 슬롯으로 이동시킨다",
    "e_bosscomet3_2": "자신의 필드 위에 다른 카드가 존재하는 경우, 이 카드가 받는 모든 대미지가 {0} 감소한다",
    "e_bosscomet3_3": "상대 필드의 빈 슬롯에 <key>Corruption</> 카드를 소환한다",
    "e_bosscomet3_bomb_trigger": "이 카드가 다른 슬롯으로 이동한 경우, 자신의 덱으로 이동시키고 셔플한다",
    "e_bosscomet3_bomb": "<img id=\"\"player_health\"\"/>에 {0} 대미지를 준다",
    "e_bossomega_core": "이 카드가 대미지를 받았을 때, 자신의 필드 위에 있는 다른 모든 카드를 {0}턴 <key>서스펜드</>한다",
    "e_bossomega_countdown": "<img id=\"\"player_health\"\"/>을 0으로 한다",
    "e_bossomega_passive": "이 카드의 체력은 매 턴이 끝날 때마다 모두 회복된다",
    "e_bossomega_transform": "이 카드가 파괴되면 변신한다",
    "e_consumablecache": "이 카드가 소환되었을 때, <img id=\"\"loot\"\"/>를 <key>{0}</>개 추가한다 ({1})",
    "e_consumablecacheremoval": "이 카드가 대미지를 받았을 때, 자신의 필드 위에 있는 다른 모든 <key>.potion</>카드를 <void>보이드</>한다",
    "e_enemyartillery": "필드 위에 있는 다른 모든 <key>Artillery.sc</>의 공격력을 <attack>{0}</> 올린다",
    "e_enemyblackvirus_manual": "<img id=\"\"player_health\"\"/>에 {0} 대미지를 준다",
    "e_enemyblackvirus_triggeer": "이 카드에 대미지를 준 카드는 레벨이 없고 효과만 있는 상태의 이 카드로 변신한다. 대미지를 준 카드가 필드 위에 없을 경우, 이 효과는 적용되지 않는다",
    "e_enemychandelier": "어떠한 카드가 필드 위를 이동하거나 이동되었을 때, 이 카드의 공격력이 <key>{0}</> 올라간다. 공격하면 이 효과는 리셋된다",
    "e_enemycollapse": "상대 필드 위에 <key>{0}</>장 이상의 카드가 있는 경우, 상대의 카드의 특수효과가 발동될 때마다 상대의 모든 카드에 <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemycommandsignal_destroy": "모든 카드로 공격한다",
    "e_enemycommandsignal_manual": "모든 카드로 공격한다. 공격 가능한 카드가 존재하지 않는 경우,  <img id=\"\"player_health\"\"/>에 1 대미지를 주고, 이 카드를 <decompile>디컴파일</>한다",
    "e_enemydaggers": "상대가 패에서 카드를 필드에 꺼냈을 때, 이 카드로 공격하고 이 카드의 <attack>공격력</>을 <attack>{0}</> 올린다 (최대：+<attack>{1}</>)",
    "e_enemydetonator": "필드 위에 있는 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemydisruptor_passive": "카드를 드로우할 때마다 이 카드의 체력을 1 회복한다",
    "e_enemydisruptor_trigger": "이 카드가 대미지를 받았을 때, 상대의 덱에서 가장 위에 있는 카드를 트래쉬로 보낸다",
    "e_enemyghostblue": "이 카드에 대미지를 주었거나 이 카드에 대미지를 받은 카드는 랜덤한 슬롯으로 이동한다",
    "e_enemyghostred": "이 카드가 대미지를 받았을 때, 랜덤한 슬롯으로 이동한다",
    "e_enemyguardian": "카드를 드로우할 때마다 이 카드의 공격력은 <attack>1</> 올라간다",
    "e_enemyinterceptor": "자신의 카드가 대미지를 받았을 때, 이 카드로 공격한다",
    "e_enemymiasma_damage": "상대의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemymiasma_protect": "자신의 필드 위에 있는 이 카드와 다른 이름을 가진 카드의 수만큼, 이 카드가 받는 대미지가 감소한다 (현재：<key>-{0}</>)",
    "e_enemyminibosscurse_attack": "랜덤한 슬롯으로 이동하고, <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지로 공격한다",
    "e_enemyminibosscurse": "이 카드가 대미지를 받았을 때, 상대의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemymirrorshard": "이 카드가 대미지를 받았을 때, 다른 모든 <key>MirrorShard.mw</> 카드가 받은 대미지와 같은 공격력으로 공격한다",
    "e_enemyobserver": "상대의 카드가 효과를 발동했을 때, 상대의 패, 덱, 필드, 트래쉬에 있는 같은 카드를 모두 <void>보이드</>한다",
    "e_enemypathogen_destruct": "상대는 패를 모두 버리고, 버린 카드와 같은 수만큼 카드를 드로우한다",
    "e_enemypathogen": "상대의 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemyphantomred": "상대의 후열에 있는 카드를 전열로 이동시킨다. 겹쳐진 카드는 위치를 바꾼다",
    "e_enemypredator": "체력이 줄어든 상대의 카드가 필드 위를 이동한 경우, 그 카드와 같은 세로열의 전열로 이동한다. 그 후, 이 카드로 공격한다",
    "e_enemyrailgun": "이 카드가 대미지를 받았을 때, 공격력이 <attack>{0}</> 올라간다",
    "e_enemytalismanblack": "상대 카드의 특수효과를 모두 제거한다. 상대의 카드에 특수효과가 없는 경우, 그 카드를 파괴한다",
    "e_enemyvenomdestruct": "이 카드를 덱의 가장 위로 추가한다",
    "e_enemyvenomexecute": "<img id=\"\"player_health\"\"/>에 {0} 대미지를 준다",
    "e_enemyvenommanual": "이 카드를 파괴하고, <img id=\"\"player_health\"\"/>에 {0} 대미지를 준다",
    "e_enemyvirusblue": "이 카드에 대미지를 주었거나 이 카드에 대미지를 받은 카드는 특수효과를 잃는다",
    "e_enemyvirusred_attack": "특수효과를 가지지 않은 카드를 공격했을 때, 이 카드의 공격력은 <attack>{0}</> 올라간다",
    "e_enemyvirusred_passive": "이 카드는 특수효과가 없는 카드에는 대미지를 받지 않는다",
    "e_enemywhitetalisman_trigger": "자신의 트래쉬로 레벨 <key>1</> 이상의 카드가 보내졌을 때(<key>White.tlsm</> 제외), 그 카드의 카피로 변신한다",
    "e_enemywormblue": "이 카드가 공격해서 대미지를 준 경우, 대미지를 준 카드와 같은 가로열에 있는 다른 모든 카드에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_enemywormred": "<physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지로 2번 공격한다",
    "e_enemyzombie": "이 카드가 트래쉬에 있고, 이 턴에 파괴되지 않은 경우, 필드 위의 자신의 카드가 1장 파괴되면(<key>Zombie.mw</> 제외), 이 카드를 자신의 필드 위의 랜덤한 슬롯에 꺼낸다",
    "e_haloshield": "이 카드와 다른 이름을 가진 카드는 대미지를 받지 않는다",
    "e_shareddelayonhit": "이 카드가 대미지를 받았을 때, {0}턴 <key>서스펜드</>한다",
    "e_sharedoneshotonly": "이 카드가 대미지를 받았지만 파괴되지 않은 경우, 상대는 게임에서 패배한다",
    "e_specialcryptcache_drafting": "이 카드가 나왔을 때, 이 카드에 <key>Compile</><img id=\"\"loot\"\"/>를 {0}개 창조한다",
    "e_specialcryptcache_random": "이 카드가 나왔을 때, 이 카드에 <img id=\"\"loot\"\"/>를 창조한다",
    "e_specialcryptcache": "이 카드가 나왔을 때, 이 카드에 <img id=\"\"loot\"\"/>를 창조한다. 1개는 <img id=\"\"effect_consumable\"\"/> 카드가 된다",
    "e_specialsanctum": "이 카드가 나왔을 때, 줄어든 <img id=\"\"player_health\"\"/>의 {0}%를 회복한다. 그 후, 상대의 카드를 모두 <key>리로드</>한다",
    "e_specialtimebomb": "상대는 게임에서 패배한다",
    "e_specialwaystone": "이 카드가 출현했을 때, 덱을 편집한다",
    "e_storyantiaurora": "유저명 <key>AURORA</>의 체력을 0으로 한다",
    "e_storyendgamelock": "특정 카드를 <decompile>디컴파일</>한 <key>Dragoon's flame</>이 존재하는 경우, 이 카드를 파괴한다",
    "e_storyflowerhologram": "이 카드가 파괴되었을 경우, 이 카드의 상하좌우에 있는 카드의 카운터를 {0}으로 한다",
    "e_storyhydrogencard": "<key>턴 드로우</>가 발생한 경우, 이 카드를 파괴하고 <img id=\"\"player_health\"\"/>을 0으로 한다",
    "e_storyoxygencard": "이 카드는 좌우에 <key>Hydrogen</> 카드가 있는 경우에만 대미지를 받는다",
    "e_storystealer": "상대의 패, 덱, 필드의 카드를 모두 트래쉬로 <decompile>디컴파일</>한다",
    "e_storysyncmark": "<key>SyncMarker</>가 트래쉬로 보내졌을 때, 상대는 게임에서 패배한다. 이 턴에 모든 <key>SyncMarker</> 카드가 트래쉬로 보내진 경우, 이 효과는 적용되지 않는다",
    "e_bossb10_1": "상대가 필드 위의 카드를 이동시킨 경우, 이 카드를 랜덤한 위치로 이동시키고, 트래쉬의 가장 위에 있는 카드를 이 카드가 있었던 슬롯에 꺼낸다",
    "e_bossb10_2": "상대의 패와 필드 위에 있는 카드 수의 합계가 자신의 필드 위에 있는 카드 수 이상일 경우, 이 카드가 공격한 후, 필드 위에 있는 다른 모든 카드를 <decompile>디컴파일</>한다 (현재：<key>{0}</>장 vs <key>{1}</>장)",
    "e_bossb10_3": "자신의 트래쉬에 있는 카드를 모두 왼쪽에서 오른쪽, 전열에서 후열 순으로 꺼낸다. 그 후, 자신의 트래쉬에 <key>{0}</>장의 주문 미니언 카드를 창조한다",
    "e_bossb10_minion_shared_adder": "이 카드의 <health>최대 체력</>이 <health>1</> 상승한다(최대 <uadd>[</><health>{0}</><uadd>]</>). 이 카드의 최대 체력이 이미 최대일 경우, 이 카드를 <void>보이드</>한다",
    "e_bossb10_minion_1": "전열에 <key>X</>만큼의 <physical>물리 대미지</>로 공격한다. <key>X</>는 자신의 필드에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다 (현재：X = <key>{0}</>)",
    "e_bossb10_minion_2": "상대의 모든 카드에 <key>X</><img id=\"\"dmg_magic\"\"/>만큼의 <magic>마법 대미지</>를 준다. <key>X</>는 자신의 필드에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다 (현재 : <key>{0}</>)",
    "e_bossb10_minion_3": "상대의 덱의 가장 위에서부터 카드를 <key>X</>장 트래쉬로 보낸다. 이 효과의 발동 시에 상대의 덱에 카드가 없는 경우, <img id=\"\"player_health\"\"/>에 <key>X</> 대미지를 준다. <key>X</>는 자신의 필드에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다 (현재：X = <key>{0}</>)",
    "e_bossmahou_1": "자신의 카드가 1장 파괴될 때마다, 랜덤한 미니언 카드를 1장 소환한다. 그 후, 이 카드의 카운터를 절반 줄인다",
    "e_bossmahou_2": "이 카드가 대미지를 받은 경우, 이 카드의 카운터 수와 같은 횟수의 공격을 한다(현재 : <key>{0}</>번). 그 후, 이 카드의 카운터를 1 줄인다",
    "e_bossmahou_3": "필드 위에 있는 다른 모든 <expose>언커버</> 상태의 카드와 자신의 트래쉬에 있는 모든 카드를 <void>보이드</>한다. 그 후, 랜덤한 미니엄 카드를 <key>{0}</> 소환하고, 이 카드의 카운터를 <key>{1}</> 늘린다",
    "e_ability_aurora": "턴을 소비하는 행동(카드를 꺼내거나 필드 위를 이동시키는 등)을 했을 때, 턴을 소비하는 대신에 이 카드의 <key>세레니티 토큰</>을 1 줄인다",
    "e_ability_aurora_counters": "이 카드의 <key>세레니티 토큰</>을 <key>{0}</> 늘린다",
    "e_ability_dragoon": "자신의 패, 덱, 필드, 트래쉬에 있는 모든 카드의 이름에 와일드 카드 <key>.*</>가 붙는다. <key>.*</>이 있는 카드는 모든 확장자에 해당한다",
    "e_ability_esper": "레벨 <key>{0}</> 이하의 카드가 자신의 필드에 나왔을 때(<key>WorldSeed</> 제외), 그 카드의 카피(초기상태)로 변화한다",
    "e_ability_idol": "자신의 필드 위에 있는 카드를 모두 패로 되돌린다. 그 후, 패로 돌아간 카드와 같은 수까지 카드를 필드에 꺼낸다. 단, 원래 필드 위에 있던 카드는 꺼낼 수 없다",
    "e_ability_leo_1": "자신의 필드 위에 있는 다른 카드를 모두 재활성화하고, 공격력을 <attack>{0}</> 상승시킨다",
    "e_ability_leo_2": "카드가 트래쉬로 보내졌을 때(<key>Mountain</> 제외), 그 카드를 패에 추가한다.",
    "e_ability_omega": "필드 위에 있는 카드를 2장까지 선택한다. 자신의 필드 위에 있는 카드를 선택한 경우, 그 카드를 <key>자동화</>한다. 적의 필드 위에 있는 카드를 선택한 경우, <key>{0}</>턴 <key>지연</>시킨다",
    "e_ability_queen": "자신의 필드 위에 있는 모든 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. 이 카드의 효과가 발동하는 동안, 적에게 주는 모든 대미지는 {0}배가 된다",
    "e_artifact_greed_active": "카드를 <key>{0}</>장 드로우한다",
    "e_artifact_greed": "<key>턴 드로우</>를 했을 때, 카드를 1장 뽑고, 덱 위에서 카드를 <key>2장</> 트래쉬로 보낸다. 덱에 카드가 없는 경우, 매 턴 <img id=\"\"player_health\"\"/>를 1 줄인다",
    "e_artifact_memory": "자신의 <key>스토리지</>에 있는 레벨 <key>1</> 이상의 카드는 <key>리로드</>할 때, 덱에 추가된다",
    "e_artifact_momentum_active": "곧바로 <key>턴 드로우</>를 한다",
    "e_artifact_momentum": "적의 카드가 파괴되었을 때, 곧바로 <key>턴 드로우</>를 한다. 패가 <key>{0}</>장 이상 있는 상태에서 카드를 뽑은 경우, 뽑은 카드를  <decompile>디컴파일</>하고, 턴 드로우 카운터를 <key>1</> 줄인다",
    "e_artifact_spire_active": "패를 버리고, 카드를 <key>{0}</>장 드로우한다",
    "e_artifact_spire": "패가 없는 상태에서 <key>턴 드로우</>를 한 경우, 추가로 카드를 <key>{0}</>장 드로우한다. 패가 {1}장 이상 있는 상태에서 카드를 뽑은 경우, 뽑은 카드를 <decompile>디컴파일</>한다",
    "e_artifact_starter": "이 카드는 자신의 덱을 <key>리로드</>한 후, 항상 덱의 가장 위에 배치된다",
    "e_chess_bishop_init": "자신의 모든 카드를 <health>1</> 회복한다",
    "e_chess_bishop_manual": "이 카드의 대각선 방향에 있는 적 1장을 대상으로 공격한다",
    "e_chess_king_death": "이 카드가 필드 위에서 트래쉬로 보내졌을 경우, 게임에서 패배한다",
    "e_chess_king_init": "자신의 트래쉬에 카드가 1장 이상 있는 경우, 트래쉬를 <key>리로드</>한 뒤 덱으로 되돌리고, 트래쉬에 있던 카드 1장당, 이 카드의 공격력을 1 상승시킨다(최대 : {0}) (현재 : <attack>+{1}</>). 그 후, 패가 {2}장이 되도록 카드를 드로우한다",
    "e_chess_king_manual": "이 카드를 자신의 덱으로 되돌리고, 셔플한다. 그 후, 카드를 1장 드로우한다. 이 효과는 필드 위 또는 트래쉬에서 발동할 수 있다.",
    "e_chess_knight_init": "이 카드로 공격한다.",
    "e_chess_knight_manual": "이 카드의 세로로 2칸, 가로로 1칸에 있는 적 1장, 또는 가로로 2칸, 세로로 1칸에 있는 적 1장을 대상으로 공격한다",
    "e_chess_pawn_manual": "이 카드의 대각선 1칸에 있는 적 1장을 대상으로 공격한다",
    "e_chess_pawn_trigger": "이 카드가 적에게 대미지를 주었을 때, 이 카드의 카운터를 1 늘린다. 카운터가 <key>{0}</>이 되었을 때, 이 카드는 <key>Queen</>으로 변화한다",
    "e_chess_queen_init": "자신의 필드 위에 있는 카드 1장당, 모든 적 카드에게 마법 대미지를 <magic>1</><img id=\"\"dmg_magic\"\"/> 준다 (현재 : <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_chess_queen_loot": "모았던 모든 <img id=\"\"loot\"\"/>를 소비하고, 개수에 따라서 <img id=\"\"player_health\"\"/>를 회복한다 (현재 : {0}<img id=\"\"player_health\"\"/>)",
    "e_chess_queen_manual": "모든 적 카드에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_chess_rook_manual": "이 카드로 공격한다",
    "e_chess_rook_passive": "이 카드가 대미지를 받을 때마다 공격력이 <attack>{0}</> 상승한다. 이 카드로 공격했을 때, 공격 대상의 뒤에 있는 카드도 같은 수치의 대미지를 받는다",
    "e_dragoon_condition": "자신의 필드 위에 있는 카드를 <key>{0}</>장 <decompile>디컴파일</>한다",
    "e_dragoon_flame": "체력이 1인 적의 카드를 모두 <decompile>디컴파일</>한다",
    "e_dragoon_shared": "이 카드가 받은 대미지는 이 효과를 가진 다른 모든 카드와 공유된다. 이 효과는 같은 효과를 가진 카드에게서 받은 대미지에 대해서는 발동하지 않는다",
    "e_eden_bowsnipe": "이 카드와 같은 세로열에 있는 모든 적 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_eden_crossfire": "이 카드의 대각선 방향에 있는 모든 카드(자신의 카드도 포함하지만, 이 카드는 제외)에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_eden_gunner_boost": "<key>턴 드로우</>했을 때, 이 카드에게 <uadd>[</><attack>{0}</><uadd>]</> 대미지 만큼의 <specialbuff>단발 버프</>를 준다. 이미 버프가 있는 경우, 이 효과는 무시된다",
    "e_eden_gunner": "이 카드가 대미지를 주었을 때, 이 카드의 카운터가 <key>{1}</> 이상 있으면, 카운터를 리셋한 후 자신의 턴 드로우 카운터를 <key>{0}</> 줄이고, 그렇지 않으면 카운터를 1 늘린다",
    "e_eden_hazel_adder": "트래쉬에서 랜덤한 <key>.edx</> 카드를 1장 패에 추가한다",
    "e_eden_hazel": "이 카드가 대미지를 준 경우, 같은 가로열에 있는 공격력이 <attack>0</>인 모든 카드의 효과와 스테이터스 보정을 제거하고, 스테이터스를 <uadd>[</><attack>{0}</>|<health>{1}</><uadd>]</>로 한다",
    "e_eden_ragnarok": "이 카드의 <attack>공격력</>의 <uadd>[</><key>{0}</><uadd>]</>배의 <magic>마법 대미지</>를 이 카드의 <key>2</>칸 앞쪽에 있는 카드에게 준다(최대 : <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지), 이 효과로 대미지를 받은 적이 있는 경우에는 그 절반의 대미지(올림)를 다른 모든 적 카드에게 준다",
    "e_eden_reva_reflect": "이 카드가 대미지를 받았을 때, 받은 대미지와 같은 <specialbuff>감소 버프</>를 획득하고(최대 : <attack>+{0}</>), 공격한다",
    "e_eden_reva": "이 카드가 <key>가로 방향</>으로 이동했을 때, 이 카드를 <health>{0}</> 회복한다. 이 카드가 <key>세로 방향</>으로 이동했을 때, 이 카드를 <health>{1}</> 회복한다. 이 2가지 효과는 동시에 발동할 수 있다",
    "e_eden_saffron_destruct": "자신의 패로 이 카드를 되돌린다",
    "e_eden_saffron": "덱에서 랜덤한 <key>.edx</> 카드를 <uadd>[</><key>{0}</><uadd>]</>장 패에 추가한다",
    "e_eden_selicy": "이 카드가 대미지를 주었을 경우, 공격한다",
    "e_eden_sharedatkcondition": "자신의 턴 드로우 카운터가 <key>{0}</> 이하여야 한다. 이 카드를 꺼냈을 경우, 자신의 턴 드로우 카운터가 <key>{1}</> 증가한다",
    "e_eden_sharedattacking": "이 카드와 같은 세로열에서 자신의 레벨이 <key>1</> 이상인 카드의 <img id=\"\"effect_init\"\"/> 효과가 발동했을 때, 대신에 이 카드가 그 효과를 발동한 것으로 한다. 카드가 <key>.edx</> 카드인 경우, 그 카드를 <decompile>디컴파일</>하고, 카드를 1장 드로우한다",
    "e_eden_shiso_kill": "이 카드가 카드를 파괴한 경우, 카드를 1장 드로우한다",
    "e_eden_shiso": "이 카드가 대미지를 준 경우, <attack>{0}</> 대미지 만큼의 <specialbuff>감소 및 단발 버프</>를 획득한다 (최대 : <attack>+{1}</>)",
    "e_eden_shopkeeper_damage": "이 카드가 대미지를 준 경우, 자신의 덱을 <key>셔플</>한다",
    "e_eden_shopkeeper": "자신의 덱 안에서 <key>{0}</>장의 랜덤한 카드 중 1장을 선택하고, 그 카피를 덱의 가장 위에 <key>{1}</>장 창조한다",
    "e_eden_stepslash": "앞쪽에 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다. 이 카드가 후열에 있는 경우에는 전열로 이동시켜(이미 앞쪽에 카드가 있는 경우에는 뒤바꾼다), 1칸 앞에 있는 카드에게 <uadd>[</><physical>{1}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다",
    "e_eden_terra_pull": "이 카드에게 대미지를 받은 카드를(가능하다면) 전열로 끌어당긴다",
    "e_eden_terra": "이 카드가 주는 대미지는 <uadd>[</><key>{0}</><uadd>]</> 증가한다",
    "e_eden_thunder": "이 카드의 <key>2</>칸 앞쪽의 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_eden_violette_boost": "이 카드의 카운터가 <key>{0}</> 이상 있는 경우, 이 카드가 효과를 발동했을 때, 이 카드의 카운터를 리셋하고 그 효과를 한 번 더 발동한다",
    "e_eden_violette": "이 카드가 이동했을 때, 마지막에 이동한 방향에 따라 효과를 발동한다(대각선 이동은 고려하지 않는다). <key>위</> : 이 카드로 공격한다. <key>아래</> : <health>{0}</> 회복한다. <key>왼쪽</>/<key>오른쪽</> : 이 카드의 카운터를 1 늘린다 (최대 : <key>{1}</>)",
    "e_eden_violette_upgrade": "이 카드가 이동했을 때, 이 카드의 카운터를 1 늘리고(최대 : <key>{1}</>), 마지막에 이동한 방향에 따라 효과를 발동한다. <key>위</> : 이 카드로 공격한다. <key>아래</> : <health>{0}</> 회복한다",
    "e_eden_wave": "앞쪽에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, 가능하다면 대상을 뒤쪽에 밀어내고 <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 추가 대미지를 준다. 대상이 처음부터 뒤편에 있었던 경우, 가능하다면 앞쪽으로 끌어당긴다",
    "e_fantasy_arae": "이 카드가 적 카드에게 대미지를 준 경우, 그 카드의 카운터를 1 늘린다(최대 : <uadd>[</><key>{0}</><uadd>]</>). 이 카드와 같은 세로열에 있는 적 카드가 대미지를 받은 경우, 그 카드의 카운터 수만큼 대미지를 늘린다 (최대 : <uadd>[</><attack>+{0}</><uadd>]</> 추가 대미지)",
    "e_fantasy_cock": "모든 적에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</>의 피해를 입히고, <key>{1}</>턴 지연시킵니다.",
    "e_fantasy_cockcondition": "모든 적의 턴 카운터의 합계가 {0} 이상이어야 한다 (현재 :  {1}/{0})",
    "e_fantasy_griffin": "자신의 다른 카드가 <key>2</> 이상의 대미지를 받은 경우(이 카드와 같은 이름의 카드 제외), 대신에 이 카드가 대미지를 받는다",
    "e_fantasy_mermaid": "자신 필드의 모든 카드를 <key>재활성화</>하고, 그 카드들의 능력치를 <uadd>[</><attack>+{0}</>|<health>+{1}</><uadd>]</>만큼 상승시킨다.",
    "e_fantasy_mermaidcondition": "트래쉬에는 {0}장 이상의 카드가 있어야 하며, 동시에 같은 이름을 가진 카드가 트래쉬에 없어야 한다.",
    "e_fantasy_phoenix": "이 카드가 트래쉬에 있는 경우, 패에 추가한다",
    "e_fantasy_unicorn": "체력이 2 이상 있는 자신의 카드는 대미지를 받았을 때, 체력을 1 이상 남기고 버틴다",
    "e_fantasy_highlandcondition": "트래쉬에는 <key>{0}</>장 이상의 카드가 있어야 하며, 동시에 같은 이름을 가진 카드가 트래쉬에 없어야 한다.",
    "e_generic_afterburner": "자신의 패가 <uadd>[</><key>{0}</><uadd>]</>장이 될 때까지 카드를 드로우한다",
    "e_generic_avarice": "트래쉬에서 카드를 정확히 <key>{0}</>장 선택하여 덱으로 되돌리고, 카드를 <uadd>[</><key>{1}</><uadd>]</>장 드로우한다",
    "e_generic_battery": "곧바로 <key>턴 드로우</>를 한다",
    "e_generic_beartrap": "트래쉬에서만 발동할 수 있다. 모든 적을 <uadd>[</><key>{0}</><uadd>]</>턴 지연시켜, <uadd>[</><magic>{1}</><uadd>]</> 대미지를 준다. 그 후, 이 카드는 <void>보이드</>된다",
    "e_generic_cinder": "모든 적을 <uadd>[</>{0}<uadd>]</>턴 지연시킨다",
    "e_generic_constantcorrection": "자신의 필드 위에 있는 카드 1장을 대상으로 한다. 그 카드의 효과와 스테이터스 보정을 모두 제거하고, 스테이터스를 <uadd>[</><attack>{0}</>|<health>{0}</><uadd>]</>로 변경한다",
    "e_generic_crystalball": "자신의 덱에서 공격력과 체력이 덱의 가장 위에 있는 카드와 같은 카드를 1장 선택하여 패로 추가한다. 그 후, 자신의 덱을 셔플한다",
    "e_generic_doubleexecute_extra": "이 카드가 트래쉬에 있는 경우, 패에 추가한다",
    "e_generic_doubleexecute": "자신의 필드 위에 있는 모든 카드를 <exec>실행</>한다",
    "e_generic_ember": "<uadd>[</>{0}<uadd>]</>장 카드를 드로우한다",
    "e_generic_fireball": "앞쪽에 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 마법 대미지를 준다",
    "e_generic_flash": "앞쪽의 적에게 그 턴 카운터와 같은 <magic>마법 대미지</>를 준다",
    "e_generic_flashbang": "이 카드를 파괴하고, 모든 적의 카드를 <uadd>[</>{0}<uadd>]</>턴 지연시킨다",
    "e_generic_force": "앞쪽에 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 마법 대미지를 주고, 대상을 1칸 뒤쪽으로 밀어낸다. 대상의 뒤편에 카드가 있는 경우, 전후를 뒤바꾼다",
    "e_generic_giveandtake_1": "이 카드의 카운터가 0인 경우, 어떠한 카드가 대미지를 받았을 때, 그 대미지를 0으로 줄인다. 그리고 그 카드가 받아야 했던 대미지와 같은 수치만큼, 이 카드의 카운터를 늘린다(최대 : <uadd>[</>{0}<uadd>]</>). <key>DamageCapacitor</>의 효과를 이미 적용한 대미지는 무시된다",
    "e_generic_giveandtake_2": "이 카드의 카운터가 0이 아닌 경우, 어떠한 카드가 대미지를 받았을 때, 이 카드의 카운터를 리셋하고 줄어든 카운터의 수만큼 주는 대미지를 증가시킨다. <key>DamageCapacitor</>의 효과를 이미 적용한 대미지는 무시된다",
    "e_generic_giveandtake_3": "이 카드의 <img id=\"\"effect_once\"\"/> 효과를 모두 리셋한다",
    "e_generic_gravity": "카드를 1장 뽑고, 자신의 트래쉬에 있는 <key>Gravity</> 이외의 카피 1장당, 1장을 추가로 드로우한다 (현재 : <key>{0}</>장)",
    "e_generic_inferno": "자신이 다른 카드를 꺼낼 때마다 필드 위에 있는 다른 모든 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다. 이 효과를 발동시키기 위해서는 이 카드가 필드 위에 있어야 한다",
    "e_generic_magicember": "자신의 필드 위에 있는 <attack>0</>|<health>1</> 카드를 모두 <decompile>디컴파일</>하고, <decompile>디컴파일</>된 카드 1장당, 카드를 1장 드로우한다 (현재 : <key>{0}</>장)",
    "e_generic_magicflare": "자신의 필드 위에 있는 <attack>0</>|<health>1</> 카드를 모두 <decompile>디컴파일</>하고, <decompile>디컴파일</>된 카드 수와 같은 <magic>마법 대미지</>를 모든 적 카드에게 준다 (현재 : <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_generic_megarush": "자신의 <img id=\"\"player_health\"\"/>가 1인 경우, 자신의 필드 위에 있는 다른 카드의 모든 공격력을 <uadd>[</><attack>{0}</><uadd>]</> 상승시키고, 이 카드를 파괴한다",
    "e_generic_omen": "활성화한 다른 카드의 효과가 발동될 때마다 이 카드의 공격력이 <attack>{0}</> 상승한다(최대 : <uadd>[</><attack>{1}</><uadd>]</>). 공격하면 이 효과는 리셋된다",
    "e_generic_pendulum": "이 카드가 패에 있을 때, <img id=\"\"player_health\"\"/>에 대미지를 받은 경우, 이 카드를 필드에 꺼내는 것으로 <img id=\"\"player_health\"\"/>로의 대미지를 <key>1</>로 하고, 모든 적을 <uadd>[</><key>{0}</><uadd>]</>턴 지연시킨다. 그 턴 중에 자신의 카드는 대미지를 받지 않는다 (단, <img id=\"\"player_health\"\"/>로의 대미지는 막을 수 없다)",
    "e_generic_pureheart": "패에 카드가 없는 경우, <uadd>[</><key>{0}</><uadd>]</>장 카드를 드로우한다",
    "e_generic_pureheart_condition": "패가 이 카드일 경우에만 필드에 꺼낼 수 있다",
    "e_generic_reincarnation": "트래쉬에서 카드를 1장 패로 추가한다 (<key>Reincarnation</> 제외)",
    "e_generic_ambush_play": "모든 <cover>커버</> 상태의 적에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 대미지를 주고, <uadd>[</><key>{1}</><uadd>]</>턴 지연한다",
    "e_generic_rupture": "필드 위의 카드를 선택한다. 대상에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준 후, 선택한 카드의 <key>반대쪽</> 필드에 있는 모든 카드에게 <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_generic_scalpel": "이 카드가 체력 <uadd>[</><health>{0}</><uadd>]</> 이하인 카드를 공격했을 때, 그 카드를 <decompile>디컴파일</>한다. 그 후, 이 카드를 <decompile>디컴파일</>하고, 자신의 덱에서 가장 위에 있는 카드를 이 카드가 놓여 있던 위치로 꺼낸다 (<img id=\"\"effect_condition\"\"/>은 무시된다)",
    "e_generic_shatter": "자신의 필드 위의 카드를 1장 선택한다. 그 카드의 현재 체력과 같은 <img id=\"\"dmg_magic\"\"/><magic>대미지</>를 모든 적에게 주고, 그 최대 체력과 같은 <img id=\"\"dmg_magic\"\"/><magic>대미지</>를 선택한 카드에게 준다",
    "e_generic_shatter_upgrade": "자신의 필드 위의 카드를 <uadd>[</>2장까지<uadd>]</> 선택한다. 선택한 카드의 현재 체력의 합계와 같은 <img id=\"\"dmg_magic\"\"/><magic>대미지</>를 모든 적에게 주고, 선택한 카드의 최대 체력의 합계와 같은 <img id=\"\"dmg_magic\"\"/><magic>대미지</>를 그 카드들에게 준다",
    "e_generic_solarflare": "앞쪽에 <uadd>[</><magic>{0}</><img id=“dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_generic_spark": "자신의 필드 위의 비활성화인 카드를 1장 선택하고(<key>Spark</> 제외), 그 카드를 재활성화한다",
    "e_generic_taser": "이 카드가 <img id=\"\"dmg_phys\"\"/><physical>대미지</>를 주었을 때, 대상을 <uadd>[</><key>{0}</><uadd>]</>턴 지연시킨다. 대상에게 <key>지연내성</>이 있는 경우, <magic>1</><img id=\"\"dmg_magic\"\"/> x <uadd>[</><key>{1}</><uadd>]</> 추가 대미지를 준다",
    "e_generic_taunt": "모든 카드를 {0}턴 동안 가속시켜, 가속하는 동안 직접적인 대미지를 0으로 한다.",
    "e_generic_thunderclap": "앞쪽의 적을 <uadd>[</><key>{0}</><uadd>]</>턴 지연시킨다. 그 후, 자신의 덱에서 가장 위에 <key>Flash</> 카드를 추가하고, 자신의 턴 드로우 카운터를 <key>0</>으로 한다",
    "e_generic_treasure": "카드를 <uadd>[</>{0}<uadd>]</>장 뽑고, 자신의 턴 드로우 카운터를 {1}로 한다",
    "e_generic_updraft": "자신의 필드 위에 있는 카드를 1장 패로 되돌린다 (<key>Updraft</> 제외)",
    "e_infinitenavigation": "이 카드가 등장하는 경우, 새로운 루트를 선택하여 자신의 덱을 편집한다. 이 카드가 필드에서 벗어나면 선택한 루트가 시작된다",
    "e_mage_aurelia_add": "트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.sorc</> 카드를 1장 패에 추가한다",
    "e_mage_aurelia_hand": "패의 카드를 1장 선택한다. 덱에서 가장 위의 카드를 패에 추가한 후, 선택한 카드를 덱으로 되돌리고 셔플한다",
    "e_mage_camilla": "자신의 필드 위에 있는 공격력이 <attack>0</>이면서 <img id=\"\"effect_init\"\"/> 효과를 1개 이상 가진 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 카드를 1장 선택한다. 선택한 카드의 왼쪽 끝의 <img id=\"\"effect_init\"\"/> 효과를 이 카드에 <img id=\"\"effect_manual\"\"/> 효과로서 추가하고, <img id=\"\"effect_once\"\"/><img id=\"\"effect_gunique\"\"/> 제한을 준다. 그 후, 선택한 카드를 트래쉬로 보낸다",
    "e_mage_decima_condition": "자신의 트래쉬에 <key>.sorc</> 카드가 정확히 <key>{0}</>장 있어야 한다",
    "e_mage_decima_init": "자신의 패를 버린다. 버린 카드 1장당, 이 카드의 카운터를 1 늘린다. 그 후, 이 효과가 발동했을 때, 자신의 트래쉬에 있던 모든 <key>.sorc</> 카드를 패에 추가한다",
    "e_mage_decima_trigger": "이 카드의 카운터가 0이 아닌 경우, 공격력이<attack>0</>인 카드를 꺼냈을 때, 이 카드의 카운터를 1 줄이고, 패에 있는 모든 공격력이 <attack>0</>인 카드의 <health>체력</>을<health>1</> 상승시킨다. 그 후, 카드를 1장 드로우한다",
    "e_mage_lucia_discard": "패를 1장 버리고, 앞쪽에 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_mage_lucia_search": "덱에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.sorc</> 카드를 1장 패에 추가한다",
    "e_mage_mariana_ability": "자신의 레벨 <uadd>[</><key>{1}</><uadd>]</> 이하의 카드가 이 카드의 앞쪽에 있는 경우, 그 카드를 덱으로 되돌리고 셔플한다. 그리고 자신의 <key>전열</>에 있는 모든 카드의 <health>체력</>을 <health>{0}</> 상승시킨다. 단, 이미 이 효과의 영향을 받고 있는 카드에게는 <health>체력</> 상승이 적용되지 않는다",
    "e_mage_mariana_init": "이 카드의 좌우에 있는 카드를 패로 되돌린다",
    "e_mage_mariana_movement": "이 카드가 다른 슬롯으로 이동한 경우, 이 카드의 <img id=\"\"effect_once\"\"/>를 리셋한다",
    "e_mage_mariana_movement_upgrade": "이 카드가 다른 슬롯으로 이동한 경우, 이 카드의 <img id=\"\"effect_once\"\"/>를 리셋하고, <uadd>[</>재활성화<uadd>]</>한다",
    "e_mage_octavia_ability": "자신의 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 카드가 이 카드의 앞쪽에 있는 경우, 그 카드의 왼쪽 끝의 <img id=\"\"effect_init\"\"/> 효과를 발동하고(효과의 제한은 무시된다), 자신의 덱으로 되돌린 후 셔플한다",
    "e_mage_octavia_init": "패를 1장 선택하고, 그 카드의 <health>체력</>을<health>1</> 상승시킨다",
    "e_mage_sharedadder": "이 카드가 카드를 뽑는 것 이외의 방법으로 패에 추가되었을 경우, 이 카드의 <health>최대 체력</>을 <health>현재 체력</><uminus>[</>+ <health>1</><uminus>]</>로 한다 (최대 : <uadd>[</><health>{0}</><uadd>]</>)",
    "e_mage_sharedadder_upgrade": "이 카드가 카드를 뽑는 것 이외의 방법으로 패에 추가되었을 경우, 이 카드의 <health>최대 체력</>을 <health>현재 체력</><uadd>[</>x<key>2</><uadd>]</>로 한다 (최대 : <uadd>[</><health>{0}</><uadd>]</>)",
    "e_mage_sorccreo": "<key>X</>장의 카드를 드로우한다. <key>X</>는 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다. 그 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다 (현재 : <key>{0}</>장)",
    "e_mage_sorceffingo": "자신의 트래쉬에 있는 <img id=\"\"effect_init\"\"/> 효과를 1개 이상 가진 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.sorc</>카드(<key>Effingo.sorc</> 제외)를 1장 선택한다. 가장 왼쪽 끝의 <img id=\"\"effect_init\"\"/> 효과를 이 카드의 효과로서 발동하고(효과의 제한은 무시된다), 자신의 덱으로 되돌린 후 셔플한다. 그, 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다",
    "e_mage_sorcgravitas": "모든 적 카드에게 <key>X</> <uminus>[</>- <magic>{1}</><uminus>]</><img id=\"\"dmg_magic\"\"/> <magic>마법 대미지</>를 준다. <key>X</>는 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다. 그 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다 (현재 : <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_mage_sorcgravitas_upgrade": "모든 적 카드에게 <key>X</><img id=\"\"dmg_magic\"\"/> <magic>마법 대미지</>를 준다. <key>X</>는 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다. 그 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다 (현재 : <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_mage_sorcignis": "앞쪽에 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> x <key>X</>의 <magic>마법 대미지</>를 준다. <key>X</>는 자신의 필드에 있는 이 카드의 모든 카피의 <health>체력</>의 합계이다. 그 후, 자신의 필드에 있는 모든 이 카드의 카피의 <health>최대 체력</>을 <health>1</>로 한다. (현재 피해량 = <magic>{1}</><img id=\"\"dmg_magic\"\"/>)",
    "e_mage_sorclux": "트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mage</> 카드를 <key>X</>장까지 패로 추가한다. <key>X</>는 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다. 그 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다 (현재 : X = <key>{1}</>)",
    "e_mage_sorcpotentia": "이 카드와 같은 가로열에 있는 모든 카드를 재활성화하고, <key>X</> + <attack>{0}</> <specialbuff>감소 버프</>를 준다(최대 + <key>{2}</>). <key>X</>는 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>체력</>의 합계가 된다. 그 후, 자신의 필드 위에 있는 이 카드의 모든 카피의 <health>최대 체력</>을 <health>1</>로 한다 (현재 : X = <key>{1}</>)",
    "e_mage_sorctempus": "모든 적을 <uadd>[</><key>{0}</><uadd>]</> + <key>X</>턴 지연시킨다.  <key>X</>는 자신의 필드에 있는 이 카드의 카피의 <health>체력</>의 합이다. 그 후, 자신의 필드에 있는 모든 이 카드의 카피의 <health>최대 체력</>은 <health>1</> 이 된다. (현재 지연: <key>{1}</>)",
    "e_mage_sorctempus_upgrade": "모든 적을 <uadd>[</><key>{0}</> x<uadd>]</> <key>X</>턴 지연시킨다.  <key>X</>는 자신의 필드에 있는 이 카드의 카피의 <health>체력</>의 합이다. 그 후, 자신의 필드에 있는 모든 이 카드의 카피의 <health>최대 체력</>은 <health>1</> 이 된다. (현재 지연: <key>{1}</>)",
    "e_mage_valeria_attack": "이 카드가 공격할 때, 이 카드의 좌우에 있는 레벨 <key>1</> 이하의 카드의 왼쪽 끝에 있는 <img id=\"\"effect_init\"\"/> 효과를 발동한다 (효과의 제한은 무시된다)",
    "e_mage_valeria_condition": "카드를 <key>{0}</>장 버린다",
    "e_mage_valeria_init": "자신의 덱에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.sorc</> 카드를 최대 2장까지 필드에 꺼낸다",
    "e_mdv_advancedsummon_plural": "자신의 카드가 정확히 <key>{0}</>장 파괴되었을 때, 이 카드를 필드에 꺼낸다",
    "e_mdv_advancedsummon": "자신의 카드가 정확히 <key>{0}</>장 파괴되었을 때, 이 카드를 필드에 꺼낸다",
    "e_mdv_axe_init": "앞쪽에 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_mdv_axe_passive": "이 카드에 대한 공격력 상승 효과는 <uadd>[</><key>{0}배</><uadd>]</>가 되지만, 이 카드가 공격하면 상승치는 리셋된다. 이 카드의 공격력이 <uadd>[</><attack>{1}</><uadd>]</>을 넘은 경우, 대신에 필드 위의 다른 모든 카드(자신의 카드 포함)에게 <physical>{2}</> 대미지를 준다",
    "e_mdv_axe": "이 카드의 공격력이 <uadd>[</><attack>{1}</><uadd>]</> 미만인 경우, 공격력을 <attack>{0}</> 상승시킨다",
    "e_mdv_core_init": "필드 위의 <key>.mech</> 카드를 1장 선택하고, 그 카드의 공격력을 <uadd>[</><attack>{0}</><uadd>]</> 상승시킨 후, <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_mdv_core": "필드 위의 카드를 1장 선택하고, 그 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_mdv_gatling_init": "이 카드의 카운터를 <uadd>[</><key>{0}</><uadd>]</> 늘린다",
    "e_mdv_gatling_passive": "자신의 필드 위에 있는 카드가 파괴될 때마다, 이 카드의 카운터를 <uadd>[</><key>{0}</><uadd>]</> 늘린다 (최대 : <uadd>[</><key>{1}</><uadd>]</>)",
    "e_mdv_gatling": "이 카드의 카운터를 리셋하고, 줄어든 카운터의 수와 같은 횟수만큼 공격한다 (현재 : <key>{0}</>회)",
    "e_mdv_hammer_init": "필드 위에 있는 다른 모든 카드에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다",
    "e_mdv_hammer": "체력이 <key>X</> 이하인 모든 카드(자신의 카드 포함)에게 <key>X</> 대미지를 준다. <key>X</>는 이 카드의 <attack>공격력</>이 된다",
    "e_mdv_hydro_init": "덱의 가장 위에 있는 카드를 트래쉬로 보낸다. 그 후, 트래쉬의 가장 위에서 카드를 <uadd>[</><key>{0}</><uadd>]</>장 본 뒤, 그 중에서 레벨 {1}인 <key>.mech</> 카드를 2장까지 필드에 꺼낸다 (<img id=\"\"effect_condition\"\"/>은 무시된다)",
    "e_mdv_hydro": "자신의 필드 위에 있는 카드를 1장 패로 되돌린다",
    "e_mdv_plasma_blast": "카드가 파괴될 때마다 이 카드의 카운터를 1 늘린다. 이 카드의 카운터가 <key>{0}</> 이하일 때, 카운터를 리셋하고 이 카드보다 앞에 있는 모든 카드(자신의 카드 포함)에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_mdv_plasma": "이 카드의 앞쪽에 있는 모든 카드(자신의 카드 포함)에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_mdv_podeffect": "자신의 덱에서 [레벨 <uadd>[</>{0}<uadd>]</> 이하] [<key>.mech</>] [공격력이<key> 1</> 이하]의 조건을 모두 가진 카드를 1장 선택한다. 그 후, 이 카드는 파괴된다. 선택한 카드를 이 카드가 있던 위치에 꺼내고 필드 위에 있는 다른 모든 카드에게 <physical>{1}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_mdv_rocket": "이 카드가 패에 있을때, 자신의 카드가 파괴될 때마다 이 카드의 카운터를 1 늘린다 (최대 : {0})",
    "e_mdv_rocketdamage": "이 카드의 카운터를 1 줄이고, 모든 적에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다. 이 카드의 카운터가 0이 될 때까지 이 효과를 반복한다 (현재 <physical>{0}x{1}</><img id=\"\"dmg_phys\"\"/> 대미지)",
    "e_mdv_signal": "이 카드를 제외한 자신의 카드는 자신의 카드에 의한 대미지를 받지 않는다. 대신 대미지 대상이 되는 자신의 카드 (<key>CommandTower</> 제외)를 재활성화한다",
    "e_mdv_signal_upgrade": "mdvSignal.u1,이 카드를 제외한 자신의 카드는 자신의 카드에 의한 대미지를 받지 않는다. 대신 대미지 대상이 되는 자신의 카드(<key>CommandTower</> 제외) <uadd>[</>가 받은 대미지와 같은 수치만큼 체력을 회복시키고 그 카드를 <uadd>]</>재활성화한다",
    "e_mdv_spear_init": "덱에서 레벨 <uadd>[</>{0}<uadd>]</> 이하의 <key>.mech</> 카드를 1장 패로 추가한다 (<key>Spear.mech</> 제외)",
    "e_mdv_sword_init": "앞쪽에 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다",
    "e_mdv_sword": "이 카드의 절반의 공격력으로 2회 공격한다(소수점 이하는 버린다) (현재 : <physical>{0}</><img id=\"\"dmg_phys\"\"/>x2)",
    "e_mdv_thunder_init": "적의 모든 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_mdv_thunder": "필드 위에 있는 카드를 1장 선택하고, 그 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_mdv_unity_condition": "자신의 필드 위에 정확히 <key>.mech</> 카드가 {0}장 있는 경우에만 필드에 꺼낼 수 있다 (현재 : {1}/{0}장)",
    "e_mdv_unity": "자신의 필드 위에 있는 카드의 <img id=\"\"effect_manual\"\"/> 효과를 모두 발동한다 (<img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다)",
    "e_muse_bass_group": "이 카드와 함께 <exec>실행</>된 카드는 그 카드의 체력과 같은 공격력을 얻는다",
    "e_muse_bass": "이 카드와 같은 가로열에 꺼낸 카드의 체력을 <uadd>[</><health>{0}</><uadd>]</> 상승시킨다",
    "e_muse_doubleeigth": "<uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지로 2회 공격한다",
    "e_muse_equalize": "패에서 카드를 1장 버리고, 카드를 <uadd>[</>{0}<uadd>]</>장 드로우한다",
    "e_muse_executemanualshared": "자신의 필드 위에 있는 카드 1장을 <exec>실행</>하고, 카드를 1장 드로우한다",
    "e_muse_fermata": "이 카드와 함께 <exec>실행</>된 카드는 필드에서 제거되지 않는다 (<key>Fermata.muse</> 제외)",
    "e_muse_forte": "이 카드와 같은 가로열에 있는 모든 <key>.muse</> 카드의 공격력을 <uadd>[</><key>{0}</><uadd>]</> 상승시킨다",
    "e_muse_idol1_init": "자신의 트래쉬에 있는 레벨 1 <key>.muse</> 카드 1장을 필드에 꺼낸다",
    "e_muse_idol1_init_upgrade": "자신의 트래쉬에 있는 <uadd>[</>레벨 2 이하<uadd>]</>인 <key>.muse</> 카드 1장을 필드에 꺼낸다",
    "e_muse_idol2_init": "자신의 덱 안에 있는 레벨 1 <key>.muse</> 카드 1장을 필드에 꺼낸다",
    "e_muse_idol2_init_upgrade": "자신의 덱 안에 있는 <uadd>[</>레벨 2 이하<uadd>]</>인 <key>.muse</> 카드 1장을 필드에 꺼낸다",
    "e_muse_idol2": "자신의 필드 위에 있는 카드 1장을 <exec>실행</>하고, 카드를 1장 드로우한다",
    "e_muse_idol3_init": "패의 레벨 1 <key>.muse</> 카드를 모두 버린다. 버린 카드 1장당 카드를 드로우한다",
    "e_muse_idol3_manual": "자신의 트래쉬에 있는 레벨 1 <key>.muse</> 카드 1장을 필드에 꺼낸다. 그 카드의 효과에는 <img id=\"\"effect_once\"\"/>가 추가된다",
    "e_muse_idol3_manual_upgrade": "자신의 트래쉬에 있는 <uadd>[</>레벨 2 이하<uadd>]</>인 <key>.muse</> 카드 1장을 필드에 꺼낸다. 그 카드의 효과에는 <img id=\"\"effect_once\"\"/>가 추가된다",
    "e_muse_idol4_init": "<uadd>[</>{0}<uadd>]</>장 카드를 드로우한다",
    "e_muse_idol4": "레벨 1 <key>.muse</> 카드를 1장,  패에서 자신의 필드에 꺼낸다",
    "e_muse_idol4_upgrade": "<uadd>[</>레벨 2 이하<uadd>]</>인 <key>.muse</> 카드를 1장, 패에서 자신의 필드에 꺼낸다",
    "e_muse_idol5_passive": "카드를 뽑을 때마다 이 카드의 공격력이 <uadd>[</><attack>{1}</><uadd>]</> 상승한다(현재 : <attack>+{2}</>) (최대 : <uadd>[</><attack>+{0}</><uadd>]</>). 이 카드로 공격한 후, 공격력 상승치는 리셋된다",
    "e_muse_idol5": "이 카드의 좌우에 있는 카드를 <exec>실행</>하고, 대상이 된 카드 1장당, 카드를 {0}장 드로우한다",
    "e_muse_idolboss_condition": "다른 카드를 패에서 1장 버린다",
    "e_muse_idolboss_init": "자신 필드 위에 있는 모든 카드의 카운터를 1 늘린다",
    "e_muse_idolboss_passive": "이 카드가 필드에 나와 있는 동안, 카운터가 0이 아닌 카드가 <exec>실행</>을 받았을 경우, 제거되는 대신에 카운터를 1 줄인다",
    "e_muse_piano": "자신의 필드 위에 있는 모든 카드의 최대 체력을 <uadd>[</><health>{0}</><uadd>]</> 상승시킨다",
    "e_muse_quarter": "앞쪽에 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 마법 대미지를 준다",
    "e_muse_quarterrest": "카드를 <uadd>[</>{0}<uadd>]</>장 드로우한다",
    "e_muse_treble_group": "이 카드와 함께 <exec>실행</>된 카드 1장당, 카드를 1장 드로우한다",
    "e_muse_treble": "이 카드와 같은 가로열에 꺼내진 카드의 공격력을 <uadd>[</><attack>{0}</><uadd>]</> 상승시킨다",
    "e_muse_triplet": "모든 적에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 마법 대미지를 준다",
    "e_natural_apple": "덱에서 이 카드와 같은 이름의 카드를 1장 패에 추가한다",
    "e_natural_apple_upgrade": "덱에서 이 카드와 같은 이름의 카드를 <uadd>[</>2장<uadd>]</> 패에 추가한다",
    "e_natural_banana": "자신의 트래쉬에 있는 레벨 1 <uminus>[</><key>.fruit</><uminus>]</> 카드 1장을(이 카드와 같은 이름의 카드 제외) 필드에 꺼낸다",
    "e_natural_banana_upgrade": "자신의 트래쉬에 있는 레벨 1 카드 1장을(이 카드와 같은 이름의 카드 제외) 필드에 꺼낸다",
    "e_natural_cherry": "카드를 <uadd>[</>{0}<uadd>]</>장 드로우한다",
    "e_natural_demeter_condition": "자신의 트래쉬에 레벨 1인 같은 이름의 <key>.fruit</> 카드가 {0}장 이상 있는 경우에만 필드에 꺼낼 수 있다 (현재 : {1}/{0})",
    "e_natural_demeter_trigger": "자신의 패에서 카드가 나왔을 때, 앞쪽에 이 카드의 공격력과 같은 <magic>마법 대미지</>를 준다",
    "e_natural_demeter": "자신의 트래쉬에 있는 레벨 1 카드를 선택하고, 선택된 카드와 같은 이름의 카드를 모두 패로 추가한다",
    "e_natural_fall": "자신의 필드 위에 있는 레벨 1의 <key>.fruit</> 카드 효과를 모두 제거한다. 그 후, 효과가 제거된 카드 수만큼 카드를 드로우한다",
    "e_natural_fall_upgrade": "자신의 필드 위에 있는 레벨 1의 <key>.fruit</> 카드 효과를 모두 제거한다. 그 후, 효과가 제거된 카드의 수만큼 카드를 뽑고, <uadd>[</>그 카드의 공격력을 <attack>1</> 상승시킨다<uadd>]</>",
    "e_natural_greenhouse": "이 카드의 뒤에 레벨 <uadd>[</>{0}<uadd>]</> 이하의 카드가 나왔을 때(<key>Greenhouse</> 제외), 나온 카드와 같은 이름의 카드가 자신의 트래쉬에 1장 이상 있는 경우, 그 카드를 트래쉬에서 1장 패에 추가한다",
    "e_natural_growth": "자신의 트래쉬에 있는 <uminus>[</><key>.fruit</><uminus>]</> 카드를 1장 선택한다. 선택된 카드와 같은 이름의 카드를 모두 트래쉬에서 덱으로 되돌리고, 덱으로 되돌려진 카드의 수만큼 카드를 드로우한다",
    "e_natural_growth_upgrade": "자신의 트래쉬에 있는 카드를 1장 선택한다. 선택된 카드와 같은 이름의 카드를 모두 트래쉬에서 덱으로 되돌리고, 덱으로 되돌려진 카드의 수만큼 카드를 드로우한다",
    "e_natural_lemon": "자신의 필드 위에 있는 이 카드와 같은 이름의 카드가 모두 공격한다",
    "e_natural_persephone_condition": "서로 다른 이름을 가진 레벨 1의 <key>.fruit</> 카드가 자신의 필드 위에 3장 이상 있는 경우에만 필드에 꺼낼 수 있다 (현재 {1}/{0})",
    "e_natural_persephone_init": "자신의 필드 위에 있는 다른 모든 카드를 <void>보이드</>하고, 대상이 된 카드 수를 2배로 한 수치가 이 카드의 공격력이 된다. 이 효과를 발동하기 위해서는 이 카드가 필드 위에 있어야 한다",
    "e_natural_persephone_passive": "이 카드가 공격한 후, 이 카드의 공격력이 {0} 감소하고, 모든 적에게 감소한 수치와 같은 <magic>마법 대미지</>를 준다",
    "e_natural_pollination": "자신의 덱 안에 있는 효과를 1개 이상 가진 레벨 1 <key>.fruit</> 카드를 1장 선택한다. 선택한 카드를 트래쉬에 보내고, 그 카드의 왼쪽 끝의 효과를 자신의 패에 있는 모든 레벨 1 <uminus>[</><key>.fruit</><uminus>]</> 카드에게 추가한다(단, 카드가 보유할 수 있는 효과는 3개까지). 추가된 효과에는 <img id=\"\"effect_once\"\"/>가 부여된다",
    "e_natural_pollination_upgrade": "자신의 덱 안에 있는 효과를 1개 이상 가진 레벨 1 <key>.fruit</> 카드를 1장 선택한다. 선택한 카드를 트래쉬에 보내고, 그 카드의 왼쪽 끝의 효과를 자신의 패에 있는 모든 레벨 1 카드에게 추가한다(단, 카드가 보유할 수 있는 효과는 3개까지). 추가된 효과에는 <img id=\"\"effect_once\"\"/>가 부여된다",
    "e_natural_pomegranate": "이 카드가 트래쉬에 보내졌을 때, 모든 적에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_natural_pomegranate_upgrade": "이 카드가 트래쉬에 보내졌을 때, <uadd>[</>모든 <expose>언커버</> 상태인 적에게<magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, 모든 <cover>커버</> 상태인 적에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다<uadd>]</>",
    "e_natural_pumpkin_trigger": "이 카드는 공격한 후, 파괴된다.",
    "e_natural_pumpkin": "자신의 필드 위에 있는 이 카드와 같은 이름의 모든 카드의 체력을 <uadd>[</>{0}<uadd>]</> 상승시킨다",
    "e_natural_spring": "자신의 트래쉬에 있는 레벨 <uadd>[</>{0}<uadd>]</> 이하의 <key>.fruit</> 카드를 1장 선택한다(<key>Spring.fruit</> 제외). 선택한 카드의 카피(초기상태)를 1장 필드에 꺼내고, 자신의 트래쉬에 있는 선택한 카드와 같은 이름을 가진 카드 1장 당 카피의 공격력을 <key>1</>상승시킨다 (최대 : +{3})",
    "e_natural_summer": "레벨 <uadd>[</>{0}<uadd>]</> 이하의 <key>.fruit</> 카드를 1장, 덱에서 패로 추가한다 (<key>Summer.fruit</> 제외)",
    "e_natural_winter": "자신의 덱의 <key>.fruit</> 카드를 1장 선택한다(<key>Winter.fruit</> 제외). 덱에 있는 선택한 카드와 같은 이름의 카드를 모두 트래쉬로 보내고, 보낸 카드 1장당, 자신의 필드 위에 있는 모든 카드를 <uadd>[</>{0}<uadd>]</> 회복한다",
    "e_potionhealth": "<img id=\"\"player_health\"\"/>를 <uadd>[</>{0}<uadd>]</> 회복한다",
    "e_potionstorage": "스토리지 용량을 <uadd>[</>{0}<uadd>]</> 늘린다 (최대 : +{1}) (현재 : +{2})",
    "e_potionvoid": "레벨 {0} 이하의 적을 모두 <void>보이드</>한다",
    "e_sakura_bow": "<uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 물리 대미지로 공격한다",
    "e_sakura_katana": "이 카드로 공격한다",
    "e_sakura_kunai": "모든 적에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다",
    "e_sakura_lantern": "덱에서 레벨 <uadd>[</>{0}<uadd>]</> 이하의 <key>.hana</> 카드를 1장 패에 추가한다 (<key>Lantern.hana</> 제외)",
    "e_sakura_ninja1": "이 카드의 뒤에 있는 <key>.hana</> 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다 (<img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다)",
    "e_sakura_ninja2": "패에서 필드로 레벨 <uadd>[</>{0}<uadd>]</> 이하의 <key>.hana</> 카드를 1장 꺼낸다",
    "e_sakura_ninja3_adder": "덱에서 뽑은 것 이외의 방법으로 이 카드가 패에 추가된 경우, 이 카드를 필드에 꺼낸다 (<img id=\"\"effect_condition\"\"/>은 무시된다)",
    "e_sakura_ninja3_condition": "이 카드 외의 카드를 1장 버린다",
    "e_sakura_ninja3": "자신의 트래쉬에 있는 <img id=\"\"effect_manual\"\"/> 혹은 <img id=\"\"effect_init\"\"/> 효과를 1개만 가지는 레벨 1 카드를 1장 선택한다. 그 후, 선택된 카드의 효과를 이 카드가 발동한다 (<img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다)",
    "e_sakura_ninja3_upgrade": "자신의 트래쉬에 있는 <img id=\"\"effect_manual\"\"/> 혹은 <img id=\"\"effect_init\"\"/> 효과를 1개만 가지는 레벨 1 카드를 1장 선택한다. 그 후, 선택된 카드를 이 카드가 <uadd>[</>2번<uadd>]</> 발동한다 (<img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다)",
    "e_sakura_ninja4": "이 카드의 좌우에 있는 레벨 <uadd>[</>{0}<uadd>]</> 이하의 카드의 <img id=\"\"effect_manual\"\"/> 효과(초기상태)를 이 카드에 복제한다. 단, 좌우의 카드에게서 각 1개씩만 복제할 수 있다",
    "e_sakura_ninjaboss_condition": "자신의 필드 위에 있는 <key>Bloom.hana</> 1장과 레벨 2인 <key>.hana</> 카드 1장을 <decompile>디컴파일</>한다",
    "e_sakura_ninjaboss": "이 카드의 좌우에 있는 <key>.hana</> 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. <img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다",
    "e_sakura_priestess_condition": "자신의 필드 위에서 <img id=\"\"effect_once\"\"/><img id=\"\"effect_manual\"\"/> 효과가 정확히 <key>{0}</>번 사용되야 한다",
    "e_sakura_priestess": "자신 필드 위에 있는 모든 카드의 <img id=\"\"effect_once\"\"/> 효과를 리셋하고, 자신의 카드를 모두 재활성화한다. 그리고 모든 적을 <uadd>[</><key>{0}</><uadd>]</>턴 지연시킨다",
    "e_sakura_shide": "필드 위의 <key>.hana</> 카드 1장의(<key>Shide.hana</> 제외) <img id=\"\"effect_once\"\"/> 효과를 리셋하고, 자신의 패로 되돌린다. <uminus>[</> 이 효과를 발동한 경우, <uminus>]</>추가로 카드를 1장 드로우한다",
    "e_sakura_shide_upgrade": "필드 위의 <key>.hana</> 카드 1장의(<key>Shide.hana</> 제외) <img id=\"\"effect_once\"\"/> 효과를 리셋하고, 자신의 패로 되돌린다. 그리고 카드를 1장 드로우한다",
    "e_sakura_storm": "<uminus>[</>이 카드와 같은 가로열에 있는 모든 <uminus>]</><key>.hana</> 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. <img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다",
    "e_sakura_storm_upgrade": "자신 필드 위에 있는 모든 <key>.hana</> 카드의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. <img id=\"\"effect_once\"\"/> 효과의 제한은 무시된다",
    "e_sakura_torii_condition": "자신의 필드 위에 있는 <key>.hana</> 카드 1장을 <decompile>디컴파일</>한다",
    "e_sakura_torii": "자신의 카드의 공격이 이 카드를 통과한 경우, 그 공격력을 <uadd>[</>{0}배<uadd>]</>로 한다",
    "e_spdeckedit_manual": "이 카드가 트래쉬에 있는 경우, 이 카드를 덱으로 되돌리고 셔플한다",
    "e_spdeckedit": "덱 에디터를 연다. 덱을 편집한 후, 자신의 필드와 모든 카드가 <key>리로드</>된다",
    "e_spdeckreload": "자신의 카드를 모두 <key>리로드</>한다 (트래쉬, 필드, 패를 모두 덱으로 되돌리고, 새로운 패를 드로우한다)",
    "e_spinstantdraft": "대량의 <img id=\"\"loot\"\"/>를 입수하고, 덱 에디터를 연다. 덱을 편집한 후, 카드를 <key>리로드</>한다",
    "e_spirit_amaterasu1": "<key>턴 드로우</>했을 때, 필드, 트래쉬, 그리고 패에 있는 모든 다른 카드를 덱으로  되돌립니다. 덱을 섞은 후, <key>{0}</>개의 카드를 뽑고 모든 적의 카드를<key>{1}</>턴 동안 지연시킨다.",
    "e_spirit_amaterasucondition": "자신의 패, 트래쉬, 덱, 그리고 필드에 정확히 <key>{0}</>장의 카드가 있어야 한다.",
    "e_spirit_amaterasuappear": "모든 적 카드에게 <key>X</> <img id=\"\"dmg_magic\"\"/> 피해를 입힙니다. <key>X</>는 자신의 트래쉬에 있는 다른 이름의 카드 수입니다 (현재 <key>X</>=<magic>{0}</>)(최대 <key>{1}</>). 그 후, 트래쉬의 모든 카드를 자신의 덱으로 되돌리고 셔플한다.",
    "e_spirit_bounce": "<key>턴 드로우</>했을 때, 이 카드를 패로 되돌린다",
    "e_spirit_swarm": "이 카드와 인접한 다른 카드가 없다면(대각선 제외), 자신의 트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.spirit</> 카드를 이 카드와 인접한 칸에 놓는다(대각선 제외).",
    "e_spirit_bouncecondition": "자신의 카드가 정확히 <key>{0}</>장의 카드가 패에 되돌아 왔을 경우에만 이 카드를 필드에 꺼낼 수 있다.",
    "e_spirit_countcondition": "자신의 필드와 패에 총 <key>{0}</>장의 카드가 있어야 한다(현재 {1}/{0}).",
    "e_spirit_kitsunehand": "[패]:{b}이 카드를 버린다. 모든 <expose>언커버</> 상태의 적 카드에게 <uadd>[</><magic>{handDmg}</><img id=\"\"dmg_magic\"\"/><uadd>]</>의 데미지를 준다.{b}",
    "e_spirit_kitsunefield": "[필드]:{b}적 카드를 선택한다. <magic>X</><img id=\"\"dmg_magic\"\"/>만큼의 피해를 준다. <magic>X</>는 이 카드에 <pathed>연결</>된 모든 <key>.spirit</> 카드의 <attack>공격력</> 합계다 (현재: <magic>{currentFieldDmg}</><img id=\"\"dmg_magic\"\"/>)(최대: <uadd>[</><key>{maxDmg}</><uadd>]</>), 그 후, <pathed>연결</>된 카드들의 <attack>공격력</>을 <attack>1</>만큼 감소시킨다.",
    "e_spirit_tsuruhand": "[패]:{b}이 카드를 버린다. 자신의 필드 위의 <key>.spirit</> 카드 중 원래 <attack>공격력</>이 <attack>1</> 이상인 모든 카드는 <uadd>[</><attack>+{handBuff}</><uadd>]</> 공격력을 얻는다.(최대 <uadd>[</><key>+{handBuff}</><uadd>]</>).{b}",
    "e_spirit_tsurufield": "[필드]:{b}이 카드에 <pathed>연결</>된 모든 <key>.spirit</> 카드로 공격한 후, 그들의 <attack>공격력</>을 <attack>1</>만큼 감소시킵니다.",
    "e_spirit_kusanagiinit": "인접한 모든 카드들은 (대각선을 제외하고) <uadd>[</><attack>+{0}</><uadd>]</>의 공격력을 얻는다.(최대 <uadd>[</><key>+{0}</><uadd>]</>).",
    "e_spirit_kusanagireaction": "자신의 패에 카드가 추가될 때 (이 카드를 뽑았을 때는 제외), 이 카드에 <uadd>[</><attack>+{0}</><uadd>]</> <specialbuff>단발 버프</>를 부여한다 (최대: <uadd>[</><attack>+{1}</><uadd>]</>).",
    "e_spirit_magatamainit": "덱에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.spirit</> 카드를 패에 추가한다.",
    "e_spirit_magatamatrigger": "카드가 (이 카드를 뽑았을 때는 제외) 자신의 패에 추가될 때, 이 카드에<key>{0}</>개의 카운터를 추가한다 (최대 <uadd>[</><key>{1}</><uadd>]</>).",
    "e_spirit_magatamadefense": "이 카드에 <key>카운터</>가 올려져 있는 동안, 자신의 카드가 받을 피해는 대상의 <health>체력</>이 아닌 이 카드의 <key>카운터</>를 제거한다.",
    "e_spirit_yatainit": "패에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.spirit</> 카드(단, <key>Yata.spirit</> 제외)를 선택하고, 그 카드의 <key>카피</>을 트래쉬에 생성한다.",
    "e_spirit_yatatrigger": "이 카드가 <key>활성화</>된 상태에서 (이 카드를 뽑았을 때는 제외) 자신의 패에 카드가 추가될 때, 패에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.spirit</> 카드를 필드에 냅니다. 그 후, 이 카드를 비활성화한다.",
    "e_spirit_nekohand": "[패]: {b}자신의 패에서 <key>.spirit</> 카드를 선택한다.(<key>Neko.spirit</>은 제외). 이 카드와 선택한 카드를 버리고, 그 후, 카드를 <uadd>[</><key>{draw}</><uadd>]</>장 뽑는다.{b}",
    "e_spirit_nekofield": "[필드]: {b}<key>X</>장 뽑는다. 여기서 <key>X</>는 이 카드에 <pathed>연결</>된 모든 <key>.spirit</> 카드의 총 <attack>공격력</>이다. (현재: <key>{fieldDraw}</>) (최대: <uadd>[</><key>{fieldDrawMax}</><uadd>]</>). 그 후, <pathed>연결</>된 카드들의 <attack>공격력</>을 <attack>1</>만큼 감소시킨다.{b}",
    "e_spirit_nezumitrigger": "<key>.spirit</> 카드가 (<key>Nezumi.spirit</>는 제외) <img id=\"\"effect_manual\"\"/> 또는 <img id=\"\"effect_init\"\"/> 효과를 발동할 때:",
    "e_spirit_nezumihand": "{b}[패]:{b} 이 카드를 필드에 놓는다.{b}",
    "e_spirit_nezumifield": "[필드]: 이 카드로 공격한 후, 이 카드의 <attack>공격력</>을 <attack>1</>만큼 감소시킵니다.",
    "e_spirit_sikahand": "[패]: 자신의 필드에서 적어도 하나의 <img id=\"\"effect_manual\"\"/> 효과를 가진 레벨 <key>{lvTarget}</>의 <key>.spirit</> 카드를 선택하고, 그 카드의 모든 <img id=\"\"effect_manual\"\"/> 효과를 발동한다( <img id=\"\"effect_once\"\"/> 제한은 무시한다).",
    "e_spirit_sikafield": "[필드]: 이 카드와 <pathed>연결</>된 모든 <key>.spirit</> 카드들의 <attack>공격력</>의 총합이 정확히 <key>X</>일 때, 모든 적들을 <key>X</>턴만큼 지연시키고 (현재: <key>{currentDelay}</>)(최대: <uadd>[</><key>{maxDelay}</><uadd>]</>), <pathed>연결</>된 카드들의 <attack>공격력</>을 <attack>1</>만큼 감소시킨다.",
    "e_spirit_tanzakuinit": "이 카드와 인접한 (대각선을 제외한) 모든 레벨 <key>{0}</>의 <key>.spirit</> 카드들의 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. ( <img id=\"\"effect_once\"\"/> 제한은 무시한다).",
    "e_spirit_tsukuyomibuff": "자신의 필드에 카드가 나올 때마다, 이 카드에 카운터를 추가한다. 이 카드에 <key>{0}</>개의 카운터가 있을 때 카드가 나오면, 이 카드의 모든 카운터를 제거하고, 활성화할 수 있는 카드의 모든 <img id=\"\"effect_manual\"\"/> 효과를 발동한다. 그 후, 이 카드의 <key>공격력</>을 <attack>{1}</>만큼 증가시킨다.",
    "e_spirit_watatsumihand": "[패]: 이 카드를 버린다. 자신의 필드에 있는 모든 카드의 상태 변화를 제거한다.",
    "e_spirit_watatsumifield": "[필드]: 자신 손패의 모든 카드를 덱에 넣고 섞는다. 섞은 카드의 수 만큼 이 카드의 공격력과 체력을 <attack>+1</>|<health>+1</>씩 증가시킨다. (현재 <attack>+{buffAmt}</>|<health>+{buffAmt}</>)(최대 <uadd>[</><attack>+{max}</>|<health>+{max}</><uadd>]</>). 그 후, <uadd>[</><key>{redraw}</><uadd>]</>장 뽑는다.",
    "e_spirit_yamatahand": "[패]: 이 카드를 버린다. 모든 적 카드에게 <uadd>[</><magic>{handDmg}</><img id=\"\"dmg_magic\"\"/><uadd>]</>의 대미지를 입힌다.",
    "e_spirit_yamatafield": "[필드]: 자신 손패의 모든 카드를 덱에 넣고 섞는다. 섞은 카드의 수와 같은 <expose>언커버</>된 적에게 <magic>{fieldDmg}</>의 <magic>대미지</>를 입힌다.(현재 <magic>{fieldDmg}</> <img id=\"\"dmg_magic\"\"/>). 그 후, <uadd>[</><key>{redraw}</><uadd>]</>장 뽑는다.",
    "e_spirit_dragoncondition": "자신 필드에 있는 <key>비활성</>상태이면서 공격력이 <key>0</>인 <key>.spirit</> 카드 두 장을 패로 되돌린다.",
    "e_spirit_dragonbounce": "<key>턴 드로우</>를 할 때, 패에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.spirit</> 카드를 필드로 놓고, 그렇게 했다면 이 카드를 덱에 넣고 섞는다.",
    "e_spstoragehit": "자신의 <key>스토리지</>에서 카드를 1장 자신의 패로 추가한다. <key>스토리지</>에 카드가 없는 경우, 덱에서 카드를 2장 드로우한다",
    "e_vamp_gen1_condition": "자신의 필드에 카드가 정확히 <key>{0}</>장 있고, 그 카드들은 같은 <attack>공격력</>이어야 한다",
    "e_vamp_gen1_init": "공격력이 <attack>1</> 이상인 모든 카드로 공격하고, 그 외의 카드를 패로 되돌린다",
    "e_vamp_gen1_manual": "자신의 필드 위의 카드를 1장 선택한다. 그 카드의 공격력이 <attack>1</> 이상인 경우, 그 카드로 공격한다. 그렇지 않은 경우에는 패로 되돌린다",
    "e_vamp_gen2_condition": "자신의 트래쉬에 <key>.blood</> 카드가 정확히 <key>{0}</>장 있어야 한다 (현재 : {1}/{0}장)",
    "e_vamp_gen2_groupattack": "자신의 필드 위에 있는 체력이 <health>1</>인 모든 카드로 공격한다",
    "e_vamp_gen2_manual": "자신의 트래쉬에 있는 <key>.blood</> 카드를 1장 선택하고 <void>보이드</>시키고, 필드 위의 임의의 장소에 스테이터스가 <uadd>[</><attack>{0}</><uadd>]</>|<health>1</>인 미니언을 소환한다. 그 후, 이 카드를 재활성화한다",
    "e_vamp_hyper": "모든 적에게 자신의 필드 위에 있는 카드의 수와 같은 <magic>마법 대미지</>를 준다(최대 : <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지) (현재 : <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지). 그 후, 자신의 필드 위에 있는 모든 카드에게 <magic>1</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_vamp_lieu1": "덱에서 레벨 <key>{0}</> 이하의 <key>.legion</> 카드를 <key>X</>장 패로 추가한다. <key>X</>는 이 카드의 공격력의 절반이 된다(현재 : <key>X = {1}</>). 그 후, 이 카드에게서 모든 스테이터스 보정을 제거한다",
    "e_vamp_lieu2": "덱에서 레벨 <key>{0}</> 이하의 <key>.blood</> 카드를 <key>X</>장 패로 추가한다. <key>X</>는 이 카드의 공격력의 절반이 된다(현재 : <key>X = {1}</>). 그 후, 이 카드에게서 모든 스테이터스 보정을 제거한다",
    "e_vamp_lifesteal": "이 카드가 <img id=\"\"dmg_phys\"\"/> <physical>대미지</>를 받았을 때, 체력이 <health>{0}</> 회복되고, 공격력이 <attack>1</> 상승한다(최대 : <attack>+{1}</>). 이 카드가 대미지를 받은 경우, 공격력이 <attack>1</> 감소한다",
    "e_vamp_orb_destruction": "카드를 1장 드로우한다",
    "e_vamp_orb": "패에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.legion</> 카드를 1장 필드에 꺼낸다",
    "e_vamp_origin": "자신의 트래쉬에 있는 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.blood</> 카드(<key>Origin.blood</> 제외)를 <key>X</>장 선택한다. <key>X</>는 자신의 필드 위에 있는 체력이 <health>1</>인 카드의 수가 된다(현재 : <key>X = {1}</>장). 그 후, 선택한 카드를 패에 추가하고, 자신의 필드 위에 있는 체력이 <health>1</>인 카드를 모두 <decompile>디컴파일</>한다",
    "e_vamp_plunge_trigger": "1턴 후에 이 카드가 패에 있는 경우, 이 카드를 버린다",
    "e_vamp_plunge": "필드 위에 있는 체력이 <health>{0}</>인 카드(<key>Plunge.blood</> 제외)를 1장 선택하고 파괴한다. 파괴된 카드와 같은 쪽의 필드에 있는 모든 카드에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다. 그 후, 이 카드를 자신의 패로 되돌린다",
    "e_vamp_revival": "자신의 트래쉬에 있는 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.legion</> 카드를 1장 선택하고 필드에 꺼낸다",
    "e_vamp_shield_revive": "트래쉬에서만 발동할 수 있다. 이 카드를 패에 추가하지만, 효과를 모두 제거하고, 스테이터스를 <attack>0</>|<health>1</>로 변경한다",
    "e_vamp_shield": "이 카드에게 대미지를 준 카드에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 되돌려준다",
    "e_vamp_simpledamagefront": "이 카드의 1칸 앞쪽에 있는 카드에게 <physical>1</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_vamp_sol1": "이 카드가 대미지를 받았을 때(혹은 종료시에 필드에 존재할 때), 카드를 <key>{0}</>장 드로우한다",
    "e_vamp_sol3": "이 카드가 대미지를 받았을 때(혹은 종료시에 필드에 존재할 때), 모든 <expose>언커버</> 상태의 적 카드에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_vamp_spear_trigger": "이 카드로 적의 카드를 파괴한 경우, 패로 되돌린다",
    "e_vamp_spear": "이 카드보다 앞쪽에 있는 모든 카드(자신의 카드 포함)에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다. 카드가 1장밖에 없을 경우에는 그 대신에 <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_vamp_surrounddamage": "이 카드의 상하좌우의 카드에게 <physical>1</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_vamp_sword_coattack": "이 카드와 같은 세로열에 있는 카드가 공격하는 경우(<key>Sword.blood</> 제외), 이 카드로 공격한다",
    "e_vamp_sword_credit": "이 카드의 공격은 같은 세로열에 있는 다른 자신의 카드에 의한 것으로 취급된다",
    "e_cross_ctroncharge": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만인 상태에서 다른 카드를 <key>패</>에서 꺼내는 경우, 이 카드를 재활성화하고, 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_ctronshot": "이 카드가 활성화인 경우, 적의 카드가 다른 카드에게서 대미지를 받았을 때(혹은 파괴되지 않았을 때), 이 카드를 비활성화하고, 대미지를 받은 카드에게 이 카드의 <attack>공격력</>과 같은 <img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_cross_ctronbuff": "이 카드의 카운터가 0이 아닌 경우, 필드 위의 자신의 카드를 1장 선택하고(<key>C'tron.cross</> 제외), 이 카드의 카운터를 선택한 카드에게 이동시킨다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_eleheatburst": "이 카드의 <align>직선상</>에 있는 자신의 카드의 카운터를 리셋한다(이 카드 포함). 그 후, 리셋한 카운터의 수만큼 효과를 발동한다 {b}{b}[<key>{0}+</>] : <physical>4</><img id=\"\"dmg_phys\"\"/> 대미지로 공격한다 {b}[<key>{1}+</>] : <physical>2</><img id=\"\"dmg_phys\"\"/> + <physical>2</><img id=\"\"dmg_phys\"\"/> + <physical>4</><img id=\"\"dmg_phys\"\"/> 대미지로 3회에 걸쳐 차례로 공격한다 {b}{b} 그리고 이 카드를 <decompile>디컴파일</>하고, 카드를 1장 드로우한다",
    "e_cross_eleheatpassive": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, 이 카드의 <align>직선상</>에 있는 <attack>공격력</>이 <attack>1</> 이상인 자신의 카드가 대미지를 준 경우, 대미지를 받은 대상에게 <physical>{1}</><img id=\"\"dmg_phys\"\"/> 대미지를 주고, 이 카드의 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_eleheatplay": "이 카드의 <align>직선상</>에 있는 자신의 다른 카드에게 <key>{0}</> <specialbuff>감소 버프</>를 주고, 재활성화한다",
    "e_cross_elecoldburst": "이 카드의 <align>직선상</>에 있는 자신의 카드의 카운터를 리셋한다(이 카드 포함). 그 후, 리셋한 카운터의 수만큼 효과를 발동한다 {b}{b}[<key>{0}+</>] : 모든 적을 <key>3</>턴 지연시킨다 {b}[<key>{1}+</>] : 모든 적을 <key>6</>턴 지연시킨다 {b}{b} 그리고 이 카드를 <decompile>디컴파일</>하고, 카드를 1장 드로우한다",
    "e_cross_elecoldpassive": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, 이 카드의 <align>직선상</>에 있는 <attack>공격력</>이 <attack>1</> 이상인 자신의 카드가 대미지를 받은 경우, 대미지를 준 대상에게 <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 주고, 이 카드의 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_elecoldplay": "이 카드의 <align>직선상</>에 있는 자신의 다른 카드의 <health>체력</>을 <uadd>[</><health>{0}</><uadd>]</> 상승시키고, 재활성화한다",
    "e_cross_eleshockburst": "이 카드의 <align>직선상</>에 있는 자신의 카드의 카운터를 리셋한다(이 카드 포함) 그 후, 리셋한 카운터의 수만큼 효과를 발동한다 {b}{b}[<key>{0}+</>] : 앞쪽에 <magic>2</><img id=\"\"dmg_magic\"\"/> 대미지를 준다. 이 대미지는 인접한 적에게 확산한다(대각선 방향은 무시된다) {b}[<key>{1}+</>] : 앞의 대미지가 <magic>4</><img id=\"\"dmg_magic\"\"/> 로 늘어난다 {b}{b} 그리고 이 카드를 <decompile>디컴파일</>하고, 카드를 1장 드로우한다",
    "e_cross_eleshockpassive": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, 이 카드의 <align>직선상</>에 있는 <attack>공격력</>이 <attack>1</> 이상인 자신의 카드가 대미지를 준 경우, 대미지를 받은 대상을 <key>{1}</>턴 <key>지연</>시키고(<key>지연내성</>이 있는 경우에는 대신에 <magic>{2}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다), 이 카드의 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_eleshockplay": "이 카드와 같은 세로열, 가로열에 있는 모든 카드를(가능하다면) 이 카드 쪽으로 <key>1</>칸 끌어당긴다",
    "e_cross_elewaveburst": "이 카드의 <align>직선상</>에 있는 자신의 카드의 카운터를 리셋한다(이 카드 포함). 그 후, 리셋한 카운터의 수만큼 효과를 발동한다 {b}{b}[<key>{0}+</>] : 패에서 레벨 <key>2</> 이하의 카드를 1장 필드에 꺼내고, 그 카드의 카운터를 <key>3</> 늘린다 {b}[<key>{1}+</>] : 카드 2장에게 같은 효과를 적용한다 {b}{b} 그리고 이 카드를 <decompile>디컴파일</>하고, 카드를 1장 드로우한다",
    "e_cross_elewavepassive": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, 이 카드의 <align>직선상</>에 있는 <attack>공격력</>이 <attack>1</> 이상인 자신의 카드가 대미지를 준 경우, 카드를 1장 뽑고, 이 카드의 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_elewaveplay": "이 카드와 같은 세로열, 가로열에 있는 모든 카드를(가능하다면) 이 카드를 중심으로 <key>1</>칸 밀어낸다",
    "e_cross_emilienatorcharge": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만의 상태에서 필드 위를 이동했을 때, 이 카드를 재활성화하고 앞쪽에 <physical>1</><img id=\"\"dmg_phys\"\"/> 대미지를 준다. 그 후, 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_emilienatorbeat": "이 카드의 카운터가 0이 아닌 경우, 1칸 앞쪽에 있는 적의 카드에게 카운터의 수만큼 <physical>{0}</><img id=\"\"dmg_phys\"\"/>의 대미지를 준다. 적에게 <key>지연내성</>이 있는 경우, 그 대신에 <physical>{1}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다. 그 후, 이 카드의 카운터를 리셋한다",
    "e_cross_emilienatordash": "이 카드가 활성화인 경우, 적의 카드가 다른 카드에게서 대미지를 받았을 때(혹은 파괴되지 않았을 때), 대미지를 받은 카드와 같은 세로열 및 전열로 이동한다 (그 장소에 카드가 있는 경우에는 뒤바꾼다)",
    "e_cross_emilienatorplay": "카드를 1장 드로우한다",
    "e_cross_leacharge": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, <img id=\"\"dmg_phys\"\"/> 대미지를 준 경우, 재활성화하고 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_leashot": "이 카드의 카운터가 0이 아닌 경우, 적의 카드를 1장 선택하고 <magic>{0}</><img id=\"\"dmg_magic\"\"/> x <key>X</> 대미지를 준다. <key>X</>는 이 카드의 카운터의 수가 된다. 그 후, 이 카드의 카운터를 리셋한다",
    "e_cross_leasearch": "덱에서 <key>.element</> 카드를 1장 패에 추가한다",
    "e_cross_counter_condition": "자신의 필드 위에 있는 카운터가 1 이상인 카드를 <key>{0}</>장 선택한다. 그 카운터를 이 카드로 이동시키고, 선택한 카드를 자신의 덱으로 되돌린 후, 셔플한다",
    "e_cross_lukasslash": "이 카드의 <key>카운터</>의 수<key>x{0}</>와 같은 <img id=\"\"dmg_magic\"\"/> 대미지를 이 카드의 <align>직선상</>에 있는 모든 적에게 준다(최대 : <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지). 그 후, 이 카드의 카운터를 리셋한다 (현재 : <magic>{2}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_cross_joernsearch": "레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.cross</> 카드를 덱에서 패로 추가한다(<key>Joern.cross</> 제외). 그 후, 이 카드의 카운터를 리셋하고, 선택한 카드에 같은 수의 카운터를 늘린다 (최대 : <uadd>[</><key>{1}</><uadd>]</>)",
    "e_cross_apollocharge": "이 카드의 카운터가 <uadd>[</><key>{0}</><uadd>]</> 미만일 때, 자신의 카드가 대미지를 받은 경우, 이 카드를 재활성화하고, 카운터를 1 늘린다 (최대 : <uadd>[</><key>{0}</><uadd>]</>)",
    "e_cross_apollosearch": "트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.cross</> 카드(<key>Apollo.cross</> 제외)를 1장 패에 추가한다",
    "e_cross_hlinplay": "덱에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.cross</> 카드를 1장 선택하고, 필드에 꺼낸다",
    "e_cross_hlindefense": "이 카드가 대미지를 받았을 때, 이 카드의 카운터의 수만큼 대미지를 경감한 후, <key>X</> <specialbuff>단발 버프</>를 얻는다. 그리고 뒤쪽의 카드의 카운터를 <key>X</> 늘린다. <key>X</>는 이 카드의 카운터의 절반의 수치(올림)가 된다 (최대 : <uadd>[</><key>{0}</><uadd>]</>). 그 후, 이 카드의 카운터를 절반(올림) 줄인다",
    "e_cross_buggyslash": "이 카드의 바로 앞쪽과 바로 대각선에 있는 적에게 <magic>{0}</><img id=\"\"dmg_magic\"\"/> x <key>X</> 대미지를 준다(최대 : <uadd>[</>X = <key>{1}</><uadd>]</>). <key>X</>는 이 카드의 <key>카운터</>의 수가 된다. 그 후, 이 카드의 카운터를 리셋한다 (현재 : <magic>{0}</><img id=\"\"dmg_magic\"\"/>x<key>{2}</> 대미지)",
    "e_cross_albertplay": "적 카드를 <uadd>[</><key>{0}</><uadd>]</>장까지 선택하고, <key>X</><img id=\"\"dmg_magic\"\"/> 대미지를 준다. <key>X</>는 이 카드의 카운터의 수가 된다 (최대 : <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지)",
    "e_cross_albertfield": "패에서 카드를 꺼냈을 때, 이 카드의 카운터를 1 줄이고, 꺼낸 카드의 카운터를 1 늘린다",
    "e_cross_shizukacondition": "자신의 필드에 정확히 <key>{0}</> 카운터가 있어야 한다(현재 : {1}/{0}). 모든 카운터를 이 카드로 이동시킨다",
    "e_cross_shizukaplay": "모든 <expose>언커버</> 상태인 적에게 <physical>{0}</><img id=\"\"dmg_phys\"\"/>의 대미지를 준다",
    "e_cross_shizukaburst": "이 카드와 <key>직선상</>에 있는 자신의 카드의 카운터를 리셋하고, 앞쪽에 <key>X</><img id=\"\"dmg_phys\"\"/> 대미지를 준다.  <key>X</>는 리셋한 카운터의 수의 합계가 된다 (현재 : <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지)",
    "e_mahou_bunny_fire_summon": "패에서 <key>Akane.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_fire_attack": "필드 위에 있는 다른 카드를 선택한다. 이 카드를 <decompile>디컴파일</>하고, 선택한 카드에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_mahou_girl_fire_proc": "이 카드에게 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 이 카드로 공격한다",
    "e_mahou_girl_fire_summon": "트래쉬에서 <key>Kufi.mahou</>를 1장, 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯은 제외)",
    "e_mahou_bunny_earth_summon": "패에서 <key>Chie.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_earth_attack": "적의 카드를 <uadd>[</><key>{0}</><uadd>]</>장까지 선택한다. 이 카드를 <decompile>디컴파일</>하고, 선택한 카드에게 <magic>{1}</><img id=\"\"dmg_magic\"\"/> 대미지를 준다",
    "e_mahou_girl_earth_proc": "이 카드에 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 이 카드의 앞쪽에 있는 적 카드와 같은 체력을 가진 모든 적 카드에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다",
    "e_mahou_girl_earth_summon": "트래쉬에서 <key>Kuea.mahou</>를 1장, 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_water_summon": "패에서 <key>Aoi.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_water_attack": "이 카드를 <decompile>디컴파일</>하고, 카드를 <uadd>[</><key>{0}</><uadd>]</>장 드로우한다",
    "e_mahou_girl_water_proc": "이 카드에 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 자신의 트래쉬에서 가장 위에 있는 카드가 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하라면, 가장 왼쪽 끝의 <img id=\"\"effect_manual\"\"/> 효과를 이 카드의 효과로서 발동한다 (효과의 제한은 무시된다)",
    "e_mahou_girl_water_summon": "트래쉬에서 <key>Kuwa.mahou</>를 1장, 이 카드에게 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_wind_summon": "패에서 <key>Kazane.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯은 제외)",
    "e_mahou_bunny_wind_attack": "자신의 필드 위에 있는 다른 카드를 <uadd>[</><key>{0}</><uadd>]</>장까지 선택한다. 이 카드를 <decompile>디컴파일</>하고, 선택한 카드를 패로 되돌린다",
    "e_mahou_girl_wind_proc": "이 카드에 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 패에 있는 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 카드(<key>Kazane.mahou</> 제외)를 선택하고, 자신의 필드에 꺼낸다",
    "e_mahou_girl_wind_summon": "트래쉬에서 <key>Kuwi.mahou</>를 1장, 이 카드에 인접한 슬롯에 배치한다 (대각선 방향은 제외)",
    "e_mahou_bunny_dark_summon": "패에서 <key>Tsukiyo.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯은 제외)",
    "e_mahou_bunny_dark_attack": "이 카드를 <decompile>디컴파일</>하고, 모든 적에게 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 대미지를 준다",
    "e_mahou_girl_dark_proc": "이 카드가 활성화일 때, 이 카드에 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 자신의 트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mahou</> 카드를 1장 패로 추가한다(<key>Tsukiyo.mahou</> 제외). 그 후, 이 카드를 비활성화한다",
    "e_mahou_girl_dark_summon": "트래쉬에서 <key>Kuda.mahou</> 를 1장, 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_light_summon": "패에서 <key>Hoshiko.mahou</>를 1장(여러 장인 경우에는 왼쪽 끝에서), 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_bunny_light_attack": "이 카드를 <decompile>디컴파일</>하고, 모든 적에게 <uadd>[</><key>{0}</><uadd>]</>턴 <key>지연</>시킨다",
    "e_mahou_girl_light_proc": "이 카드가 활성화일 때, 이 카드에 인접한 카드(대각선 방향 제외)가 파괴되지 않고 필드에서 제거된 경우, 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mahou</> 카드를 1장, 덱에서 필드로 꺼낸다(<key>Hoshiko.mahou</> 제외). 그 후, 이 카드를 비활성화한다",
    "e_mahou_girl_light_summon": "트래쉬에서 <key>Kuli.mahou</>를 1장, 이 카드에 인접한 슬롯에 배치한다 (대각선 슬롯 제외)",
    "e_mahou_starwish": "자신의 덱에서 카드를 1장 트래쉬로 보내고, 셔플한다",
    "e_mahou_hearttrial_init": "자신의 필드 위의 카드를 1장 선택한다. 자신의 패에 선택한 카드의 카피를 <key>{0}</>장 창조한다. 카피는 스테이터스가 <attack>0</>|<health>1</>이 되고, 모든 효과가 제거된다",
    "e_mahou_hearttrial_field": "카드가 필드 위에서 나왔을 때, 그 카드와 같은 이름의 다른 모든 카드를 <decompile>디컴파일</>한다",
    "e_mahou_starwish_active": "자신의 트래쉬에 있는 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mahou</> 카드를 선택한다(<key>Wish.mahou</> 제외). 이 카드를 <decompile>디컴파일</>하고, 이 카드가 있던 위치에 선택한 카드를 꺼낸다",
    "e_mahou_girl_shared_tagout": "자신의 덱 안에서 이름이 다르고 레벨이 이 카드 이하인 <key>.mahou</> 카드를 1장 선택한다. 이 카드를 덱으로 보내고 셔플한 후, 이 카드가 있던 위치에 선택한 카드를 꺼내고 비활성화한다",
    "e_vault_slash": "앞쪽에 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다. 자신의 <key>턴 드로우</>가 <key>0</>인 경우, 곧바로 <key>턴 드로우</>를 하고, 패에 <key>Combo</> 카드를 1장 창조한다",
    "e_vault_combo": "이 카드가 자신의 <key>패</> 또는 <key>필드</>에 있고, <attack>공격력</>이 <attack>1</> 이상 있는 <key>.vault</> 카드가 <img id=\"\"effect_init\"\"/> 효과를 발동한 경우, 그 효과를(발동 후에) 재발동하고, 이 카드를 <void>보이드</>한다 (다른 <key>Combo</> 카드에 의해 발동한 효과는 무시된다)",
    "e_vault_sharedredraw": "패에서만 발동할 수 있다. 이 카드를 버리고 자신의 <key>턴 드로우 카운터</>를 <key>1</> 줄인다. 또, 이 카드가 패의 마지막 카드였을 경우, 카드를 <key>{0}</>장 드로우한다",
    "e_vault_jab": "앞쪽에 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 대미지를 준다. 대미지를 주는 것에 성공한 경우, 카드를 1장 드로우한다",
    "e_vault_blade": "자신의 패에 있는 <key>Combo</> 카드의 수 <key>+1</>회만큼 앞쪽의 카드 1장에게 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다 (현재 대미지 <physical>{0}</> <key>x{1}</>)",
    "e_vault_apprentice": "패에 <key>HiddenBlade.vault</> 카드를 <uadd>[</><key>{0}</><uadd>]</>장 창조하고, 패에 <key>Combo</> 카드를 1장 창조한다",
    "e_vault_multiblade": "앞쪽에 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 대미지를 준다. 대미지를 주는 것에 성공한 경우, 패에 <key>HiddenBlade.vault</> 카드를 1장 창조한다",
    "e_vault_bide": "패에 <key>Combo</> 카드를 <key>{0}</>장 창조한다",
    "e_vault_agility": "패에 <key>Combo</> 카드를 1장 창조한다",
    "e_vault_char_edit": "이 카드가 필드에서 제거된 경우, 이 카드의 감소한 체력과 같은 <img id=\"\"player_health\"\"/> 대미지를 받은 후, 덱을 <key>편집</>하고 <key>리로드</>한다 (현재 <img id=\"\"player_health\"\"/> 대미지 : <key>{0}</>)",
    "e_vault_char_ping": "적의 카드 1장을 <key>{0}</>턴 지연한다. <key>HiddenBlade.vault</> 카드와 <key>Combo</> 카드를 각각 1장씩 패에 창조한다. 이 효과는 트래쉬 안에서도 발동할 수 있고, 그 경우에는 추가로 이 카드를 덱에 추가하고 셔플한다",
    "e_vault_juggle": "패의 카드를 <key>1</>장 버린다. 카드를 <uadd>[</><key>{0}</><uadd>]</>장 뽑고, 패에 <key>HiddenBlade.vault</>를 1장 창조한다",
    "e_vault_oncemore": "자신의 필드에 있는 <img id=\"\"effect_init\"\"/> 효과를 가진 레벨 <key>1</> 카드를 1장 선택한다. 선택한 카드의 앞쪽에 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 주고 가장 왼쪽 끝에 있는 <img id=\"\"effect_init\"\"/> 효과를 발동한다. 이렇게 발동한 효과는 그 카피를 다시 발동하지 않는다",
    "e_vault_opportunist": "모든 적에게 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다. 적의 카운터가 <key>0</>인 경우, 그 대신에 <physical>{1}</><img id=\"\"dmg_phys\"\"/> 대미지를 준다",
    "e_vault_lightup": "앞쪽에 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 대미지를 준다. 대미지를 주는 것에 성공한 경우, 자신의 <key>턴 드로우 카운터</>를 <key>1</> 줄인다",
    "e_vault_parry": "자신의 필드에 있는 모든 카드를 <uadd>[</><health>{0}</><uadd>]</> 회복한다",
    "e_vault_condition": "자신의 필드 위에 있는 카드를 <key>{0}</>장 <decompile>디컴파일</>한다",
    "e_vault_condition_1_upgrade": "자신의 필드 위에 있는 카드를 <uadd>[</><key>{0}</><uadd>]</>장 <decompile>디컴파일</>한다",
    "e_nova_assault": "이 카드와 인접한 칸에, 자신의 덱에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mod</> 카드를 놓는다.(대각선은 제외)",
    "e_nova_sentinel": "이 카드와 인접한 칸에, 당신의 트래쉬에서 레벨 <uadd>[</><key>{0}</><uadd>]</> 이하의 <key>.mod</> 카드를 놓는다. (대각선은 제외)",
    "e_nova_sentinelblock": "이 카드가 받는 피해를 <key>0</>으로 줄이고, 이 효과를 제거한다.",
    "e_nova_research": "이 카드와 인접한 모든 카드를 <decompile>디컴파일</>한다.(대각선은 제외) 그 후, <decompile>디컴파일</>된 카드의 수에 따라 다음 효과를 순서대로 발동한다:{b}{b}[1+]: <uadd>[</><key>{0}</><uadd>]</>장의 카드를 뽑습니다. {b}[2+]: 모든 적의 카드를 <uadd>[</><key>{1}</><uadd>]</>턴 지연시킨다. {b}[3+]: 트래쉬를 덱에 넣고 섞은 후, <key>{2}</>장의 카드를 뽑는다.",
    "e_nova_researchmanual": "자신의 패에서 <key>.mod</> 카드 하나를 선택한다. 그 카드를 덱으로 섞은 후, <key>{0}</>장의 카드를 뽑는다.",
    "e_nova_architectinit": "원하는 만큼 자신의 패에서 레벨 <key>2</> 이하의 <key>.mod</> 카드를 필드에 놓는다.",
    "e_nova_architectfetch": "자신의 덱에서 레벨 <key>1</>의 <key>.nova</> 카드를 필드에 놓는다. 그 카드의 체력을 <uadd>[</><health>+{0}</><uadd>]</> 상승시킨다.",
    "e_nova_architectcondition": "자신의 필드에는 <key>.nova</> 카드가 없어야 한다.",
    "e_nova_leviathansummon": "트래쉬에서 <key>{0}</> 장의 무작위 <key>.nova</> 카드를 패로 가져온다. (카드가 {0}장보다 적을 경우 가능한만큼 가져온다).",
    "e_nova_leviathancondition": "자신의 필드에는 카드가 없어야 하며, 트래쉬에는 서로 다른 이름을 가진 <key>.mod</> 카드가 <key>{0}</>장 이상 있어야 한다. (현재 {1}/{0})",
    "e_nova_leviathanmanual": "트래쉬에서 <key>{0}</> 장의 무작위 <key>.nova</> 카드를 패로 가져온다. (카드가 {0}장보다 적을 경우 가능한만큼 가져온다). 그 후, 이 카드에 걸린 모든 효과를 제거한다.",
    "e_nova_carrierspawn": "인접한 칸에 (대각선은 제외) 미니언 카드를 소환한다.",
    "e_nova_carrierattack": "인접한 카드들로 공격한다.(대각선은 제외)",
    "e_nova_carriercondition": "<key>3</>개의 효과가 있는 필드의 <key>.nova</> 카드를 패로 되돌립니다. (<key>Carrier.nova</>는 제외)",
    "e_nova_sharedbuffing": "인접한 모든 <key>.nova</> 카드들을 재활성화하고 (대각선은 제외), 이 카드의 다른 모든 효과를 해당 카드들에게 부여한다.",
    "e_nova_fusillade": "이 카드가 <physical>공격</>한다면, 공격 대상과 같은 가로열에 있는 모든 다른 카드에게 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 피해를 준다.",
    "e_nova_highexplosive": "이 카드가 <img id=\"\"dmg_phys\"\"/><physical>대미지</>를 입힌다면, 대상과 인접한 모든 적 카드들에게 (대각선은 제외) <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</>의 피해를 준다. 공격한 대상이 파괴되었다면, 대신 <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</>의 피해를 준다.",
    "e_nova_heavycaliber": "이 카드의 공격은 <uadd>[</><physical>+{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 추가 피해를 준다. 이 카드가 공격한 후에 뒤로 이동한다. 만약 이동 경로에 카드가 있었다면, 대신 이 카드를 패로 되돌린다.",
    "e_nova_taclink": "이 카드의 인접한 다른 카드 (대각선은 제외)를 놓을 때, 이 카드와 놓은 카드 양쪽의 <health>체력</>을 <uadd>[</><health>+{0}</><uadd>]</> 만큼 상승시킨다. (최대 <health>+{0}</> 최대 체력).",
    "e_nova_barrier": "이 카드의 체력이 <health>1</> 이상인 동안 피해를 입었을 때, 적어도 <health>1</>의 체력이 남도록 생존한다.",
    "e_nova_strike": "이 카드가 공격할 때, 이 카드의 효과마다 <uadd>[</><key>{0}</><uadd>]</>의 추가 피해를 부여한다 (현재 <key>+{1}</> 전투력). 이 카드가 공격한 후에, 이 카드의 모든 효과를 제거한다.",
    "e_nova_lance": "이 카드가 이동할 때, 이 카드의 체력이 <health>1</> 이상이라면, <magic>1</><img id=\"\"dmg_magic\"\"/>의 피해를 입은 후 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</>의 피해를 가하는 공격을 수행한다.",
    "e_nova_ataraxia": "이 카드는 패에 있는 <key>.mod</> 카드의 수에 따라 효과를 획득한다 (현재: {count}):",
    "e_nova_ataraxia1": "{b}[{first}+]: 공격 시, 턴 드로우 카운트를 <uadd>[</><key>{turndraw}</><uadd>]</>만큼 감소시킨다.",
    "e_nova_ataraxia2": "{b}[{second}+]: 이 카드가 공격한 적을 <uadd>[</><key>{delay}</><uadd>]</>만큼 지연시킵니다.",
    "e_nova_ataraxia3": "{b}[{third}+]: 모든 피해량을 <uadd>[</><key>+{superDmg}</><uadd>]</>만큼 증가시킨다.",
    "e_dmg_reduction": "받는 모든 대미지를 <key>{0}</> 감소한다",
    "e_deathcrave": "이 카드가 전투에서 카드를 파괴한 경우, 재활성화 한다",
    "e_undamagable": "이 카드는 대미지를 받지 않는다",
    "e_dmgcap": "이 카드는 한 번에 <key>{0}</> 초과의 대미지를 받지 않는다",
    "e_undamagable_physical": "이 카드는 <physical>물리 대미지</>를 받지 않는다",
    "e_dmgcap_physical": "이 카드는 한 번에 <physical>{0}</><img id=\"\"dmg_phys\"\"/> 초과의 물리 대미지를 받지 않는다",
    "e_undamagable_magic": "이 카드는 <magic>마법 대미지</>를 받지 않는다",
    "e_dmgcap_magic": "이 카드는 한 번에 <magic>{0}</><img id=“dmg_magic\"\"/> 초과의 마법 대미지를 받지 않는다",
    "e_destroy_self": "이 카드를 파괴한다",
    "e_decompile_self": "이 카드를 <decompile>디컴파일</>한다",
    "e_void_self": "이 카드를 <void>보이드</>한다",
    "e_attack": "{0}번 공격한다",
    "e_quick": "이 카드를 꺼냈을 때, 턴을 소비하지 않는다",
    "e_revenge": "이 카드가 대미지를 받으면 공격한다",
    "e_reflect": "이 카드가 대미지를 받으면, 받은 대미지와 같은 공격력으로 공격한다",
    "e_use_potion": "이 카드는 한 번 사용하면 소멸한다",
    "e_volatile": "필드에서 제외당했을 때, 이 카드를 <void>보이드</>한다",
    "e_grave_to_hand": "이 카드가 자신의 트래쉬에 있는 경우, 패에 추가한다.",
    "e_t_ignition": "매뉴얼",
    "e_t_desc_ignition": "클릭해서 발동한다. 발동 후, 이 카드는 비활성화 된다",
    "e_t_trigger": "트리거",
    "e_t_desc_trigger": "특정 이벤트가 발생했을 때, 자동으로 발동한다. 턴을 소비하지 않는다",
    "e_t_init": "초기화",
    "e_t_desc_init": "이 카드가 필드에 나왔을 때, 발동한다",
    "e_t_condition": "컨디션",
    "e_t_desc_condition": "이 카드를 수동으로 패에서 꺼내기 위해서는 조건을 만족시켜야 한다",
    "e_t_exec": "실행",
    "e_t_desc_exec": "이 카드가 실행되었을 때, 발동한다",
    "e_t_passive": "패시브",
    "e_t_desc_passive": "이 카드의 활성화 여부와 상관없이 자동으로 발동한다",
    "e_t_destruction": "파괴",
    "e_t_desc_destruction": "이 카드가 파괴되었을 때, 발동한다 (디컴파일이나 실행은 파괴로 간주하지 않는다)",
    "e_t_volatile": "휘발",
    "e_t_desc_volatile": "이 카드가 필드에서 벗어날 때, 소멸한다",
    "e_t_defense": "방어",
    "e_t_desc_defense": "이 카드는 한 번에 일정 이상의 대미지를 받지 않는다",
    "e_t_quick": "퀵",
    "e_t_desc_quick": "이 카드는 필드에 나올 때, 턴을 소비하지 않는다",
    "e_t_dragoon": "드라군 링크",
    "e_t_desc_dragoon": "동일한 드라군에게서 만들어진 프로그램은 모두 링크되어 있다",
    "e_t_single": "소모품",
    "e_t_desc_single": "이 효과를 발동한 후, 그 게임과 덱에서 소멸된다",
    "e_t_artifact": "프리로드",
    "e_t_desc_artifact": "이 카드가 패에 있는 상태로 게임이 시작된다",
    "e_t_storage": "캐쉬",
    "e_t_desc_storage": "이 효과는 이 카드가 스토리지에 있을 경우에 적용된다",
    "key_once": "일회용",
    "key_desc_once": "이 효과는 1회만 발동할 수 있다",
    "key_instant": "순간발동",
    "key_desc_instant": "이 효과를 발동할 때, 턴을 소비하지 않는다",
    "key_unique": "유니크",
    "key_desc_unique": "이 효과는 1턴에 1번만 발동할 수 있다",
    "key_global": "하드 유니크",
    "key_desc_global": "이 효과는 다른 카드의 같은 효과와 합쳐서 1턴에 1번만 발동할 수 있다.",
    "key_bonded": "결합",
    "key_desc_bonded": "이 효과는 제거되지 않는다",
    "key_exclusive": "배척",
    "key_desc_exclusive": "이 카드가 같은 턴 중에 다른 특수효과를 발동한 경우, 이 효과는 발동할 수 없다",
    "key_chained": "연쇄",
    "key_desc_chained": "이 효과는 트리거가 된 이벤트에 이어서 발동한다",
    "h_effectkeyword_void": "<void>보이드</> - 덱이 리로드 되었을 때, 이 카드를 게임에서 제거하고 사용할 수 없게 된다",
    "h_effectkeyword_suspend": "<key>서스펜드</> - 대상을 지연시키지만, 추가적인 지연의 내성은 부여하지 않는다",
    "h_effectkeyword_decompile": "<decompile>디컴파일</> - 카드를 파괴하지 않고 트래쉬로 보낸다. 대상은 드랍하지 않는다",
    "h_effectkeyword_exposed": "<expose>언커버</> - 이 카드의 앞에 아군 카드가 없는 상태",
    "h_effectkeyword_covered": "<cover>커버</> - 이 카드의 앞에 아군 카드가 있는 상태",
    "h_effectkeyword_automate": "<key>자동화</> - 카드가 자동으로 움직인다",
    "h_effectkeyword_decaybuff": "<specialbuff>감소 버프</> - 매 턴 종료 시에 버프가 감소한다",
    "h_effectkeyword_singlebuff": "<specialbuff>단발 버프</> - 공격하면 버프가 해제된다",
    "h_effectkeyword_aligned": "<align>직선상</> - 이 카드와 같은 세로열에 놓여 있는 상태",
    "h_effectkeyword_pathed": "<pathed>연결</> - 두 개의 자신의 카드 사이에 연속적으로 연결된 상태(대각선은 제외).",
    "h_activate": "<green>[클릭 시 발동]</>",
    "h_noactivate": "<yellow>[발동 불가능]</>",
    "h_notactiveturn": "<red>[카드 비활성화]</>",
    "h_usedonce": "<red>[</> <img id=\"\"effect_once\"\"></><red>사용 완료]</>",
    "h_disabled": "<red>[무효]</>",
    "h_conditionnotmet": "<red>[조건 불충족]</>",
    "h_novalidtargets": "<yellow>[대상 없음]</>",
    "h_notlocation": "<red>[이 장소에서 발동 불가능]</>",
    "h_nocounters": "<red>[카운터 부족]</>",
    "h_toomanycounters": "<red>[카운터 초과]</>",
    "h_noattackpower": "<red>[공격력 없음]</>",
    "h_noslots": "<red>[필드 슬롯 없음]</>",
    "h_maxreached": "<yellow>[최대 수 도달]</>",
    "h_upgradeblocker_healthzero": "체력 부족",
    "c_abilityaurora": "Serenity",
    "c_abilitydragoon": "Imagination",
    "c_abilityesper": "WorldSeed",
    "c_abilityidol": "Encore",
    "c_abilityleo": "Mountain",
    "c_abilityomega": "Paradox",
    "c_abilityqueen": "Checkmate",
    "c_artifactgreed": "Greed.algo",
    "c_artifactmemory": "Memory.algo",
    "c_artifactmomentum": "Momentum.algo",
    "c_artifactspire": "Spire.algo",
    "c_chessbishop": "Bishop",
    "c_chessking": "King",
    "c_chessknight": "Knight",
    "c_chesspawn": "Pawn",
    "c_chessqueen": "Queen",
    "c_chessrook": "Rook",
    "c_consumablepotionhealth": "HealthPotion",
    "c_consumablepotionstorage": "StoragePotion",
    "c_consumablepotionvoid": "VoidPotion",
    "c_debugknife": "Knife.debug",
    "c_dragoonflame": "DragoonFlame",
    "c_fantasyarae": "Arae.myth",
    "c_fantasycockatrice": "Cockatrice.myth",
    "c_fantasygolem": "Golem.myth",
    "c_fantasygriffin": "Griffin.myth",
    "c_fantasymermaid": "Mermaid.myth",
    "c_fantasyphoenix": "Phoenix.myth",
    "c_fantasyunicorn": "Unicorn.myth",
    "c_genericafterburner": "Afterburner",
    "c_genericavarice": "Avarice",
    "c_genericbattery": "Battery",
    "c_genericbeartrap": "ClawTrap",
    "c_genericcapacitor": "DamageCapacitor",
    "c_genericcinder": "Cinder",
    "c_genericconstantcorrection": "ConstantCorrection",
    "c_genericcrystalball": "CrystalBall",
    "c_genericdoubleexecute": "DoubleExecute",
    "c_genericember": "Ember",
    "c_genericfireball": "Fireball",
    "c_genericflashattack": "Flash",
    "c_genericflashbang": "Flashbang",
    "c_genericforce": "Force",
    "c_genericinferno": "Inferno",
    "c_genericmagicember": "MagicEmber",
    "c_genericmagicflare": "MagicFlare",
    "c_genericmegarush": "RushMega",
    "c_genericomen": "Omen",
    "c_genericpendulum": "Pendulum",
    "c_genericpureheart": "PureHeart",
    "c_genericreincarnation": "Reincarnation",
    "c_genericscalpel": "Scalpel",
    "c_genericshatter": "Shatter",
    "c_genericspark": "Spark",
    "c_genericthunderclap": "Thunderclap",
    "c_generictreasure": "Treasure",
    "c_mdvaxe": "Axe.mech",
    "c_mdvcore": "Core.mech",
    "c_mdvgatling": "Gatling.mech",
    "c_mdvhammer": "Hammer.mech",
    "c_mdvhydro": "Hydro.mech",
    "c_mdvplasma": "Plasma.mech",
    "c_mdvpod": "DropPod",
    "c_mdvrocket": "RocketBarrage",
    "c_mdvspear": "Spear.mech",
    "c_mdvsword": "Sword.mech",
    "c_mdvthunder": "Thunder.mech",
    "c_mdvtower": "CommandTower",
    "c_mdvunity": "Unity",
    "c_musicbass": "Bass.muse",
    "c_musicdoubleeighth": "DoubleEighth.muse",
    "c_musicequalize": "Equalize.muse",
    "c_musicfermata": "Fermata.muse",
    "c_musicforte": "Forte.muse",
    "c_musicidol1": "Airi.muse",
    "c_musicidol2": "Miki.muse",
    "c_musicidol3": "Yuki.muse",
    "c_musicidol4": "Kano.muse",
    "c_musicidol5": "Erika.muse",
    "c_musicidolboss": "Remi.muse",
    "c_musicpiano": "Piano.muse",
    "c_musicquarter": "Quarter.muse",
    "c_musicquarterrest": "QuarterRest.muse",
    "c_musictreble": "Treble.muse",
    "c_musictriplet": "Triplet.muse",
    "c_naturalapple": "Apple.fruit",
    "c_naturalbanana": "Banana.fruit",
    "c_naturalcherry": "Cherry.fruit",
    "c_naturaldemeter": "Demeter.fruit",
    "c_naturalfall": "Autumn.fruit",
    "c_naturalgreenhouse": "Greenhouse",
    "c_naturalgrowth": "Growth",
    "c_naturallemon": "Lemon.fruit",
    "c_naturalpersephone": "Persephone.fruit",
    "c_naturalpollination": "Pollination",
    "c_naturalpomegranate": "Pomegranate.fruit",
    "c_naturalpumpkin": "Pumpkin.fruit",
    "c_naturalspring": "Spring.fruit",
    "c_naturalsummer": "Summer.fruit",
    "c_naturalwinter": "Winter.fruit",
    "c_sakurabow": "Bow.hana",
    "c_sakurakatana": "Katana.hana",
    "c_sakurakunai": "Kunai.hana",
    "c_sakuralantern": "Lantern.hana",
    "c_sakuraninja1": "Saya.hana",
    "c_sakuraninja2": "Ishida.hana",
    "c_sakuraninja3": "Mira.hana",
    "c_sakuraninja4": "Saigo.hana",
    "c_sakuraninjaboss": "MasterKobo.hana",
    "c_sakurapriestess": "Chiyo.hana",
    "c_sakurashide": "Shide.hana",
    "c_sakurastorm": "Bloom.hana",
    "c_sakuratorii": "Torii.hana",
    "c_spdeckedit": "Reprogram",
    "c_spdeckreload": "Rejuvenate",
    "c_spinitialize": "Initialize",
    "c_spinstantdraft": "Compile",
    "c_spiritamaterasu": "Amaterasu.spirit",
    "c_spiritkitsune": "Kitsune.spirit",
    "c_spiritkusanagi": "Kusanagi.spirit",
    "c_spiritmagatama": "Yasakani.spirit",
    "c_spiritneko": "Neko.spirit",
    "c_spiritnezumi": "Nezumi.spirit",
    "c_spiritsika": "Sika.spirit",
    "c_spirittanzaku": "Tanzaku.spirit",
    "c_spirittsukuyomi": "Tsukuyomi.spirit",
    "c_spirittsuru": "Tsuru.spirit",
    "c_spiritwatatsumi": "Watatsumi.spirit",
    "c_spirityamata": "Yamata.spirit",
    "c_spirityata": "Yata.spirit",
    "c_spstoragehit": "CacheHit",
    "c_tutorialfireball": "Fireball",
    "c_vampgen1": "Lorado.legion",
    "c_vampgen2_minion": "Clone.legion",
    "c_vampgen2": "Syka.legion",
    "c_vamphyper": "Hyper.blood",
    "c_vamplieu1": "Yiko.legion",
    "c_vamplieu2": "Misera.legion",
    "c_vamporb": "Orb.blood",
    "c_vamporigin": "Origin.blood",
    "c_vampplunge": "Plunge.blood",
    "c_vamprevival": "Revival.blood",
    "c_vampshield": "Shield.blood",
    "c_vampsol1": "Li.legion",
    "c_vampsol2": "Ora.legion",
    "c_vampsol3": "Xelia.legion",
    "c_vampspear": "Spear.blood",
    "c_vampsword": "Sword.blood",
    "c_magesorcignis": "Ignis.sorc",
    "c_magesorceffingo": "Effingo.sorc",
    "c_magesorccreo": "Creo.sorc",
    "c_magesorcgravitas": "Gravitas.sorc",
    "c_magesorcpotentia": "Potentia.sorc",
    "c_magesorctempus": "Tempus.sorc",
    "c_magesorclux": "Lux.sorc",
    "c_magelucia": "Lucia.mage",
    "c_mageaurelia": "Aurelia.mage",
    "c_magecamilla": "Camilla.mage",
    "c_magemariana": "Mariana.mage",
    "c_mageoctavia": "Octavia.mage",
    "c_magevaleria": "Valeria.mage",
    "c_magedecima": "Decima.mage",
    "c_genericupdraft": "Updraft",
    "c_generictaser": "Taser",
    "c_genericambush": "Ambush",
    "c_genericrupture": "Rupture",
    "c_edensaffron": "Saffron.eden",
    "c_edenthunder": "Thunder.edx",
    "c_edengunner": "Gunner.eden",
    "c_edenreva": "Reva.eden",
    "c_edenhazel": "Hazel.eden",
    "c_edenselicy": "Selicy.eden",
    "c_edenshiso": "Shiso.eden",
    "c_edenterra": "Terra.eden",
    "c_edenviolette": "Violette.eden",
    "c_edenstepslash": "StepSlash.edx",
    "c_edenbowsnipe": "BowSnipe.edx",
    "c_edencrossfire": "Crossfire.edx",
    "c_edenwave": "KineticWave.edx",
    "c_edenragnarok": "Ragnarok.edx",
    "c_edenshopkeeper": "Shopkeeper.eden",
    "c_crosseleheat": "Heat.element",
    "c_crosselecold": "Cold.element",
    "c_crosseleshock": "Shock.element",
    "c_crosselewave": "Wave.element",
    "c_crosslea": "Lea.cross",
    "c_crossemilienator": "Emilienator.cross",
    "c_crossctron": "C'tron.cross",
    "c_crosslukas": "Schneider.cross",
    "c_crossapollo": "Apollo.cross",
    "c_crossjoern": "Joern.cross",
    "c_crosshlin": "Hlin.cross",
    "c_crossbuggy": "Buggy.cross",
    "c_crossalbert": "Beowulf.cross",
    "c_crossshizuka": "Shizuka.cross",
    "c_mahoubunnyfire": "Kufi.mahou",
    "c_mahougirlfire": "Akane.mahou",
    "c_mahoubunnyearth": "Kuea.mahou",
    "c_mahougirlearth": "Chie.mahou",
    "c_mahoubunnywind": "Kuwi.mahou",
    "c_mahougirlwind": "Kazane.mahou",
    "c_mahoubunnywater": "Kuwa.mahou",
    "c_mahougirlwater": "Aoi.mahou",
    "c_mahoubunnydark": "Kuda.mahou",
    "c_mahougirldark": "Tsukiyo.mahou",
    "c_mahoubunnylight": "Kuli.mahou",
    "c_mahougirllight": "Hoshiko.mahou",
    "c_mahouwish": "Wish.mahou",
    "c_mahouhearttrial": "TrialOfHeart",
    "c_vaultcombo": "Combo",
    "c_vaultslash": "Slash.vault",
    "c_vaultblade": "HiddenBlade.vault",
    "c_vaultjab": "Jab.vault",
    "c_vaultapprentice": "Apprentice.vault",
    "c_vaultmultiblade": "BladeOnBlades.vault",
    "c_vaultbide": "Bide.vault",
    "c_vaultjuggle": "Juggle.vault",
    "c_vaultchar": "TheHidden.vault",
    "c_vaultoncemore": "OnceMore.vault",
    "c_vaultagility": "Agility.vault",
    "c_vaultlightup": "LightItUp.vault",
    "c_vaultopportunist": "Opportunist.vault",
    "c_vaultparry": "Parry.vault",
    "c_novastandard": "Protean.nova",
    "c_novaassault": "Assault.nova",
    "c_novasentinel": "Sentinel.nova",
    "c_novaresearch": "Research.nova",
    "c_novacarrier": "Carrier.nova",
    "c_novacarrier_minion": "Swarm.nova",
    "c_novaarchitect": "Architect.nova",
    "c_novaleviathan": "Leviathan.nova",
    "c_novaburstfire": "BurstFire.mod",
    "c_novafusillade": "Fusillade.mod",
    "c_novahighexplosive": "HighExplosive.mod",
    "c_novaheavycaliber": "HeavyCaliber.mod",
    "c_novaconvergence": "Convergence.mod",
    "c_novataclink": "TacticalLink.mod",
    "c_novabarrier": "Barrier.mod",
    "c_novastrike": "SingularStrike.mod",
    "c_novalance": "CelestialLance.mod",
    "c_novaataraxia": "Ataraxia.mod",
    "c_boss1minion": "ZyriteFragment.z",
    "c_boss2": "Zlime.z",
    "c_boss2minion": "Zlob.z",
    "c_boss3": "Zarakuri.z",
    "c_boss3virus": "Purple.virus",
    "c_boss4": "Zeaper.z",
    "c_boss4scythe": "Zcythe.z",
    "c_boss4dagger": "Zagger.z",
    "c_boss4soul": "Soul",
    "c_boss5": "Zirus.z",
    "c_boss5attackminion": "Zpike.z",
    "c_boss5bombminion": "Zingularity.z",
    "c_boss5left": "ZeftArm.z",
    "c_boss5right": "ZightArm.z",
    "c_bossb1": "Demeter.dark",
    "c_bossb1minion": "BlackThorns",
    "c_bossb2": "Remi.dark",
    "c_bossb2minion": "Note",
    "c_bossb3": "MasterKobo.dark",
    "c_bossb3minion1": "Katana.dark",
    "c_bossb3minion2": "Bow.dark",
    "c_bossb3minion3": "Kunai.dark",
    "c_bossb3minion4": "Lantern.dark",
    "c_bossb4": "Plasma.dark",
    "c_bossb4minion": "Energy.dark",
    "c_bossb5": "Persephone.dark",
    "c_bossb5minion": "Thorn",
    "c_bossb6": "Griffin.dark",
    "c_bossb6extra": "Treasure.dark",
    "c_bossb6minion": "Curse",
    "c_bossb7": "Lorado.dark",
    "c_bossb7minion1": "Soldier",
    "c_bossb7minion2": "Soldier",
    "c_bossb7minion3": "Soldier",
    "c_bossb8": "Amaterasu.dark",
    "c_bossb8minion": "SpiritEmber",
    "c_bossb9": "Tsukuyomi.dark",
    "c_bossb9minion": "Moonlight",
    "c_bossb10": "Decima.dark",
    "c_bossb10minion1": "Ignis.dark",
    "c_bossb10minion2": "Gravitas.dark",
    "c_bossb10minion3": "Creo.dark",
    "c_bossb10minionspawn": "DarkPower",
    "c_bossmahou": "TrialsOfHeart.x",
    "c_bosscomet1": "Zira.z",
    "c_bosscomet1minion": "Afterimage",
    "c_bosscomet2": "Zira.z",
    "c_bosscomet3": "Zira.z",
    "c_bosscomet3minion": "ShadowSabre",
    "c_bosscomet3minion2": "Corruption",
    "c_bosscometdefeat": "Zira.z",
    "c_bosswaystone": "CorruptedBit",
    "c_cometruinsanctum": "Sanctum?",
    "c_cometsanctum1": "Sanctum",
    "c_cometsanctum2": "Sanctum",
    "c_depthssanctum": "Sanctum",
    "c_dungeonbug": "Bug.mw",
    "c_enemyartillery": "Artillery.sc",
    "c_enemyblackvirus": "Black.virus",
    "c_enemybosscandle": "Zandle.z",
    "c_enemybug": "Bug.mw",
    "c_enemycache": "CryptCache",
    "c_enemycachedrafting": "SourceCache",
    "c_enemycacherandom": "BitCache",
    "c_enemychandelier": "Chandelier.mw",
    "c_enemycollapse": "Guillotine.ex",
    "c_enemydaggers": "Daggers.ex",
    "c_enemydisruptor": "Disruptor.sc",
    "c_enemyghostblue": "Blue.ghst",
    "c_enemyghostred": "Red.ghst",
    "c_enemyguardian": "Guardian.sc",
    "c_enemyinterceptor": "Interceptor.sc",
    "c_enemymiasma": "Miasma.ex",
    "c_enemymine": "Mine.sc",
    "c_enemymirrorshard": "MirrorShard.mw",
    "c_enemyobserver": "Observer.sc",
    "c_enemypassivebug": "Bug.mw",
    "c_enemypathogen": "Pathogen.mw",
    "c_enemypredator": "Predator.sc",
    "c_enemyrail": "RailGun.sc",
    "c_enemysentry": "Sentry.sc",
    "c_enemysentry2": "Sentry2.sc",
    "c_enemysignal": "Trance.ex",
    "c_enemystagetarget": "StageMark",
    "c_enemystealertutorial": "???",
    "c_enemystrongbug": "StrongBug.mw",
    "c_enemystrongwall": "Firewall.scx",
    "c_enemytalismanblack": "Black.tlsm",
    "c_enemytalismanwhite": "White.tlsm",
    "c_enemyvenom": "Venom.mw",
    "c_enemyvirusblue": "Blue.virus",
    "c_enemyvirusred": "Red.virus",
    "c_enemyweaktarget": "Target",
    "c_enemyweakwall": "Firewall.sc",
    "c_enemywormblue": "Blue.wrm",
    "c_enemywormred": "Red.wrm",
    "c_enemyzombie": "Zombie.mw",
    "c_miniboss1": "Curse.x",
    "c_omegaboss": "Zira.z",
    "c_omegabossunstable": "Zira.z",
    "c_omegacore": "VoidSpike.z",
    "c_potionhealth": "Health.potion",
    "c_potionstorage": "Storage.potion",
    "c_syncmarker1": "SyncMarker",
    "c_syncmarker2": "SyncMarker",
    "c_syncmarker4": "SyncMarker",
    "c_timebomb2": "TimeBomb",
    "c_timebomb3": "TimeBomb",
    "c_timebomb4": "TimeBomb",
    "c_timebomb7": "TimeBomb",
    "c_timebomb_h5_t6": "TimeBomb",
    "c_timebomb_h5_t5": "TimeBomb",
    "c_timebomb_h5_t4": "TimeBomb",
    "c_puzzleblank": "Blank",
    "c_storyvolatilecircuit_t2": "UnstableCircuit",
    "c_storyvolatilecircuit_t3": "UnstableCircuit",
    "c_storyvolatilecircuit_t4": "UnstableCircuit",
    "c_storyvolatilecircuit_t5": "UnstableCircuit",
    "c_storyvolatilecircuit_t6": "UnstableCircuit",
    "c_storyvolatilecircuit_t7": "UnstableCircuit",
    "c_storyvolatilecircuit_t8": "UnstableCircuit",
    "c_storyexplosivecircuit_t4": "ExplosiveCircuit",
    "c_storyfragilecircuit_t6": "FragileCircuit",
    "c_volatilecircuit_h4_t8": "UnstableCircuit",
    "c_volatilecircuit_h5_t4": "UnstableCircuit",
    "c_volatilecircuit_h5_t6": "UnstableCircuit",
    "c_volatilecircuit_h5_t7": "UnstableCircuit",
    "c_volatilecircuit_h5_t8": "UnstableCircuit",
    "c_volatilecircuit_h6_t8": "UnstableCircuit",
    "c_infinitereload": "Navigation",
    "c_infiniteinstantdraft": "HyperCompiler",
    "c_quantumknifetutorial": "Knife.hck",
    "c_quantumsigil": "Quantum",
    "c_enemysentrynoattack": "Sentry.sc",
    "c_stagemarker": "StageMarker",
    "c_securitylock": "Security.x",
    "c_objectivedata1": "Data.txt",
    "c_openingdungeonmark": "ACTIVE",
    "c_puzzledummy": "Dummy",
    "c_lootdummy": "ItemCage",
    "c_puzzleironwall": "IronWall",
    "c_puzzleironwall2": "TemperedWall",
    "c_auroraantisentry": "Sentry2+.sc",
    "c_queenlock": "QueensLock",
    "c_queenlockcore": "Lock",
    "c_machineblock": "BitBlock",
    "c_machineblock2": "BitBlock",
    "c_machinegear": "Contraption",
    "c_machinecoin": "Coin",
    "c_brainthorn": "ThornBubble",
    "c_brainheart": "BrokenHeart.z",
    "c_brainqueen": "Queen",
    "c_endgamelockgeneral": "Red.lock",
    "c_endgamelock1": "RedBit",
    "c_endgamelock2": "RedBit",
    "c_endgamelock3": "RedBit",
    "c_endgamelock4": "RedBit",
    "c_endgamelock5": "RedBit",
    "c_storyoxygen": "Oxygen",
    "c_storyhydrogen": "Hydrogen",
    "c_storybackdoor": "Backdoor",
    "c_flowerhologram": "Hologram",
    "c_haloshield": "Protection"
}as Record<string, string>