export default{
    "d_queenintro": "女王部下",
    "d_esperintro": "自然一体",
    "d_auroraintro": "樱花散漫",
    "d_leointro": "机甲暴动",
    "d_idolintro": "登场时分",
    "d_esperpuzzle1": "解谜工具箱",
    "d_aurorareprogram": "解谜工具箱",
    "d_aurorastarter1": "樱花 MKI",
    "d_idolstarter1": "登场时分",
    "d_esperstarter1": "自然一体",
    "d_queenchess": "CHECKMATE",
    "d_esperdungeon1": "自然一体",
    "d_esperdungeon2": "白驹过隙",
    "d_esperdungeon3": "宏伟秘仪",
    "d_auroradungeon1": "樱花散漫",
    "d_auroradungeonspirit": "灵兽呼唤",
    "d_idoldungeon1": "舞台中央",
    "d_idoldungeonmahou": "心之试炼",
    "d_leodungeon1": "机甲暴动",
    "d_dragoondungeon1": "时过境迁",
    "d_dragoondungeon2": "同心协力",
    "d_dragoondungeoninf": "无限求知",
    "d_omegadungeon1": "军团总部",
    "d_collabeden": "伊甸边境",
    "d_collabcross": "远星旅人",
    "d_collabvault": "虚空宝库",
    "d_collabnova": "新星爆发",
    "d_auroraside1": "樱花 MKII",
    "d_queenside1": "女王荣耀",
    "d_queenomegaduel": "女王荣耀",
    "d_idolside1": "幕布揭开",
    "d_idolside2": "幕布揭开",
    "d_dragoonstory1": "神话传说",
    "d_dragoonstoryflame": "神圣烈焰",
    "d_esperside1": "演示装置",
    "d_esperside2": "演示装置?",
    "d_leoside1": "机械工具箱",
    "d_leoside2": "烈焰装备",
    "d_idolexpuzzle1": "解谜工具箱",
    "d_leoexpuzzle1": "解谜工具箱",
    "d_expuzzlemage": "解谜工具箱",
    "d_collabedendemo": "伊甸边境",
    "d_collabcrossdemo": "远星旅人",
    "d_collabvaultdemo": "虚空宝库",
    "d_collabnovademo": "新星爆发",
    "e_boss1effect_spawn": "召唤<key> {0} </>个随从.",
    "e_boss1effect_spawn_upgrade": "召唤<key> {0} </>个随从<uadd>[</>，并根据本卡牌拥有的计数点等量增加随从的生命值<uadd>]</>.",
    "e_boss1effect_splash": "对对方场地上所有卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss1effect_splashtrigger": "当一张卡牌被摧毁时，对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss2effect_aoe": "对对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss2effect_passive": "根据己方场地上的卡牌数目(<key> X </>张)，本卡牌每次受到的伤害减少<key> X -1 </>点(当前总共减少：<key>- {0} </>点).",
    "e_boss2effect_spawn": "当本卡牌受到伤害时，召唤一个生命值等同于本次受到的伤害值的随从.",
    "e_boss2effect_superspawn": "根据己方场地上的空位数目(<key> X </>格)，召唤<key> X - 1 </>个生命值为<health> {0}X  </>点的随从(当前随从生命值：<health> {1} </>点).",
    "e_boss3effect_blast": "摧毁场地上没有效果的所有的卡牌，每摧毁一张卡牌便造成<health> {0} </><img id=\"\"player_health\"\"/> 生命值伤害.",
    "e_boss3effect_control": "将对方场地上所有卡牌转移到己方场地上，然后移除它们的效果.",
    "e_boss3effect_spawn": "召唤<key> 3 </>个随从并清除己方弃牌堆中所有的卡牌.",
    "e_boss3effect_spawn_super": "召唤<key> {0} </>个随从并清除己方弃牌堆中所有的卡牌，并根据本卡牌拥有的计数点等量增加随从的生命值，然后本卡牌获得<key> 1 </>个计数点.",
    "e_boss3effect_protection": "将本卡牌受到的伤害降低至<key> 0 </>点；若对方场地上恰好有<key> {0} </>张没有效果的卡牌，则该效果无效(当前对方场地上没有效果的卡牌个数/令该效果无效需要的没有效果的卡牌数目：{1}/{0}).",
    "e_boss4effect_dagger_move": "当对方的一张卡牌发动攻击后，将本卡牌向发动攻击的卡牌的方向斜后移动一格(若目标位置已经有一张卡牌，则与其交换位置).",
    "e_boss4effect_scythe_destruct": "增加己方场上其他的所有卡牌的攻击力<key> {0} </>点.",
    "e_boss4effect_scythe_move": "当对方的一张卡牌发动攻击后，将本卡牌移动到发动攻击的卡牌的同列前排位置(若目标位置已经有一张卡牌，则与其交换位置).",
    "e_boss4effect_spawn": "召唤<key> 1 </>个随从.",
    "e_boss4effect_superspawn": "在对方场上与这张牌所在的同一列的第一排生成一张 <key>魂魄</> 卡牌，如果此处有卡牌，则将其覆盖.",
    "e_boss4effect_soul_death": "当本卡牌从场地上被移除到弃牌堆中时，游戏失败.",
    "e_boss4effect_weapondeath": "当本卡牌从场地上被移除到弃牌堆中时，增加己方场地上所有卡牌的攻击力<key> {0} </>点.",
    "e_boss5effect_1": "当对方打开卡组编辑器时，增加本卡牌<attack> 1 </>点攻击力.",
    "e_boss5effect_2": "当本卡牌受到伤害时，若本卡牌拥有计数点，则消耗一个计数点并将本卡牌本次受到的伤害降低至<key> 0 </>点；否则，本卡牌获得<key> 1 </>个计数点.",
    "e_boss5effect_bombminion": "对你的场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害并造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_boss5effect_left1": "丢弃对方手牌中所有的卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_boss5effect_left2": "在对方场上与这张牌所在的同一列的第一排生成一个随从，如果此处有卡牌，则将其覆盖.",
    "e_boss5effect_right1": "对对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss5effect_right2": "召唤<key> {0} </>个随从.",
    "e_bossb1_1": "根据对方场地上的空位数目(<key> X </>格)，召唤一个生命值为<health> {1}X </>点的随从(最低生命值：<health> 1 </>点). 然后向对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>魔法伤害.",
    "e_bossb1_2": "当本卡牌拥有计数点时，若对方将手牌中的一张卡牌放置到场地上，则本卡牌发动一次攻击.",
    "e_bossb1_3": "本卡牌获得<key> {0} </>个计数点(最大计数点个数：<key> {0} </>个). 当本卡牌拥有计数点时，根据本卡牌拥有的计数点数目等量减少己方场地上其他卡牌受到的伤害. 当本卡牌受到伤害时，移除<key> 1 </>个计数点.",
    "e_bossb1_minion_1": "造成等同于本卡牌攻击力的  <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossb1_minion_2": "当对方场地上的一张卡牌移动时，对其造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_bossb2_1": "召唤<key> {0} </>个拥有<key> {1} </>个或<key> {2} </>个计数点的随从.",
    "e_bossb2_2": "场地上所有卡牌获得<key> {0} </>个计数点(每张卡牌拥有的计数点个数不会因此超过<key> {1} </>个).",
    "e_bossb2_3": "当拥有计数点的卡牌受到伤害时，那张卡牌将消耗一个计数点并将其本次受到的伤害降低至<key> 0 </>点.",
    "e_bossb2_minion_1": "当本卡牌对其他卡牌造成伤害但没有将其生命值降为<health> 0 </>点时，造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossb3_1": "当本卡牌拥有计数点时，召唤<key> {1} </>个随从；否则，召唤<key> {0} </>个随从. 召唤后本卡牌获得<key> {2} </>个计数点(最大计数点个数：<key> {2} </>个).",
    "e_bossb3_2": "当本卡牌受到伤害时，根据本卡牌拥有的计数点等量减少本卡牌受到的伤害(当前伤害减少量：-<key> {0} </>点). 若该伤害值不高于本卡牌拥有的计数点数目，则消耗<key> 1 </>个计数点；否则，消耗所有的计数点.",
    "e_bossb3_3": "当己方场地上其他的一张卡牌被摧毁时，触发己方场地上除本卡牌以外的所有卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块.",
    "e_bossb3_minion_1": "本卡牌发动 {0} 次攻击.",
    "e_bossb3_minion_2": "本卡牌发动一次攻击，该次攻击会造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bossb3_minion_3": "对对方场地上所有卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bossb3_minion_4": "召唤 {0} 个随从.",
    "e_bossb4_1": "对对方手牌中所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害，然后根据先前对方手牌中拥有的卡牌数目召唤等量的随从.",
    "e_bossb4_2": "当场地上一张卡牌被摧毁时，本卡牌获得<key> 1 </>个计数点. 当本卡牌拥有的计数点不少于<key> {0} </>个时，消耗所有计数点并对场地上所有卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/>  魔法伤害(包括本卡牌).",
    "e_bossb4_3": "根据本卡牌拥有的计数点数目，对对方场地上所有的卡牌造成等量的魔法伤害(最小魔法伤害：<magic> 1 </><img id=\"\"dmg_magic\"\"/>  )(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/>  ).",
    "e_bossb5_1": "根据本卡牌的攻击力(<key> X </>点)，召唤<key> X </>个生命值为<health> X </>点的随从(当前随从个数：<key> {0} </>个).",
    "e_bossb5_2": "当本卡牌通过攻击造成不低于<key> 0 </>点的伤害时，<void>放逐</>除目标外对方场地上所有<expose>暴露的</>卡牌.",
    "e_bossb5_3": "增加本卡牌的攻击力<attack> {0} </>点.",
    "e_bossb6_1": "将对方弃牌堆中所有的卡牌洗入抽牌堆中，然后将对方场地上前排的卡牌移动到后排，后排的卡牌洗入抽牌堆，再令对方抽取卡牌至手牌中卡牌数目为<key> 5 </>张.",
    "e_bossb6_2": "当本卡牌拥有的计数点数目少于<key> {0} </>个时，若己方场地上其他的卡牌将受到伤害时，则将其受到的伤害降低至<key> 0 </>点，然后本卡牌获得等同于其降低的伤害数值的计数点(最大计数点个数：<key> {0} </>个)；否则，该效果无效.",
    "e_bossb6_3": "本卡牌受到的伤害不会超过其拥有的计数点数目(当本卡牌没有计数点时，将本卡牌受到的伤害降低至<key> 0 </>点). 当本卡牌受到伤害时，根据所受伤害的数值移除等量的计数点.",
    "e_bossb6_extra_1": "根据本卡牌持有的计数点数目召唤等量的随从(最少随从数目：<key> 1 </>个)，然后本卡牌获得一个计数点(最大计数点个数：<key> {0} </>个).",
    "e_bossb7_1": "根据对方场地上的卡牌数目召唤等量的随从(最少随从数目：<key> {0} </>个).",
    "e_bossb7_2": "当己方场地上的卡牌被摧毁时，本卡牌获得<key> 1 </>个计数点. 当本卡牌拥有的计数点数目不少于<key> {0} </>个时，消耗所有计数点并令己方场地上所有的卡牌发动一次攻击.",
    "e_bossb7_3": "根据本卡牌拥有的计数点数目发动相同次数的攻击(最少攻击次数：<key> 1 </>次)(当前攻击次数：<key> {0} </>次).",
    "e_bossb8_1": "摧毁己方场地上所有的随从. 每摧毁一个随从，便造成<health> {1} </><img id=\"\"player_health\"\"/> 角色生命值伤害，然后召唤<key> {0} </>个随从.",
    "e_bossb8_2": "当对方放置一张卡牌时，召唤一个攻击力和生命值等于本卡牌拥有的计数点数目的随从(最低随从数值：<attack>1</>|<health>1</>)，然后本卡牌获得一个计数点.",
    "e_bossb8_3": "根据本卡牌拥有的计数点数目(<key> X </>个)，对对方场地上所有的卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/>  魔法伤害(最低魔法伤害：<magic> 1 </><img id=\"\"dmg_magic\"\"/>  )，随后消耗本卡牌拥有的所有计数点.",
    "e_bossb8_minion_1": "本列的卡牌无法对位于其他列的卡牌造成伤害.",
    "e_bossb8_minion_2": "对本列所有属于对方的卡牌造成 <magic>{0}</><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_bossb9_1": "召唤<key> {0} </>个攻击力和生命值等于本卡牌攻击力的随从；若本卡牌拥有正好<key> 4 </>个计数点，改为召唤<key> 4 </>个随从；若本卡牌拥有正好<key> 8 </>个计数点，改为召唤<key> 8 </>个随从.",
    "e_bossb9_2": "当对方放置一张卡牌或触发<key>回合抽牌</>时，本卡牌获得<key> 1 </>个计数点；当本卡牌拥有<key> {0} </>个计数点时，改为消耗所有计数点并增加本卡牌的攻击力<attack> {1} </>点.",
    "e_bossb9_3": "将己方场地上所有卡牌承受的伤害降低<key> {0} </>点；若本卡牌拥有正好<key> 4 </>或<key> 8 </>个计数点时，该效果无效.",
    "e_bossb9_minion_1": "当本卡牌对一张对方卡牌造成伤害或受到伤害以后，若本卡牌还位于场地上，<void>放逐</>目标卡牌或对其造成伤害的卡牌.",
    "e_bosscomet1_1": "当本卡牌受到不低于<key> 0 </>点的伤害且本卡牌未被摧毁时，将本卡牌移动到随机位置并在本卡牌原先的位置召唤<key> 1 </>个随从；若本卡牌被摧毁，则该效果无效.",
    "e_bosscomet1_2": "本卡牌发动四次攻击，每次造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bosscomet1_minion": "将己方场地上与本卡牌不同名的卡牌受到的伤害降低至<key> 0 </>点.",
    "e_bosscomet2_1": "当本卡牌受到伤害时，<key>挂起</>本卡牌<key> {0} </>回合并令本卡牌获得一个计数点. 当本卡牌拥有<key> {1} </>个计数点时，消耗所有计数点，然后对对方场地上所有的卡牌造成<magic> {2} </><img id=\"\"dmg_magic\"\"/>  魔法伤害并造成<health> {2} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bosscomet3_1": "召唤<key> {0} </>个拥有随机数值的生命值和攻击值的随从，然后将本卡牌移动到随机位置；若对方弃牌堆中有不少于<key> {1} </>张 <key>堕落</> 卡牌，则改为召唤数值为<attack>{2}</>|<health>{3}</>的随从.",
    "e_bosscomet3_2": "当已方场地上有其他卡牌时，将本卡牌受到的伤害减少<key> {0} </>点.",
    "e_bosscomet3_3": "将<key>堕落</>卡牌放置到对方场地上所有的空位处.",
    "e_bosscomet3_bomb_trigger": "当本卡牌被移动到其他位置时，将本卡牌洗入抽牌堆中.",
    "e_bosscomet3_bomb": "造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossomega_core": "当本卡牌受到伤害时，<key>挂起</>己方场地上其他的所有卡牌<key> {0} </>回合.",
    "e_bossomega_countdown": "将对方的 <img id=\"\"player_health\"\"/> 角色生命值降低至<health> 0 </><img id=\"\"player_health\"\"/> .",
    "e_bossomega_passive": "每回合后，将本卡牌的生命值恢复至<health>最大生命值</>.",
    "e_bossomega_transform": "当本卡牌被摧毁时，形态转换.",
    "e_consumablecache": "当本卡牌被放置在场上时，本卡牌获得<key> {0} </>个<img id=\"\"loot\"\"/>( {1} ).",
    "e_consumablecacheremoval": "当本卡牌受到伤害时，<void>放逐</>己方场地上其他的所有 <key>.potion</> 卡牌.",
    "e_enemyartillery": "增加己方场地上其他的所有<key>火炮.sc</>卡牌的攻击力<attack> {0} </>点.",
    "e_enemyblackvirus_manual": "造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyblackvirus_triggeer": "当本卡牌被场地上一张卡牌伤害时，将其转化为本卡牌并移除其等级与该效果；当对本卡牌造成伤害的卡牌未位于场地上时，该效果无效.",
    "e_enemychandelier": "当场地上一张卡牌移动时，增加本卡牌的攻击力<key> {0} </>点，攻击后重置攻击力.",
    "e_enemycollapse": "当对方场地上拥有至少<key> {0} </>张卡牌时，若对方一张卡牌的效果被触发，则对对方场地上所有的卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemycommandsignal_destroy": "己方场地上所有卡牌发动一次攻击.",
    "e_enemycommandsignal_manual": "己方场地上所有卡牌发动一次攻击；若己方场地上没有卡牌能发动攻击，则对角色造成<health> 1 </> <img id=\"\"player_health\"\"/> 生命值伤害然后<decompile>反编译</>本卡牌.",
    "e_enemydaggers": "当对方将手牌中的一张卡牌放置到场地上时，本卡牌发动一次攻击，然后增加本卡牌的攻击力<attack> {0} </>点(攻击力增加上限：+<attack> {1} </>点).",
    "e_enemydetonator": "对场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemydisruptor_passive": "当对方抽取一张卡牌时，治疗本卡牌<health> 1 </>点生命值.",
    "e_enemydisruptor_trigger": "当本卡牌受到伤害时，丢弃对方抽牌堆顶端的卡牌.",
    "e_enemyghostblue": "当本卡牌造成伤害或受到伤害时，将目标卡牌或对本卡牌造成伤害的卡牌移动到对方场地上的随机位置.",
    "e_enemyghostred": "当本卡牌受到伤害时，将本卡牌移动到随机位置.",
    "e_enemyguardian": "当对方抽取一张卡牌时，增加本卡牌的攻击力<attack> 1 </>点.",
    "e_enemyinterceptor": "当己方场地上的卡牌受到伤害时，本卡牌发动一次攻击.",
    "e_enemymiasma_damage": "对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemymiasma_protect": "根据己方场地上与本卡牌不同名的卡牌数目，等量降低本卡牌受到的伤害(当前伤害减少量：-<key> {0} </>点).",
    "e_enemyminibosscurse_attack": "将本卡牌移动到随机位置，然后本卡牌发动一次攻击，该次攻击会造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_enemyminibosscurse": "当本卡牌受到伤害时，对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemymirrorshard": "当本卡牌受到伤害时，其他<key>反射棱镜.mw</>将发动一次攻击，该次攻击会造成等同于此次受到的伤害值的伤害.",
    "e_enemyobserver": "当对方的卡牌触发效果时，<void>放逐</>抽牌堆、手牌、场牌和弃牌堆中除触发效果的卡牌以外与那张卡牌同名的所有卡牌.",
    "e_enemypathogen_destruct": "丢弃对方手牌中所有的卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_enemypathogen": "对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemyphantomred": "将对方场地上所有位于后排的卡牌移动到前排(若目标位置已经有一张卡牌，则与其交换位置).",
    "e_enemypredator": "当对方场地上不是满生命值的卡牌移动时，将本卡牌移动到对应卡牌同一列的己方前排位置并发动一次攻击.",
    "e_enemyrailgun": "当本卡牌受到伤害时，增加本卡牌的攻击力<attack> {0} </>点.",
    "e_enemytalismanblack": "移除对方场地上所有卡牌上的效果，若对象是一张没有效果的卡牌，则将它摧毁.",
    "e_enemyvenomdestruct": "将本卡牌添加到抽牌堆顶端.",
    "e_enemyvenomexecute": "造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyvenommanual": "摧毁本卡牌并造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyvirusblue": "当本卡牌造成伤害或受到伤害时，移除目标卡牌或对本卡牌造成伤害的卡牌的所有效果.",
    "e_enemyvirusred_attack": "攻击没有任何效果的卡牌时，该次攻击造成<attack> {0} </>点伤害.",
    "e_enemyvirusred_passive": "本卡牌不会受到没有任何效果的卡牌造成的伤害.",
    "e_enemywhitetalisman_trigger": "当一张等级不低于<key> 1 </>级的己方卡牌被移除到弃牌堆中时(除了 <key>白色护符.tlsm</> )，将本卡牌转换为那张卡牌的复制品.",
    "e_enemywormblue": "当本卡牌发动攻击并对一张卡牌造成伤害时，对目标卡牌所在行的其他卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemywormred": "本卡牌发动两次攻击，每次造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_enemyzombie": "若本卡牌已于先前的回合被摧毁并处于弃牌库之中，当己方场地上一张卡牌被摧毁时(除了 <key>僵尸.mw</> )，将本卡牌放置到己方场地上.",
    "e_haloshield": "将与本卡牌不同名的卡牌受到的伤害降低至 0 点.",
    "e_shareddelayonhit": "当本卡牌受到伤害时，<key>挂起</>本卡牌 {0} 回合.",
    "e_sharedoneshotonly": "当本卡牌受到伤害但没有被摧毁时，游戏失败.",
    "e_specialcryptcache_drafting": "当本卡牌被放置到场地上时，本卡牌获得<key> {0} </>个 <img id=\"\"loot\"\"/>.",
    "e_specialcryptcache_random": "当本卡牌被放置到场地上时，本卡牌获得一定数目的<img id=\"\"loot\"\"/>.",
    "e_specialcryptcache": "当本卡牌被放置到场地上时，本卡牌获得包括一张<img id=\"\"effect_consumable\"\"/> 消耗品卡牌在内的一定数目的<img id=\"\"loot\"\"/>.",
    "e_specialsanctum": "当本卡牌被放置到场地上时，治疗<key> {0} %</>失去的 <img id=\"\"player_health\"\"/> 角色生命值. 然后<key>重新加载</>对方的所有卡牌.",
    "e_specialtimebomb": "游戏失败.",
    "e_specialwaystone": "当本卡牌被放置到场地上时，打开卡组编辑器.",
    "e_storyantiaurora": "将用户名为<key>曙光</>的角色的 <img id=\"\"player_health\"\"/> 角色生命值降低至0点.",
    "e_storyendgamelock": "当一张<key>龙息</><decompile>反编译</>一张特定卡牌时，摧毁本卡牌.",
    "e_storyflowerhologram": "当本卡牌被摧毁时，将己方场地上与本卡牌相邻(不包括对角线)卡牌的行动倒计时设置为 {0} .",
    "e_storyhydrogencard": "当对方触发了<key>回合抽牌</>时，摧毁本卡牌并将 <img id=\"\"player_health\"\"/> 角色生命值设置为<health> 0 </>点.",
    "e_storyoxygencard": "将本卡牌受到的伤害降低至 0 点；若本卡牌左右两侧的卡牌为\"\" <key>氢气</> \"\"，则该效果无效.",
    "e_storystealer": "<decompile>反编译</>对方场地上、手牌中和抽牌堆中所有的卡牌.",
    "e_storysyncmark": "当一张<key>同步标记</>被移除到弃牌堆中时，游戏失败. 若所有的 <key>同步标记</> 卡牌在同一次操作里被移除到弃牌堆中，则此效果无效.",
    "e_bossb10_1": "当对方场地上的一张卡牌移动时，将本卡牌移动到随机位置并将弃牌库顶端的卡牌放置到本卡牌移动前所在的位置.",
    "e_bossb10_2": "当对方手牌中和场地上的卡牌数目之和不少于己方场地上的卡牌数目时，在本卡牌攻击后，<decompile>反编译</>场地上除本卡牌以外所有的卡牌(当前己方卡牌数目和对方卡牌数目：<key> {0} </>vs<key> {1} </>).",
    "e_bossb10_3": "将己方弃牌库中所有的卡牌按照从左到右、从前排到后排的顺序依次放置到场地上，然后将<key> {0} </>个魔法添加到己方弃牌堆中.",
    "e_bossb10_minion_shared_adder": "增加本卡牌<health> 1 </>点<health>最大生命值</>(增加量上限：+<uadd>[</><health> {0} </><uadd>]</>点). 若本卡牌的最大生命值已达到最大值，则<void>放逐</>本卡牌.",
    "e_bossb10_minion_1": "根据己方场地上与本卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，进行一次攻击，该次攻击会造成<physical> X </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前伤害：<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_bossb10_minion_2": "根据己方场地上与本卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，对对方场地上所有卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/>  魔法伤害(当前伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/>  ).",
    "e_bossb10_minion_3": "根据己方场地上与本卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，丢弃对方抽牌堆顶端<key> X </>张卡；若该效果发动时对方的抽牌堆中没有卡牌，则造成<health> X </> <img id=\"\"player_health\"\"/> 角色生命值伤害(当前弃牌数目：<key> {0} </>张).",
    "e_bossmahou_1": "当己方场地上的一张卡牌被摧毁时，召唤一张随机的随从，随后消耗本卡牌一半的计数点.",
    "e_bossmahou_2": "当本卡牌受到伤害时，根据本卡牌拥有的计数点数目发动相同次数的攻击(当前攻击次数：<key> {0} </>)，然后消耗<key> 1 </>个计数点.",
    "e_bossmahou_3": "<void>放逐</>场地上其他所有<expose>暴露的</>卡牌以及己方弃牌堆中的所有的卡牌，并召唤<key> {0} </>个随机的随从，然后本卡牌获得<key> {1} </>个计数点.",
    "e_ability_aurora": "当你进行消耗回合数的操作时(比如放置一张卡牌或移动一张卡牌)，消耗 1 点<key>宁静点数</>并使<key>威胁等级</>与场上的倒计时不变化.",
    "e_ability_aurora_counters": "本卡牌获得<key> {0} </>点<key>宁静点数</>.",
    "e_ability_dragoon": "令抽牌堆、弃牌堆、场地上和手牌中的所有己方卡牌获得 <key>.*</> 符号且 <key>.*</> 符号可被视作任意的后缀.",
    "e_ability_esper": "当一张等级不高于<key> {0} </>级的卡牌放置到己方场地上时(除了 <key>世界之种</> )，将本卡牌转化为那张卡牌初始状态的复制品.",
    "e_ability_idol": "将场地上所有的己方卡牌返还到手牌中，并根据返还的卡牌数目(<key> X </>张)，选择手牌中至多<key> X </>张原来未位于场地上的己方卡牌，将其放置到场地上.",
    "e_ability_leo_1": "重新激活场地上的所有己方卡牌，并增加其攻击力<attack> {0} </>点.",
    "e_ability_leo_2": "当一张己方卡牌被移除到弃牌堆中时(除了 <key>群山</> )，将其返还到手牌中.",
    "e_ability_omega": "选择场地上至多两张卡牌，若选择了己方卡牌，则将其<key>自动化</>，若选择了对方卡牌，则延迟其行动倒计时<key> {0} </>回合.",
    "e_ability_queen": "触发场地上所有己方卡牌的<img id=\"\"effect_manual\"\"/>指令式模块. 在该效果生效期间，所有己方卡牌造成的伤害提升至<key> {0} </>倍.",
    "e_artifact_greed_active": "抽取<key> {0} </>张卡牌.",
    "e_artifact_greed": "当你触发<key>回合抽牌</>时，额外抽取一张卡牌并丢弃抽牌堆顶端<key> 2 </>张卡牌. 当抽牌堆中没有卡牌时，每回合造成<key> 1 </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_artifact_memory": "当你触发<key>重新加载</>效果时，将存储空间中全部等级不低于<key> 1 </>级的卡牌添加到抽牌堆中.",
    "e_artifact_momentum_active": "触发<key>回合抽牌</>.",
    "e_artifact_momentum": "当一张对方卡牌被摧毁时，触发<key>回合抽牌</>. 当你抽取一张卡牌时，若手牌中卡牌数目不低于<key> {0} </>张，则<decompile>反编译</>抽取的卡牌并减少回合抽牌倒计时<key> 1 </>点.",
    "e_artifact_spire_active": "丢弃手牌中所有的卡牌并抽取<key> {0} </>张卡牌.",
    "e_artifact_spire": "当你触发<key>回合抽牌</>时，若手牌中没有卡牌，则额外抽取<key> {0} </>张卡牌. 当你抽取一张卡牌时，若手牌中卡牌数目不低于<key> {1} </>张，则<decompile>反编译</>被抽取到的卡牌.",
    "e_artifact_starter": "<key>重新加载</>后，将本卡牌放置到抽牌堆顶端.",
    "e_chess_bishop_init": "治疗场地上所有己方卡牌的生命值<health> 1 </>点.",
    "e_chess_bishop_manual": "对对角线上最近的一张对方卡牌发动一次攻击.",
    "e_chess_king_death": "当本卡牌从场地上被移除到弃牌堆中时，游戏失败.",
    "e_chess_king_init": "当弃牌堆中至少有一张卡牌时，将你的弃牌堆洗入抽牌堆并仅<key>重新加载</>抽牌堆直至手牌、场上牌与抽牌堆得以构成完整的象棋卡组，然后根据原先弃牌堆中的卡牌数目等量增加本卡牌的攻击力(攻击力增加上限：+<attack> {0} </>点)(当前攻击力增加量：+<attack> {1} </>点)，然后抽取卡牌至手牌中卡牌数目为 {2} .",
    "e_chess_king_manual": "将本卡牌从场地上或从弃牌堆中洗入抽牌堆中，并抽取一张卡牌.",
    "e_chess_knight_init": "本卡牌发动一次攻击.",
    "e_chess_knight_manual": "对 3 * 2 格的对角线上的一张对方卡牌发动一次攻击.",
    "e_chess_pawn_manual": "对左上角或右上角紧挨本卡牌的一张对方卡牌发动一次攻击.",
    "e_chess_pawn_trigger": "当本卡牌造成伤害时，本卡牌获得<key> 1 </>个计数点. 当本卡牌拥有<key> {0} </>个计数点时，消耗所有计数点并将本卡牌转化为 <key>女王</> ，同时触发其初始化效果.",
    "e_chess_queen_init": "根据场地上所有己方卡牌的数目，对所有对方卡牌造成等量的魔法伤害(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_chess_queen_loot": "消耗所有<img id=\"\"loot\"\"/>. 每消耗一个<img id=\"\"loot\"\"/>，治疗<health> 1 </><img id=\"\"player_health\"\"/> 角色生命值(当前治疗量： {0} <img id=\"\"player_health\"\"/> ).",
    "e_chess_queen_manual": "对所有对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_chess_rook_manual": "本卡牌发动一次攻击.",
    "e_chess_rook_passive": "当本卡牌受到伤害时，增加其攻击力<attack> {0} </>点. 当本卡牌通过攻击造成伤害时，攻击目标后方的一张卡牌也受到等量伤害.",
    "e_dragoon_condition": "<decompile>反编译</>场地上<key> {0} </>张己方卡牌，解除限制.",
    "e_dragoon_flame": "<decompile>反编译</>场地上生命值为<health> 1 </>的所有对方卡牌.",
    "e_dragoon_shared": "当本卡牌受到伤害时，所有具有该效果的卡牌将受到等量的伤害. 若该伤害来自具有该效果的卡牌，则此效果无效.",
    "e_eden_bowsnipe": "对前方一列对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_crossfire": "对对角线上除本卡牌以外的所有卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_gunner_boost": "当你触发<key>回合抽牌</>时，本卡牌获得一个<uadd>[</><attack> {0} </><uadd>]</>点的不可叠加的<specialbuff>一次性的攻击力增益</>.",
    "e_eden_gunner": "当本卡牌造成伤害时，若其拥有至少<key> {1} </>个计数点，则消耗所有计数点并减少回合抽牌倒计时<key> {0} </>点；否则，本卡牌获得<key> 1 </>个计数点.",
    "e_eden_hazel_adder": "将弃牌堆中随机一张 <key>.edx</> 卡牌返还到手牌中.",
    "e_eden_hazel": "当本卡牌造成不低于<key> 0 </>点的伤害时，移除本卡牌所在行上攻击力为<attack> 0 </>点的所有卡牌的效果和数值调整，并将其数值设置为<uadd>[</><attack>{0}</>|<health>{1}</><uadd>]</>.",
    "e_eden_ragnarok": "根据本卡牌的攻击力(<key> X </>点)，对前方第<key> 2 </>格的一张对方卡牌造成<uadd>[</><magic> {0}</><uadd>]</><magic>X </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害(最大魔法伤害：<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>). 若该伤害对目标卡牌造成伤害，则对其他所有对方卡牌造成该伤害一半的魔法伤害(向上取整).",
    "e_eden_reva_reflect": "当本卡牌受到伤害时，其获得一个等同于本次受到的伤害的<specialbuff>衰减性的攻击力增益</>(攻击力增加上限：+<attack> {0} </>点)，然后本卡牌发动一次攻击.",
    "e_eden_reva": "当本卡牌移动到另一列时，治疗其生命值<health> {0} </>点. 当本卡牌移动到另一行时，治疗其生命值<health> {1} </>点. 这两种效果可以同时发生.",
    "e_eden_saffron_destruct": "将本卡牌返还到手牌中.",
    "e_eden_saffron": "将抽牌堆中随机<uadd>[</><key> {0} </><uadd>]</>张<key>.edx</>卡牌添加到手牌中.",
    "e_eden_selicy": "当本卡牌造成伤害时，本卡牌发动一次攻击.",
    "e_eden_sharedatkcondition": "当回合抽牌倒计时不高于<key> {0} </>点时，解除限制. 当本卡牌被放置到己方场地上时，增加回合抽牌倒计时<key> {1} </>点.",
    "e_eden_sharedattacking": "当另一张等级不低于<key> 1 </>级的卡牌的 <img id=\"\"effect_init\"\"/> 初始化效果在本卡牌所在列触发时，本卡牌将被视作发动者. 若那张卡牌是<key>.edx</>卡牌，则<decompile>反编译</>那张卡牌并抽取一张卡牌.",
    "e_eden_shiso_kill": "当本卡牌摧毁一张卡牌时，抽取一张卡牌.",
    "e_eden_shiso": "当本卡牌造成伤害时，本卡牌获得一个<attack> {0} </>点<specialbuff>一次性、衰减性的攻击力增益</>(攻击力增加上限：+<attack> {1} </>点).",
    "e_eden_shopkeeper_damage": "当本卡牌造成伤害时，触发洗牌.",
    "e_eden_shopkeeper": "选择抽牌堆中随机<key> {0} </>张卡牌中的一张，将<key> {1} </>张所选卡牌的复制品添加到抽牌堆顶端.",
    "e_eden_stepslash": "对前方一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害. 若本卡牌在后排，则将其移动到前排(若前排已经有一张卡牌，则与其交换位置)，然后对本卡牌前方第<key> 1 </>格的一张对方卡牌造成<uadd>[</><physical> {1} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_eden_terra_pull": "当本卡牌造成伤害时，若目标在后排且前面没有卡牌，则将其移动到前排.",
    "e_eden_terra": "增加本卡牌造成的伤害<uadd>[</><key> {0} </><uadd>]</>点.",
    "e_eden_thunder": "对前方第<key> 2 </>格的一张对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_violette_boost": "当本卡牌拥有至少<key> {0} </>个计数点时，若其触发一个效果，则消耗所有计数点并再次触发那个效果.",
    "e_eden_violette": "当本卡牌移动时，根据本卡牌最后移动的方向触发一个效果(对角线移动不计入计算). 向上：本卡牌发动一次攻击；向下：治疗其生命值<health> {0} </>点；向左或向右：本卡牌获得<key> 1 </>计数点(最大计数点个数：<key> {1} </>个).",
    "e_eden_violette_upgrade": "当本卡牌移动时，本卡牌获得<key> 1 </>计数点(最大计数点个数：<key> {1} </>个)，并根据本卡牌最后移动的方向触发一个效果(对角线移动计入计算). 向上：本卡牌发动一次攻击；向下：治疗其生命值<health> {0} </>点.",
    "e_eden_wave": "对前方一张对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害. 当目标在前排且后面没有卡牌时，将其移动到后排并对其造成额外<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害；当目标在后排且前面没有卡牌时，将其移动到前排.",
    "e_fantasy_arae": "本卡牌伤害对方卡牌后，被伤害的卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个). 当本卡牌所在列的对方卡牌拥有计数点时，根据那张卡牌拥有的计数点数目，等量增加其受到的伤害(最大额外伤害为：<uadd>[</><attack>+ {0} </><uadd>]</>点).",
    "e_fantasy_cock": "对所有对方卡牌造成 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 点魔法伤害并延迟其行动 <key>{1}</> 回合.",
    "e_fantasy_cockcondition": "当所有对方卡牌的行动倒计时总和不低于<key> {0} </>时，解除限制(当前对方所有卡牌的行动倒计时总和/需要的对方卡牌的行动倒计时总和：{1}/{0}).",
    "e_fantasy_griffin": "当场地上与本卡牌不同名的其他己方卡牌将受到超过<key> 1 </>点伤害时，本卡牌将代替其承受伤害.",
    "e_fantasy_mermaid": "<key>重新激活</>己方场地上所有的卡牌并强化其攻击力与生命值(<uadd>[</><attack>+{0}</>|<health>+{1}</><uadd>]</>).",
    "e_fantasy_mermaidcondition": "当弃牌堆中至少有 <key>{0}</> 张卡牌且弃牌堆中所有的卡牌都不同名时，解除限制.",
    "e_fantasy_phoenix": "将本卡牌从弃牌堆中返还到手牌中.",
    "e_fantasy_unicorn": "当场地上生命值大于<health> 1 </>点的所有己方卡牌受到致命伤害时，保留其<health> 1 </>点生命值.",
    "e_fantasy_highlandcondition": "当弃牌堆中至少有 <key>{0}</> 张卡牌且弃牌堆中所有的卡牌都不同名时，解除限制.",
    "e_generic_afterburner": "抽取卡牌至手牌中卡牌数目为<uadd>[</><key> {0} </><uadd>]</>张.",
    "e_generic_avarice": "若弃牌堆有不低于<key> {0} </>张卡牌，选择弃牌堆中的<key> {0} </>张卡牌，将其洗入抽牌堆中并抽取<uadd>[</><key> {1} </><uadd>]</>张卡牌.",
    "e_generic_battery": "触发<key>回合抽牌</>.",
    "e_generic_beartrap": "仅当本卡牌位于弃牌堆中时，该效果可被触发. 触发后，延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合并对其造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害，然后<void>放逐</>本卡牌.",
    "e_generic_cinder": "延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_generic_constantcorrection": "选择场地上一张己方卡牌，移除其所有效果和数值调整，并将其数值设置为<uadd>[</><attack>{0}</>|<health>{0}</><uadd>]</>.",
    "e_generic_crystalball": "选择抽牌堆中一张数值与抽牌堆顶端卡牌相同的卡牌，将其添加到手牌中并洗牌.",
    "e_generic_doubleexecute_extra": "将本卡牌从弃牌堆中返还到手牌中.",
    "e_generic_doubleexecute": "并列执行场地上所有己方卡牌.",
    "e_generic_ember": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_generic_fireball": "对前方一张对方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_flash": "根据前方一张对方卡牌的回合倒计时，对其造成等量的魔法伤害.",
    "e_generic_flashbang": "摧毁本卡牌并延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_generic_force": "对前方一张对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害并将其移动到后排(若后排已经有一张卡牌，则交换它们的位置).",
    "e_generic_giveandtake_1": "当本卡牌没有计数点时，若有卡牌将受到伤害，则将其受到的伤害降低至<key> 0 </>点. 并根据降低的伤害数目，本卡牌获得等量的计数点(最大计数点数目：<uadd>[</><key> {0} </><uadd>]</>个). 忽略已经受到 <key>电容器</> 影响的伤害(场上有多张此卡存在，互不影响彼此的效果).",
    "e_generic_giveandtake_2": "当本卡牌拥有计数点时，若有卡牌将受到伤害，则消耗所有计数点并根据消耗的计数点数目等量增加其受到的伤害. 忽略已经受到 <key>电容器</> 影响的伤害(场上有多张此卡存在，互不影响彼此的效果).",
    "e_generic_giveandtake_3": "刷新本卡牌上所有的 <img id=\"\"effect_once\"\"/> 一次性效果.",
    "e_generic_gravity": "抽取一张卡牌，然后根据你弃牌堆中<key>重力</> 的总量再抽取等量的卡牌 (当前抽取卡牌数：<key>{0}</> 张).",
    "e_generic_inferno": "当本卡牌位于场地上时，若你放置一张卡牌，则对场地上本卡牌以外的所有卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_generic_magicember": "<decompile>反编译</>场地上数值为<attack>0</>|<health>1</>所有的己方卡牌，并抽取等同于<decompile>反编译</>的卡牌数目的卡牌(当前抽取卡牌数目：<key> {0} </>张)(任何时候你都可以左右拖曳手牌以改变手牌的顺序).",
    "e_generic_magicflare": "<decompile>反编译</>场地上数值为<attack>0</>|<health>1</>的所有己方卡牌，并对所有对方卡牌造成等同于<decompile>反编译</>的卡牌数目的 <img id=\"\"dmg_magic\"\"/> 魔法伤害(当前伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_generic_megarush": "当角色生命值为<health> 1 </><img id=\"\"player_health\"\"/> 时，增加场地上所有己方卡牌的攻击力<uadd>[</><attack> {0} </><uadd>]</>点并摧毁本卡牌.",
    "e_generic_omen": "当另一张卡牌的效果触发时，增加本卡牌的攻击力<attack> {0} </>点(攻击力增加上限：+<uadd>[</><attack> {1} </><uadd>]</>点)，攻击后重置其攻击力.",
    "e_generic_pendulum": "当本卡牌位于手牌中时，若即将受到 <img id=\"\"player_health\"\"/> 角色生命值伤害，则将本卡牌放置到己方场地上并降低受到的 <img id=\"\"player_health\"\"/> 角色生命值伤害至<key> 1 </><img id=\"\"player_health\"\"/>，然后延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合. 此后在本回合内，将场地上所有己方卡牌受到的伤害降低至<key> 0 </>点 (但不会降低受到的其他 <img id=\"\"player_health\"\"/> 角色生命值伤害).",
    "e_generic_pureheart": "当手牌中卡牌数目为<key> 0 </>时，抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_generic_pureheart_condition": "当手牌中只有本卡牌时，解除限制.",
    "e_generic_reincarnation": "选择弃牌堆中的一张卡牌，将其返还到手牌中(除了 <key>循环</> ).",
    "e_generic_ambush_play": "对<cover>被掩护的</>所有对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害并延迟其行动<uadd>[</><key> {1} </><uadd>]</>回合.",
    "e_generic_rupture": "选择场地上一张卡牌并对其造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后对另一方场地上的所有卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_scalpel": "本卡牌攻击时，若抽牌堆有卡牌且目标卡牌生命值不高于<uadd>[</><health> {0} </><uadd>]</>点，则<decompile>反编译</>目标与本卡牌，并将抽牌堆顶端的卡牌放置到本卡牌所在的位置(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_generic_shatter": "选择场地上一张己方卡牌，对所有对方卡牌造成等同于所选卡牌的生命值的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>，然后对所选卡牌造成等同于其<health>最大生命值</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>.",
    "e_generic_shatter_upgrade": "选择场地上<uadd>[</>至多两张<uadd>]</>己方卡牌，并对所有对方卡牌造成等同于所选卡牌的<health>生命值总和</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>，然后对所选卡牌各自造成等同于其<health>最大生命值</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>.",
    "e_generic_solarflare": "对前方一张对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_generic_spark": "选择场地上一张未激活的己方卡牌，重新激活所选卡牌(除了 <key>火花</> ).",
    "e_generic_taser": "当本卡牌造成 <img id=\"\"dmg_phys\"\"/> 物理伤害时，延迟目标卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合. 若目标抵抗了延迟，则对其造成<uadd>[</><key> {1} </><uadd>]</>次<magic> 1 </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_taunt": "将所有卡牌的倒计时推进 {0} 个回合，此后在本回合中<img id=\"\"player_health\"\"/> 角色生命值伤害降低至 <key>0</>.",
    "e_generic_thunderclap": "延迟本卡牌前方的一张对方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合，然后将一张 <key>闪光</> 卡牌添加到抽牌堆顶端并将回合抽牌倒计时设置为<key> 0 </>点.",
    "e_generic_treasure": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌并将抽牌倒计时设置为<key> {1} </>点.",
    "e_generic_updraft": "选择场地上一张己方卡牌，将其返还到手牌中(除了 <key>上升涡流</> ).",
    "e_infinitenavigation": "当本卡牌被放置到场地上时，选择一条新的路线并打开卡组编辑器. 当本卡牌被从场地上移除时，路线开始.",
    "e_mage_aurelia_add": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其返还到手牌中.",
    "e_mage_aurelia_hand": "选择手牌中一张己方卡牌，抽取一张卡牌，然后将所选择的卡牌洗入抽牌堆.",
    "e_mage_camilla": "选择场地上攻击为<attack> 0 </>且至少有一个 <img id=\"\"effect_init\"\"/> 初始化效果的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的一张己方卡牌，将其移除到弃牌堆中. 然后将其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果添加到本卡牌上，并将其设置为 <img id=\"\"effect_manual\"\"/> 指令式模块效果(附带 <img id=\"\"effect_once\"\"/> 一次性和 <img id=\"\"effect_gunique\"\"/> 高级特有模块).",
    "e_mage_decima_condition": "当弃牌堆中恰好有<key> {0} </>张 <key>.sorc</> 卡牌时，解除限制.",
    "e_mage_decima_init": "丢弃手牌中所有卡牌，每丢弃一张卡牌，本卡牌获得<key> 1 </>个计数点，然后将弃牌堆中所有该效果发动前就存在的 <key>.sorc</> 卡牌返还到手牌中.",
    "e_mage_decima_trigger": "当本卡牌拥有计数点时，若你放置一张攻击力为<attack> 0 </>点的卡牌，则消耗<key> 1 </>个计数点并增加手牌中攻击力为<attack> 0 </>点的所有卡牌<health> 1 </>点生命值，然后抽取一张卡牌.",
    "e_mage_lucia_discard": "丢弃手牌中的一张卡牌，并对前方的一张对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mage_lucia_search": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其添加到手牌中.",
    "e_mage_mariana_ability": "当本卡牌前方有一张等级不高于<uadd>[</><key> {1} </><uadd>]</>级的己方卡牌时，将那张卡牌洗入抽牌堆中并增加前排所有己方卡牌的生命值<health> {0} </>点(该效果不可叠加).",
    "e_mage_mariana_init": "将本卡牌左右两侧的卡牌返还到手牌中.",
    "e_mage_mariana_movement": "当本卡牌移动到场地上其他位置时，刷新本卡牌所有 <img id=\"\"effect_once\"\"/> 一次性效果.",
    "e_mage_mariana_movement_upgrade": "当本卡牌移动到场地上其他位置时，刷新本卡牌所有 <img id=\"\"effect_once\"\"/> 一次性效果<uadd>[</>并重新激活本卡牌<uadd>]</>.",
    "e_mage_octavia_ability": "当本卡牌前方有一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的己方卡牌时，触发其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果(无视其限制)并将那张卡牌洗入抽牌堆中.",
    "e_mage_octavia_init": "选择手牌中一张己方卡牌，增加其生命值<health> 1 </>点.",
    "e_mage_sharedadder": "当本卡牌以抽取以外方式添加至手牌中时，增加其<uminus>[</><health> 1 </>点<uminus>]</><health>最大生命值</>(最大生命值上限：<uadd>[</><health> {0} </><uadd>]</>点).",
    "e_mage_sharedadder_upgrade": "当本卡牌以抽取以外方式添加至手牌中时，其<health>最大生命值</>提高至<uadd>[</><key> 2 </>倍<uadd>]</>(最大生命值上限：<uadd>[</><health> {0} </><uadd>]</>点).",
    "e_mage_sorccreo": "根据场地上与本卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，抽取<key> X </>张卡牌. 然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前抽取卡牌数目：<key> {0} </>张).",
    "e_mage_sorceffingo": "选择弃牌堆中至少有一个 <img id=\"\"effect_init\"\"/> 初始化效果的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的一张 <key>.sorc</> 卡牌(除了 <key>复刻.sorc</> )，将其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果作为本卡牌的效果触发(无视其限制)并其洗入抽牌堆中，然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点.",
    "e_mage_sorcgravitas": "根据场地上与本卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，对所有对方卡牌造成<magic> X </><uminus>[</><magic>- {1} </><uminus>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害. 然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_mage_sorcgravitas_upgrade": "根据场地上本卡牌的所有同名卡的<health>生命值总和</>(<key> X </>点)，对所有对方卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/> 魔法伤害. 然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_mage_sorcignis": "根据场地上与本卡牌同名的所有卡牌的<health>生命值总和</>( <key>X</> 点)，对前方一张对方卡牌造成 <uadd>[</><magic>{0}X</> <img id=\"\"dmg_magic\"\"/><uadd>]</> 点 <magic>魔法伤害</> ，然后将场地上与本卡牌同名的所有卡牌的 <health>最大生命值</> 设置为 <health>1</> 点. (当前魔法伤害 = <magic>{1}</><img id=\"\"dmg_magic\"\"/>)",
    "e_mage_sorclux": "根据场地上与本卡牌同名的所有卡牌的<health>生命值总和</>( <key>X</> 点)，选择弃牌堆中至多<key> X </>张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mage</> 卡牌，将其返还到手牌中. 然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前返还的卡牌数目：<key> {1} </>张).",
    "e_mage_sorcpotentia": "重新激活本卡牌所在行的所有卡牌. 并根据场地上与本卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，令本卡牌所在行上所有卡牌获得一个<key> X </><attack>+ {0} </>点的<specialbuff>衰减性的攻击力增益</>(攻击力增加上限：+<attack> {2} </>点). 然后将场地上与本卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前攻击力增加量：+<attack> {1} </>点).",
    "e_mage_sorctempus": "根据场地上与本卡牌同名的所有卡牌的 <health>生命值总和</> ( <key>X</> 点)，延迟所有敌人的行动 <uadd>[</><key>{0}</><uadd>]</> + <key>X</> 回合. 然后将场地上与本卡牌同名的所有卡牌的 <health>最大生命值</> 设置为 <health>1</> 点. (当前延迟: <key>{1}</> 回合)",
    "e_mage_sorctempus_upgrade": "根据场地上与本卡牌同名的所有卡牌的 <health>生命值总和</> ( <key>X</> 点)，延迟所有敌人的行动 <uadd>[</><key>{0}</><uadd>]</><key>X</> 回合. 然后将场地上与本卡牌同名的所有卡牌的 <health>最大生命值</> 设置为 <health>1</> 点. (当前延迟: <key>{1}</> 回合)",
    "e_mage_valeria_attack": "当本卡牌攻击时，触发其左右两侧等级不低于<key> 1 </>级的卡牌最左边的 <img id=\"\"effect_init\"\"/> 初始化效果(无视其限制).",
    "e_mage_valeria_condition": "丢弃手牌中的<key> {0} </>张卡牌，解除限制.",
    "e_mage_valeria_init": "选择抽牌堆中至多两张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其放置到己方场地上.",
    "e_mdv_advancedsummon_plural": "当一次操作中恰好有<key> {0} </>张己方卡牌被摧毁时，解除限制直至下次操作开始为止.",
    "e_mdv_advancedsummon": "当一次操作中恰好有<key> {0} </>张己方卡牌被摧毁时，解除限制直至下次操作开始为止.",
    "e_mdv_axe_init": "对前方一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_mdv_axe_passive": "本卡牌获得<uadd>[</><key> {0} </><uadd>]</>倍的攻击力增长，且本卡牌攻击后，重置其攻击力. 当本卡牌的攻击力将超过<uadd>[</><attack> {1} </><uadd>]</>点时，此次攻击力增长无效并对场地上其他的所有卡牌造成<physical> {2} </>点物理伤害.",
    "e_mdv_axe": "当本卡牌的攻击力低于<uadd>[</><attack> {1} </><uadd>]</>点时，增加其攻击力<attack> {0} </>点.",
    "e_mdv_core_init": "选择场地上一张己方的 <key>.mech</> 卡牌，增加其攻击力<uadd>[</><attack> {0} </><uadd>]</>点并对其造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_core": "选择场地上一张卡牌，对其造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_gatling_init": "本卡牌获得<uadd>[</><key> {0} </><uadd>]</>个计数点.",
    "e_mdv_gatling_passive": "当场地上一张己方卡牌被摧毁时，本卡牌获得<uadd>[</><key> {0} </><uadd>]</>个计数点(最大计数点个数：<uadd>[</><key> {1} </><uadd>]</>).",
    "e_mdv_gatling": "消耗本卡牌所有的计数点. 每消耗<key> 1 </>个计数点，本卡牌发动一次攻击(当前攻击次数：<key> {0} </>次).",
    "e_mdv_hammer_init": "对场地上其他的所有卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_mdv_hammer": "对场地上生命值不高于本卡牌攻击力的所有卡牌造成等同于本卡牌攻击力的 <img id=\"\"dmg_phys\"\"/> 物理伤害(包括本卡牌).",
    "e_mdv_hydro_init": "丢弃抽牌堆顶端的卡牌，然后选择弃牌堆顶端的<uadd>[</><key> {0} </><uadd>]</>张卡牌中至多两张<key> {1} </>级的 <key>.mech</> 卡牌，将其放置到场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_mdv_hydro": "选择场地上的一张己方卡牌，将其返还到手牌中.",
    "e_mdv_plasma_blast": "当场地上一张卡牌被摧毁时，本卡牌获得<key> 1 </>个计数点. 当本卡牌的计数点不低于<key> {0} </>个时，消耗所有的计数点并对本卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_plasma": "对本卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_podeffect": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级且至少有<key> 1 </>点攻击力的 <key>.mech</> 卡牌，摧毁本卡牌并将所选卡牌放置到本卡牌所在的位置，然后对其他所有卡牌造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_mdv_rocket": "当本卡牌位于手牌中时，若场地上一张己方卡牌被摧毁，本卡牌获得<key> 1 </>个计数点(最大计数点个数：<key> {0} </>个).",
    "e_mdv_rocketdamage": "当本卡牌被放置到场地上时，消耗<key> 1 </>个计数点并对所有对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害. 重复该效果直到耗尽所有的计数点(当前物理伤害：<physical> {0} x {1} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mdv_signal": "当己方卡牌受到来自己方卡牌的伤害时，将该伤害降低至<key> 0 </>点并重新激活受到伤害的卡牌(除了 <key>作战指挥塔</> ).",
    "e_mdv_signal_upgrade": "当己方卡牌受到来自己方卡牌的伤害时，将该伤害降低至<key> 0 </>点(除了 <key>作战指挥塔</> )并<uadd>[</>根据受到的伤害量等量治疗受到伤害的卡牌，然后<uadd>]</>重新激活受到伤害的卡牌.",
    "e_mdv_spear_init": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mech</> 卡牌，将其添加到手牌中(除了  <key>枪式-SP型.mech</> ).",
    "e_mdv_sword_init": "对前方一张对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_mdv_sword": "发动两次攻击，每次攻击造成与本卡牌的攻击力的一半(向下取整)等量的物理伤害(当前伤害：<physical> {0} x 2 </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mdv_thunder_init": "对所有对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_thunder": "选择场地上一张卡牌并对其造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_unity_condition": "当场地上恰好有<key> {0} </>张己方的 <key>.mech</> 卡牌时，解除限制(当前场地上己方 <key>.mech</> 卡牌数目/所需的 <key>.mech</> 卡牌数目：{1}/{0}).",
    "e_mdv_unity": "触发场地上所有己方卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_muse_bass_group": "与本卡牌并列执行的其他卡牌将首先根据其各自的生命值等量增加其各自的攻击力.",
    "e_muse_bass": "若卡牌被放置到本卡牌的所在行，那张卡牌增加其生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_muse_doubleeigth": "发动两次攻击，每次攻击造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_muse_equalize": "丢弃手牌中一张卡牌，抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_executemanualshared": "选择场地上的一张己方卡牌，将其执行并抽取一张卡牌.",
    "e_muse_fermata": "与本卡牌并列执行的卡牌将被保留在场地上(除了 <key>延长音.muse</> ).",
    "e_muse_forte": "增加本卡牌所在行上所有 <key>.muse</> 卡牌的攻击力<uadd>[</><key> {0} </><uadd>]</>点.",
    "e_muse_idol1_init": "选择弃牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol1_init_upgrade": "选择弃牌堆中一张<uadd>[</>不高于<key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol2_init": "选择抽牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol2_init_upgrade": "选择抽牌堆中一张<uadd>[</>不高于<key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol2": "选择场地上的一张己方卡牌，将其执行并抽取一张卡牌.",
    "e_muse_idol3_init": "丢弃手牌中所有<key> 1 </>级的 <key>.muse</> 卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_muse_idol3_manual": "选择弃牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到己方场地上并令其效果附带 <img id=\"\"effect_once\"\"/> 一次性.",
    "e_muse_idol3_manual_upgrade": "选择弃牌堆中一张<uadd>[</>不高于<key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到己方场地上并令其效果附带 <img id=\"\"effect_once\"\"/> 一次性.",
    "e_muse_idol4_init": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_idol4": "选择手牌中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol4_upgrade": "选择手牌中一张<uadd>[</>不高于<key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到己方场地上.",
    "e_muse_idol5_passive": "每抽取一张卡牌，便增加本卡牌的攻击力<uadd>[</><attack> {1} </><uadd>]</>点(当前攻击力增加量：+<attack> {2} </>点)(攻击力增加上限：+<uadd>[</><attack> {0} </><uadd>]</>点)，攻击后重置本卡牌攻击力.",
    "e_muse_idol5": "并列执行本卡牌左右两侧的卡牌. 每执行一张卡牌抽取 {0} 张卡牌.",
    "e_muse_idolboss_condition": "丢弃手牌中一张卡牌，解除限制.",
    "e_muse_idolboss_init": "场地上所有己方卡牌获得<key> 1 </>个计数点.",
    "e_muse_idolboss_passive": "当拥有计数点的卡牌被执行时，消耗<key> 1 </>计数点并保留被执行的卡牌.",
    "e_muse_piano": "增加所有己方卡牌<uadd>[</><health> {0} </><uadd>]</>点<health>最大生命值</>.",
    "e_muse_quarter": "对前方一张对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_muse_quarterrest": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_treble_group": "与其他卡牌并列执行时，首先根据其他卡牌的数目抽取等量的卡牌.",
    "e_muse_treble": "若卡牌被放置到本卡牌的所在行，那张卡牌增加其攻击力<uadd>[</><attack> {0} </><uadd>]</>点.",
    "e_muse_triplet": "对所有对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_natural_apple": "将抽牌堆中<key> 1 </>张与本卡牌同名的卡牌添加到手牌中.",
    "e_natural_apple_upgrade": "将抽牌堆至多<uadd>[</><key> 2 </><uadd>]</>张与本卡牌同名的卡牌添加到手牌中.",
    "e_natural_banana": "选择弃牌堆中一张<key> 1 </>级的<uminus>[</> <key>.fruit</> <uminus>]</>卡牌，将其放置到己方场地上(不包括与本卡牌同名的卡牌).",
    "e_natural_banana_upgrade": "选择弃牌堆中一张<key> 1 </>级的卡牌，将其放置到己方场地上(不包括与本卡牌同名的卡牌).",
    "e_natural_cherry": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_natural_demeter_condition": "当弃牌堆中至少有<key> {0} </>张同名的<key> 1 </>级 <key>.fruit</> 卡牌时，解除限制(当前弃牌堆中同名的 <key>.fruit</> 卡牌数目/需要的 <key>.fruit</> 卡牌数目：{1}/{0}).",
    "e_natural_demeter_trigger": "当手牌中一张卡牌被放置到己方场地上时，本卡牌对前方一张对方卡牌造成等同于本卡牌攻击力的魔法伤害.",
    "e_natural_demeter": "选择弃牌堆中的一张<key> 1 </>级卡牌，将弃牌堆中与所选卡牌同名的所有卡牌添加到手牌中.",
    "e_natural_fall": "移除场地上所有<key> 1 </>级 <key>.fruit</> 卡牌上的效果. 每移除一张卡牌的效果便抽取一张卡牌.",
    "e_natural_fall_upgrade": "移除场地上所有<key> 1 </>级 <key>.fruit</> 卡牌上的效果. 每移除一张卡牌的效果便抽取一张卡牌<uadd>[</>并增加被移除效果的卡牌的攻击力<attack> 1 </>点<uadd>]</>.",
    "e_natural_greenhouse": "当一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌被放置到本卡牌的后排位置时，将弃牌堆中与那张卡牌同名的一张卡牌返还到手牌中(除了 <key>温室</> ).",
    "e_natural_growth": "选择弃牌堆中一张<uminus>[</> <key>.fruit</> <uminus>]</>卡牌，将弃牌堆中与所选卡牌同名的所有卡牌洗入抽牌堆并根据洗入抽牌堆的卡牌数目抽取等量的卡牌.",
    "e_natural_growth_upgrade": "选择弃牌堆中的一张卡牌，将弃牌堆中与所选卡牌同名的所有卡牌洗入抽牌堆并根据洗入抽牌堆的卡牌数目抽取等量的卡牌.",
    "e_natural_lemon": "场地上与本卡牌同名的所有己方卡牌发动一次攻击.",
    "e_natural_persephone_condition": "当场地上至少有<key> 3 </>张不同名的己方的<key> 1 </>级 <key>.fruit</> 卡牌时，解除限制(当前己方场地上不同名的卡牌数目/所需的不同名的卡牌数目：{1}/{0}).",
    "e_natural_persephone_init": "<void>放逐</>场地上其他所有己方卡牌. 此后若本卡牌还在场上，每<void>放逐</>一张卡牌，增加本卡牌<attack> 2 </>点攻击力.",
    "e_natural_persephone_passive": "本卡牌攻击后，降低本卡牌的攻击力 {0} 点并对所有对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_natural_pollination": "丢弃抽牌堆中至少有一个效果的一张<key> 1 </>级 <key>.fruit</> 卡牌，将其最左边的效果添加到手牌中所有<key> 1 </>级<uminus>[</> <key>.fruit</> <uminus>]</>卡牌上(每张卡所拥有的效果不能超过<key> 3 </>个)(附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_natural_pollination_upgrade": "丢弃抽牌堆中至少有一个效果的一张<key> 1 </>级 <key>.fruit</> 卡牌，将其最左边的效果添加到手牌中所有<key> 1 </>级卡牌上(每张卡所拥有的效果不能超过<key> 3 </>个)(附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_natural_pomegranate": "当本卡牌进入弃牌堆中时，对所有对方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_natural_pomegranate_upgrade": "当本卡牌进入弃牌堆中时，对所有<expose>暴露的</>对方卡牌造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害并对所有<cover>被掩护的</>对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害<uadd>]</>.",
    "e_natural_pumpkin_trigger": "本卡牌攻击后，摧毁本卡牌.",
    "e_natural_pumpkin": "增加场地上与本卡牌同名的所有卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_natural_spring": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.fruit</> 卡牌(除了 <key>春.fruit</> )，将一张所选卡牌的复制品放置到己方场地上. 弃牌堆中每有一张与所选卡牌同名的卡牌，增加复制品的攻击力<attack> 1 </>点(攻击力增加上限：+<attack> {1} </>点).",
    "e_natural_summer": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.fruit</> 卡牌，将其添加到手牌中(除了 <key>夏.fruit</> ).",
    "e_natural_winter": "选择抽牌堆中一张 <key>.fruit</> 卡牌(除了 <key>冬.fruit</> )，丢弃抽牌堆中与所选卡牌同名的所有卡牌. 每丢弃一张卡牌，便治疗场地上所有己方卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_potionhealth": "治疗<uadd>[</><health> {0} </><uadd>]</><img id=\"\"player_health\"\"/> 角色生命值.",
    "e_potionstorage": "增加卡牌存储空间<uadd>[</><key> {0} </><uadd>]</>格(最多增加的空间格数：+<key> {1} </>格)(当前增加的空间格数：+<key> {2} </>格).",
    "e_potionvoid": "<void>放逐</>场地上等级不高于<key> {0} </>级的所有对方卡牌.",
    "e_sakura_bow": "发动一次攻击，该次攻击造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_sakura_katana": "本卡牌发动一次攻击.",
    "e_sakura_kunai": "对所有对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_sakura_lantern": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.hana</> 卡牌，将其添加到手牌中(除了  <key>提灯.hana</> ).",
    "e_sakura_ninja1": "触发本卡牌同列后方的一张 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja2": "选择手牌中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.hana</> 卡牌，将其放置到己方场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_sakura_ninja3_adder": "当本卡牌以抽取以外方式添加到手牌中时，将其放置到己方场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_sakura_ninja3_condition": "丢弃一张卡牌，解除限制.",
    "e_sakura_ninja3": "选择弃牌堆中恰好拥有一个 <img id=\"\"effect_manual\"\"/> 指令式模块或者 <img id=\"\"effect_init\"\"/> 初始化效果的一张<key> 1 </>级卡牌，将其效果作为本卡牌的初始化效果触发(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja3_upgrade": "选择弃牌堆中恰好拥有一个 <img id=\"\"effect_manual\"\"/> 指令式模块或者 <img id=\"\"effect_init\"\"/> 初始化效果的一张<key> 1 </>级卡牌，将其效果设置为本卡牌的初始化效果触发<uadd>[</>两次<uadd>]</>(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja4": "将本卡牌左右两侧的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块效果添加到本卡牌上(若目标有多个指令式模块，则只能获得一个).",
    "e_sakura_ninjaboss_condition": "<decompile>反编译</>场地上一张己方的 <key>绽樱.hana</> 卡牌和一张己方的<key> 2 </>级的 <key>.hana</> 卡牌，解除限制.",
    "e_sakura_ninjaboss": "触发本卡牌左右两侧的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_priestess_condition": "当己方场地上恰好有<key> {0} </>个已触发的 <img id=\"\"effect_once\"\"/> 一次性的 <img id=\"\"effect_manual\"\"/> 指令式模块，解除限制.",
    "e_sakura_priestess": "刷新场上所有己方卡牌的 <img id=\"\"effect_once\"\"/> 一次性效果并激活那些卡牌，然后延迟所有对方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_sakura_shide": "选择场地上一张己方的 <key>.hana</> 卡牌(除了 <key>御币.hana</> )，将其返还到手牌中并刷新其 <img id=\"\"effect_once\"\"/> 一次性效果. <uminus>[</>若刷新了一个 <img id=\"\"effect_once\"\"/> 一次性效果，<uminus>]</>抽取一张卡牌.",
    "e_sakura_shide_upgrade": "选择场地上一张己方的 <key>.hana</> 卡牌(除了 <key>御币.hana</> )，将其返还到手牌中并刷新其 <img id=\"\"effect_once\"\"/> 一次性效果. 若返还了一张卡牌，抽取一张卡牌.",
    "e_sakura_storm": "触发场地上<uminus>[</>本卡牌所在行的<uminus>]</>己方的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_storm_upgrade": "触发场地上所有己方的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 指令式模块效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_torii_condition": "<decompile>反编译</>场地上一张己方的 <key>.hana</> 卡牌，解除限制.",
    "e_sakura_torii": "当本卡牌后方的一张卡牌越过本卡牌攻击时，将该攻击伤害提升至<uadd>[</><key> {0} </><uadd>]</>倍. ",
    "e_spdeckedit_manual": "将本卡牌从弃牌堆中洗入抽牌堆中.",
    "e_spdeckedit": "打开卡组编辑器；完成编辑后，<key>重新加载</>所有卡牌(无等级卡不能成为以等级为条件触发的效果的目标).",
    "e_spdeckreload": "<key>重新加载</>所有卡牌(将己方抽牌堆、弃牌堆、场上和手牌中的所有卡牌移除，然后依卡组构筑获得新的抽牌堆，抽取新的手牌).",
    "e_spinstantdraft": "打开带有大量<img id=\"\"loot\"\"/>的卡组编辑器，编辑后<key>重新加载</>所有卡牌.",
    "e_spirit_amaterasu1": "当你触发<key>回合抽牌</>时，将场地上、手牌中和弃牌堆中其他所有的己方卡牌洗入抽牌堆中，然后抽取<key> {0} </>张卡牌并延迟所有对方卡牌的行动<key> {1} </>回合.",
    "e_spirit_amaterasucondition": "当手牌中、抽牌堆、弃牌堆和场上的所有己方卡牌数目总和恰好为<key> {0} </>时，解除限制.",
    "e_spirit_amaterasuappear": "根据弃牌堆中不同名卡牌的数目( <key>X</> 张)，对所有对方卡牌造成 <key>X</> 点 <img id=\"\"dmg_magic\"\"/> 魔法伤害(当前  <key>X</>=<magic>{0}</>)(最大值: <key>{1}</>). 然后将弃牌堆中的卡牌洗入抽牌堆中.",
    "e_spirit_bounce": "当触发 <key>回合抽牌</> 时，将本卡牌返还到手牌中.",
    "e_spirit_swarm": "若本卡牌不和任何卡牌相邻(不包括对角线)，将弃牌堆中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.spirit</> 卡牌放置到本卡牌相邻的位置(不包括对角线).",
    "e_spirit_bouncecondition": "当恰好 <key>{0}</> 张卡牌在同一次操作中被返还到手牌中之后，解除限制直至下次操作开始为止.",
    "e_spirit_countcondition": "当手牌和场地上的卡牌总数恰好为 <key>{0}</> 张时，解除限制(目前卡牌总数: {1}/{0}).",
    "e_spirit_kitsunehand": "[手牌中]:{b}丢弃本卡牌. 对所有 <expose>暴露的</> 对方卡牌造成 <uadd>[</><magic>{handDmg}</><img id=\"\"dmg_magic\"\"/><uadd>]</>.{b}",
    "e_spirit_kitsunefield": "[场地上]:{b}选择一张对方卡牌，根据所有与本卡牌<pathed> 连通的 </><key>.spirit</> 卡牌的攻击力之和(<key>X</>点)，对那张卡牌造成 <magic>X</><img id=\"\"dmg_magic\"\"/> 魔法伤害(当前伤害: <magic>{currentFieldDmg}</><img id=\"\"dmg_magic\"\"/>)(最大值: <uadd>[</><key>{maxDmg}</><uadd>]</>)，然后将那些<pathed> 连通的 </>卡牌的 <attack>攻击力</> 减少 <attack>1</> 点.",
    "e_spirit_tsuruhand": "[手牌中]:{b}丢弃本卡牌. 强化场地上所有初始攻击力不低于 <attack>1</> 点的 <key>.spirit</> 卡牌的攻击力(  <uadd>[</><attack>+{handBuff}</><uadd>]</> 点)(最大值 <uadd>[</><key>+{handBuff}</><uadd>]</>).{b}",
    "e_spirit_tsurufield": "[场地上]:{b}令所有与本卡牌<pathed> 连通的 </> <key>.spirit</> 卡牌发动一次攻击，然后将那些卡牌的 <attack>攻击力</> 降低  <attack>1</> 点.",
    "e_spirit_kusanagiinit": "强化所有相邻的卡牌(不包括对角线)的攻击力( <uadd>[</><attack>+{0}</><uadd>]</> 点)(最大值: <uadd>[</><key>+{0}</><uadd>]</>).",
    "e_spirit_kusanagireaction": "当一张卡牌以抽取以外方式添加至手牌中时，本卡牌将获得一个 <uadd>[</><attack>+{0}</><uadd>]</> 点的 <specialbuff>一次性的攻击力增益</> (最大值: <uadd>[</><attack>+{1}</><uadd>]</> 点).",
    "e_spirit_magatamainit": "将抽牌堆中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.spirit</> 卡牌添加到手牌中.",
    "e_spirit_magatamatrigger": "当一张卡牌以抽取以外方式添加至手牌中时，本卡牌将获得 <key>{0}</> 个计数点(最大值: <uadd>[</><key>{1}</><uadd>]</> 个).",
    "e_spirit_magatamadefense": "当本卡牌有 <key>计数点</> 时，将优先消耗本卡牌持有的 <key>计数点</> 来抵消己方卡牌所受的伤害. 若场上有多张可抵消伤害的 <key>八尺琼勾玉.spirit</> 存在，它们将依次抵消伤害.",
    "e_spirit_yatainit": "选择一张手牌中等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.spirit</> 卡牌(除了 <key>八咫镜.spirit</>)，在弃牌堆中生成一张 <key>复制品</> .",
    "e_spirit_yatatrigger": "当一张卡牌以抽取以外方式添加至手牌中时且本卡牌处于 <key>激活</> 状态时，将手牌中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.spirit</> 卡牌放置到场地上，然后将本卡牌设置为未激活状态.",
    "e_spirit_nekohand": "[手牌中]:{b}丢弃本卡牌与手牌中的一张 <key>.spirit</> 卡牌(除了 <key>玉猫.spirit</>)，然后抽取 <uadd>[</><key>{draw}</><uadd>]</> 张卡牌.{b}",
    "e_spirit_nekofield": "[场地上]:{b}根据所有与本卡牌<pathed> 连通的 </><key>.spirit</> 卡牌的攻击力之和(<key>X</>点)，抽取 <key>X</> 张卡牌(当前抽取量: <key>{fieldDraw}</> 张)(最大值: <uadd>[</><key>{fieldDrawMax}</><uadd>]</>)，然后将那些<pathed> 连通的 </>卡牌的 <attack>攻击力</> 减少 <attack>1</> 点.",
    "e_spirit_nezumitrigger": "当一张 <key>.spirit</> 卡牌(除了 <key>福鼠.spirit</> )触发了一个 <img id=\"\"effect_manual\"\"/> 或 <img id=\"\"effect_init\"\"/> 时:",
    "e_spirit_nezumihand": "{b}[手牌中]:{b}将本卡牌放置到场地上.{b}",
    "e_spirit_nezumifield": "[场地上]:{b}本卡牌发动一次攻击，然后其 <attack>攻击力</> 降低 <attack>1</> 点.",
    "e_spirit_sikahand": "[手牌中]:{b}丢弃本卡牌，然后选择一张场地上至少有一个 <img id=\"\"effect_manual\"\"/>  效果的 <key>{lvTarget}</> 级 <key>.spirit</> 卡牌，触发其所有的 <img id=\"\"effect_manual\"\"/> 效果(无视 <img id=\"\"effect_once\"\"/> 限制).{b}",
    "e_spirit_sikafield": "[场地上]:{b}根据所有与本卡牌<pathed> 连通的 </><key>.spirit</> 卡牌的攻击力之和(<key>X</>点)，延迟所有对方卡牌 <key>X</> 回合(当前延迟: <key>{currentDelay}</> 回合)(最大值: <uadd>[</><key>{maxDelay}</><uadd>]</>)，然后将那些<pathed> 连通的 </>卡牌的 <attack>攻击力</> 减少 <attack>1</> 点.",
    "e_spirit_tanzakuinit": "触发与本卡牌相邻的所有 <key>{0}</> 级 <key>.spirit</> 卡牌的 <img id=\"\"effect_manual\"\"/> 效果(不包括对角线) (无视 <img id=\"\"effect_once\"\"/> 限制).",
    "e_spirit_tsukuyomibuff": "己方场地上放置一张卡牌时，若本卡牌拥有 <key>{0}</> 个计数点，则消耗所有计数点并触发被放置的卡牌的 <img id=\"\"effect_manual\"\"/> 效果， 然后令那张卡牌的 <key>攻击力</> 增加 <attack>{1}</> 点；反之，则获得一个计数点.",
    "e_spirit_watatsumihand": "[手牌中]:{b}丢弃本卡牌并令己方场地上所有卡牌的数值恢复到初始状态.{b}",
    "e_spirit_watatsumifield": "[场地上]:{b}将所有的手牌洗入抽牌堆. 每洗入一张卡牌便强化一次本卡牌的攻击力和生命值( <attack>+1</>|<health>+1</> )(当前强化: <attack>+{buffAmt}</>|<health>+{buffAmt}</>)(最大强化: <uadd>[</><attack>+{max}</>|<health>+{max}</><uadd>]</>)，然后抽取 <uadd>[</><key>{redraw}</><uadd>]</> 张卡牌.",
    "e_spirit_yamatahand": "[手牌中]:{b}丢弃本卡牌并对所有的对方卡牌造成 <uadd>[</><magic>{handDmg}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 点魔法伤害.{b}",
    "e_spirit_yamatafield": "[场地上]:{b}将所有的手牌洗入抽牌堆. 每洗入一张卡牌便对所有 <expose>暴露的</>  对方卡牌造成 <magic>1</> <img id=\"\"dmg_magic\"\"/> 点彼此累加的魔法伤害(当前伤害: <magic>{fieldDmg}</> <img id=\"\"dmg_magic\"\"/>)，然后抽取 <uadd>[</><key>{redraw}</><uadd>]</> 张卡牌.",
    "e_spirit_dragoncondition": "将场地上两张 <key>未激活的</> 且攻击力为 <key>0</> 的 <key>.spirit</> 卡牌返还到手牌中，然后解除限制.",
    "e_spirit_dragonbounce": "当你触发 <key>回合抽牌</> 时，若手牌中有等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.spirit</> 卡牌，则选择一张放置到场地上，然后将本卡牌洗入抽牌堆中；反之，则该效果无效.",
    "e_spstoragehit": "选择 <key>存储空间</> 中的一张卡牌，将其添加到手牌中；若 <key>存储空间</> 中没有卡牌，则抽取<key> 2 </>张卡牌(无等级卡不能成为以等级为条件触发的效果的目标).",
    "e_vamp_gen1_condition": "当场地上恰好拥有<key> {0} </>张攻击力相同的己方卡牌时，解除限制.",
    "e_vamp_gen1_init": "令场地上攻击力不低于<attack> 1 </>点的所有己方卡牌发动一次攻击，并将其他卡牌返还到手牌中.",
    "e_vamp_gen1_manual": "选择场地上的一张己方卡牌，若其攻击力不低于<attack> 1 </>点，则所选卡牌发动一次攻击，否则，将其返还到手牌中.",
    "e_vamp_gen2_condition": "当弃牌堆中恰好有<key> {0} </>张 <key>.blood</> 卡牌时，解除限制(当前弃牌堆中 <key>.blood</> 卡牌数目/需要的 <key>.blood</> 卡牌数目：{1}/{0}).",
    "e_vamp_gen2_groupattack": "令场地上生命值为<health> 1 </>点的所有己方卡牌发动一次攻击.",
    "e_vamp_gen2_manual": "选择弃牌堆中一张 <key>.blood</> 卡牌，将其<void>放逐</>并在场地上放置一个数值为<uadd>[</><attack>{0}</><uadd>]</>|<health>1</>的随从，然后重新激活本卡牌.",
    "e_vamp_hyper": "根据场地上所有己方卡牌的数目，对所有对方卡牌造成等量的魔法伤害(最大魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> )(当前魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> )，然后对场地上所有己方卡牌造成<magic> 1 </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_vamp_lieu1": "根据本卡牌攻击力的一半(<key> X </>点)(向下取整)，选择抽牌堆中至多<key> X </>张等级不高于<key> {0} </>级的 <key>.legion</> 卡牌，将其添加到手牌中(当前添加的卡牌总数：<key> {1} </>张)，然后移除本卡牌所有的数值调整.",
    "e_vamp_lieu2": "根据本卡牌攻击力的一半(<key> X </>点)(向下取整)，选择抽牌堆中至多<key> X </>张等级不高于<key> {0} </>级的 <key>.blood</> 卡牌，将其添加到手牌中(当前添加的卡牌总数：<key> {1} </>张)，然后移除本卡牌所有的数值调整.",
    "e_vamp_lifesteal": "当本卡牌造成伤害时，治疗本卡牌的生命值<health> {0} </>点并增加其攻击力<attack> 1 </>点(攻击力增加上限：+<attack> {1} </>点). 当本卡牌受到伤害时，减少本卡牌的攻击力<attack> 1 </>点.",
    "e_vamp_orb_destruction": "抽取<key> 1 </>张卡牌.",
    "e_vamp_orb": "选择手牌中一张<uadd>[</><key> {0} </><uadd>]</>级以下的 <key>.legion</> 卡牌，将其放置到己方场地上.",
    "e_vamp_origin": "己方场地上生命值为<health> 1 </>点的卡牌数目为<key> X </>. 选择弃牌堆中至多<key> X </>张不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.blood</> 卡牌(除了  <key>血祭.blood</> )(当前可选择的卡牌数目：<key> {1} </>张)，将其添加到手牌中，然后<decompile>反编译</>所有生命值为<health> 1 </>点的己方卡牌.",
    "e_vamp_plunge_trigger": "当本卡牌位于手牌中时，若其一回合后仍未被放置到己方场地上，则丢弃本卡牌.",
    "e_vamp_plunge": "选择场地上生命值为<health> {0} </>点的一张卡牌(除了 <key>血雨.blood</> )，将其摧毁并对场地上与被摧毁的卡牌同侧的所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后将本卡牌返还到手牌中.",
    "e_vamp_revival": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.legion</> 卡牌，将其放置到己方场地上.",
    "e_vamp_shield_revive": "当本卡牌位于弃牌堆中时，将其返还到到手牌中并移除其所有的数值调整，之后将其数值设定为<attack>0</>|<health>1</>.",
    "e_vamp_shield": "对本卡牌造成伤害的卡牌将受到<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_vamp_simpledamagefront": "对本卡牌前方第<key> 1 </>格的一张卡牌造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vamp_sol1": "若本卡牌受到伤害且回合结束时在在场地上，抽取<key> {0} </>张牌.",
    "e_vamp_sol3": "若本卡牌受到伤害且回合结束时在场地上，则对<expose>暴露的</>所有对方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_vamp_spear_trigger": "若本卡牌摧毁了一张卡牌，则将其返还到手牌中.",
    "e_vamp_spear": "对本卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害(包括己方卡牌)；若只会对一张卡牌造成伤害，则改为造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_vamp_surrounddamage": "对与本卡牌相邻的所有卡牌(除了对角线)造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vamp_sword_coattack": "当本卡牌所在列的另一张己方卡牌发动攻击时(除了 <key>血刃.blood</> )，本卡牌发动一次攻击.",
    "e_vamp_sword_credit": "若本卡牌所在列还有其他己方卡牌，本卡牌所造成的伤害都将被视作由那张卡牌造成.",
    "e_cross_ctroncharge": "当本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若一张卡牌被放置到己方场地上，则重新激活本卡牌且本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_ctronshot": "若本卡牌处于激活状态，当一张对方卡牌受到伤害且未被摧毁，则对目标造成等同于本卡牌攻击力的魔法伤害并将本卡牌设置为未激活状态.",
    "e_cross_ctronbuff": "当本卡牌拥有计数点时，选择场地上一张己方卡牌(除了 <key>西特隆.cross</> )，将本卡牌拥有的计数点转移到那张卡牌上(以此效果添加计数点后目标卡牌可拥有的计数点上限：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleheatburst": "消耗本卡牌和与本卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:进行一次攻击，该次攻击造成<physical> 4 </><img id=\"\"dmg_phys\"\"/> 物理伤害{b}[<key> {1} +</>]:进行多次攻击，依次造成<physical> 2 </><img id=\"\"dmg_phys\"\"/> +<physical> 2 </><img id=\"\"dmg_phys\"\"/> +<physical> 4 </><img id=\"\"dmg_phys\"\"/> 物理伤害{b}{b}然后<decompile>反编译</>本卡牌并抽取一张卡牌.",
    "e_cross_eleheatpassive": "当场地上拥有<attack> 1 </>点或更多攻击力且与本卡牌<align>对齐的</>一张己方卡牌造成伤害时，若本卡牌拥有的计数点数目少于<uadd>[</><key> {0} </><uadd>]</>个，则对目标造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleheatplay": "令与本卡牌<align>对齐的</>一张己方卡牌获得一个<key> {0} </>点的<specialbuff>衰减性的攻击力增益</>，并重新激活那张卡牌.",
    "e_cross_elecoldburst": "消耗本卡牌和与本卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:延迟所有对方卡牌的行动<key> 3 </>回合{b}[<key> {1} +</>]:延迟所有对方卡牌的行动<key> 6 </>回合{b}{b}然后<decompile>反编译</>本卡牌并抽取一张卡牌.",
    "e_cross_elecoldpassive": "当场地上拥有<attack> 1 </>点或更多攻击力的且与本卡牌<align>对齐的</>一张己方卡牌被伤害时，若本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则对造成伤害的卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_elecoldplay": "增加与本卡牌<align>对齐的</>一张己方卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点，并重新激活那张卡牌.",
    "e_cross_eleshockburst": "消耗本卡牌和与本卡牌<align>对齐的</>卡牌上的所有计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:对前方一张对方卡牌造成<magic> 2 </><img id=\"\"dmg_magic\"\"/> 魔法伤害，每次造成的魔法伤害都将继续朝远处传播，对相邻的对方卡牌造成<magic> 2 </><img id=\"\"dmg_magic\"\"/> 魔法伤害(不包括对角线).{b}[<key> {1} +</>]:对前方一张对方卡牌造成<magic> 4 </><img id=\"\"dmg_magic\"\"/> 魔法伤害，每次造成的魔法伤害都将继续朝远处传播，对相邻的对方卡牌造成<magic> 4 </><img id=\"\"dmg_magic\"\"/> 魔法伤害(不包括对角线).{b}{b}然后<decompile>反编译</>本卡牌并抽取一张卡牌.",
    "e_cross_eleshockpassive": "当场地上攻击力不低于<attack> 1 </>点且与本卡牌<align>对齐的</>一张己方卡牌造成伤害时，若本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则延迟目标的行动<key> {1} </>回合(若目标抵抗了延迟，则对其造成<magic> {2} </><img id=\"\"dmg_magic\"\"/> 魔法伤害)，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleshockplay": "若可能的话，将与本卡牌同列、同行的所有卡牌向本卡牌的方向移动一格.",
    "e_cross_elewaveburst": "消耗本卡牌和与本卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数量触发效果：{b}{b}[<key> {0} +</>]:选择手牌中一张等级不高于<key> 2 </>级的卡牌，将其放置到到己方场地上，然后那张卡牌获得<key> 3 </>个计数点{b}[<key> {1} +</>]:选择手牌中两张等级不高于<key> 2 </>级的卡牌，将其放置到到己方场地上，然后那张卡牌获得<key> 3 </>个计数点{b}{b}然后<decompile>反编译</>本卡牌并抽取一张卡牌.",
    "e_cross_elewavepassive": "当场地上攻击力不低于<attack> 1 </>点且与本卡牌<align>对齐的</>一张己方卡牌造成伤害时，若本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则抽取一张卡牌，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_elewaveplay": "若可能的话，将与本卡牌同列、同行的所有卡牌向远离本卡牌的方向移动一格.",
    "e_cross_emilienatorcharge": "当本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若本卡牌在场地上移动，则重新激活本卡牌并对前方一张对方卡牌造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_emilienatorbeat": "当本卡牌拥有计数点时，消耗本卡牌所有的计数点. 每消耗<key> 1 </>个计数点便对本卡牌前方第<key> 1 </>格的一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害. 若目标抵抗了延迟，则改为对其造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_cross_emilienatordash": "若本卡牌处于激活状态，且至少一张对方卡牌被伤害且未被摧毁，将本卡牌移动到与最后一张受到伤害的卡牌相同列的前排位置上(若已经有一张卡牌，则与其交换位置).",
    "e_cross_emilienatorplay": "抽取一张卡牌.",
    "e_cross_leacharge": "当本卡牌拥有的计数点数目少于<uadd>[</><key> {0} </><uadd>]</>个时，若本卡牌对一张卡牌造成物理伤害，则重新激活本卡牌，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_leashot": "当本卡牌拥有计数点时，选择一张对方卡牌，然后消耗所有计数点，根据消耗的计数点数目(<key> X </>点)对那张卡牌造成<key> X </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_cross_leasearch": "选择抽牌堆中一张 <key>.element</> 卡牌，将其添加到手牌中.",
    "e_cross_counter_condition": "选择场地上<key> {0} </>张拥有计数点的己方卡牌，将所选卡牌拥有的计数点转移到本卡牌上，然后将被选择的卡牌洗入抽牌堆中，解除限制.",
    "e_cross_lukasslash": "消耗所有计数点，并根据消耗的计数点数目(<key> X </>点)，对本卡牌<align>对齐的</>所有对方卡牌造成<magic> {0} X </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大魔法伤害：<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>)(当前魔法伤害：<magic> {2} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_joernsearch": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其添加到手牌中(除了 <key>乔恩.cross</> )，然后将本卡牌拥有的计数点转移到所选卡牌上(以此效果添加计数点后目标卡牌可拥有的计数点上限：<uadd>[</><key> {1} </><uadd>]</>个).",
    "e_cross_apollocharge": "当本卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若己方卡牌受到伤害，则重新激活本卡牌，然后本卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_apollosearch": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其返还到手牌中(除了 <key>阿波罗.cross</> ).",
    "e_cross_hlinplay": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其放置到己方场地上.",
    "e_cross_hlindefense": "若本卡牌即将受到伤害，根据本卡牌拥有的计数点数目等量减少本卡牌受到的伤害，然后消耗本卡牌一半的计数点(向上取整)，根据消耗的计数点数目(<key> X </>点)，令本卡牌获得一个<key> X </>点的<specialbuff>一次性的攻击力增益</>，再令本卡牌同列后方的一张卡牌获得<key> X </>个计数点(以此效果添加计数点后目标卡牌可拥有的计数点上限：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_buggyslash": "消耗所有计数点，并根据消耗的计数点数目(<key> X </>点)，对本卡牌正前方和左上角、右上角紧挨本卡牌的所有对方卡牌造成<key> X </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大伤害次数：<uadd>[</><key> {1} </><uadd>]</>次)(当前伤害：<key> {2} </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_albertplay": "根据本卡牌拥有的计数点数目(<key> X </>点)，选择场地上至多<uadd>[</><key> {0} </><uadd>]</>张对方卡牌各造成<magic> X </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_albertfield": "当你将手牌中的一张卡牌放置到场地上时，将本卡牌的<key> 1 </>个计数点转移到被放置的卡牌上.",
    "e_cross_shizukacondition": "当己方场地上恰好有<key> {0} </>个计数点时，解除限制(当前计数点数目总和/需要的计数点数目总和：{1}/{0}). 当本卡牌被放置到场地上时，将己方场地上所有卡牌拥有的计数点转移到本卡牌上. ",
    "e_cross_shizukaplay": "对所有<expose>暴露的</>对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_cross_shizukaburst": "消耗本卡牌和与本卡牌<align>对齐的</>卡牌上的所有计数点，并根据消耗的计数点数目(<key> X </>点)，对前方一张对方卡牌造成<physical> X </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前物理伤害：<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mahou_bunny_fire_summon": "选择手牌中最左边的一张 <key>茜.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_fire_attack": "<decompile>反编译</>本卡牌，然后对选择的一张卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mahou_girl_fire_proc": "当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时，本卡牌发动一次攻击(不包括对角线).",
    "e_mahou_girl_fire_summon": "选择弃牌堆中一张 <key>火灵·库法.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_earth_summon": "选择手牌中最左边的一张 <key>千枝.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_earth_attack": "<decompile>反编译</>本卡牌，然后选择最多<uadd>[</><key> {0} </><uadd>]</>张对方卡牌并对其各自造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mahou_girl_earth_proc": "当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时，对和前方第一张对方卡牌生命值相同的所有对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害(不包括对角线).",
    "e_mahou_girl_earth_summon": "选择弃牌堆中一张 <key>土灵·库亚.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_water_summon": "选择手牌中最左边的一张 <key>葵.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_water_attack": "<decompile>反编译</>本卡牌，然后抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_mahou_girl_water_proc": "当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时(不包括对角线)，将弃牌堆顶部等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌最左边的 <img id=\"\"effect_manual\"\"/> 指令式模块效果作为本卡牌的效果触发(无视限制).",
    "e_mahou_girl_water_summon": "选择弃牌堆中一张 <key>水灵·库瓦.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_wind_summon": "选择手牌中最左边的一张 <key>风音.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_wind_attack": "<decompile>反编译</>本卡牌，然后选择场地上至多<uadd>[</><key> {0} </><uadd>]</>张己方卡牌并将其返还到手牌中.",
    "e_mahou_girl_wind_proc": "当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时，选择手牌中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌，将其放置到己方场地上(除了 <key>风音.mahou</> ).",
    "e_mahou_girl_wind_summon": "选择弃牌堆中一张 <key>风灵·库维.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_dark_summon": "选择手牌中最左边的一张 <key>月夜.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_dark_attack": "<decompile>反编译</>本卡牌，然后对所有对方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mahou_girl_dark_proc": "若本卡牌处于激活状态，当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时，选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌，将其返还到手牌中(除了 <key>月夜.mahou</> )，然后将本卡牌设置为未激活状态.",
    "e_mahou_girl_dark_summon": "选择弃牌堆中一张 <key>暗灵·库达.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_light_summon": "选择手牌中最左边的一张 <key>星子.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_light_attack": "<decompile>反编译</>本卡牌，然后延迟所有对方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_mahou_girl_light_proc": "若本卡牌处于激活状态，当与本卡牌相邻的卡牌从场地上离开且没有被摧毁时，则选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌，将其放置到己方场地上(除了 <key>星子.mahou</> )，然后将本卡牌设置为未激活状态.",
    "e_mahou_girl_light_summon": "选择弃牌堆中一张 <key>光灵·库利.mahou</> 卡牌，将其放置到己方场地上与本卡牌相邻的位置(不包括对角线).",
    "e_mahou_starwish": "丢弃抽牌堆中的一张卡牌，然后洗牌.",
    "e_mahou_hearttrial_init": "选择场地上一张己方卡牌，将所选卡牌的<key> {0} </>张没有效果且数值为<attack>0</>|<health>1</>的复制品添加到手牌中.",
    "e_mahou_hearttrial_field": "当一张卡牌被放置到己方场上时，<decompile>反编译</>其他的所有与被放置的卡牌同名的卡牌.",
    "e_mahou_starwish_active": "<decompile>反编译</>本卡牌，然后选择弃牌堆中一张<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌(除了 <key>星愿.mahou</> )，将其放置到本卡牌原来的位置上.",
    "e_mahou_girl_shared_tagout": "选择抽牌堆中与本卡牌不同名且等级不高于本卡牌的一张 <key>.mahou</> 卡牌，将本卡牌返还到抽牌堆中并将所选卡牌放置到本卡牌原来的位置上，然后将所选卡牌设置为未激活状态.",
    "e_vault_slash": "对前方一张对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害. 若回合抽牌倒计时为<key> 0 </>点，则触发<key>回合抽牌</>并将一张 <key>连击</> 卡牌添加到手牌中.",
    "e_vault_combo": "当本卡牌位于手牌中或场地上时，若一张攻击力不低于<attack> 1 </>点的<key>.vault</>卡牌触发 <img id=\"\"effect_init\"\"/> 初始化效果，则在该效果结算完毕后再次触发该效果并<void>放逐</>本卡牌(该效果不会由其他 <key>连击</> 触发的效果触发).",
    "e_vault_sharedredraw": "当本卡牌位于手牌中时，丢弃本卡牌，并减少回合抽牌倒计时<key> 1 </>点. 若该手牌原本是你的最后一张手牌，则抽取<key> {0} </>张卡牌.",
    "e_vault_jab": "对前方一张对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>点物理伤害. 此后，抽取一张卡牌.",
    "e_vault_blade": "根据手牌牌中 <key>连击</> 卡牌数目(<key> X </>张)，对前方一张对方卡牌造成<key> X + 1 </>次<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前伤害：<key> {1} </>次<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_vault_apprentice": "将<uadd>[</><key> {0} </><uadd>]</>张 <key>隐秘之刃.vault</> 卡牌和<key> 1 </>张 <key>连击</> 卡牌添加到手牌中.",
    "e_vault_multiblade": "对前方一张对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>点物理伤害. 此后，将一张 <key>隐秘之刃.vault</> 卡牌添加到手牌中.",
    "e_vault_bide": "将<key> {0} </>张 <key>连击</> 卡牌添加到手牌中.",
    "e_vault_agility": "将一张 <key>连击</> 卡牌添加到手牌中.",
    "e_vault_char_edit": "当本卡牌即将离开场地时，造成等同于本卡牌损失的生命值的 <img id=\"\"player_health\"\"/> 角色生命值伤害，然后打开你的<key>卡组编辑器</>并<key>重新加载</>己方卡牌(当前造成的 <img id=\"\"player_health\"\"/> 角色生命值伤害：<key> {0} </><img id=\"\"player_health\"\"/> ).",
    "e_vault_char_ping": "当本卡牌位于场地上或位于弃牌堆中时，该效果可被触发. 触发后，延迟一张对方卡牌的行动<key> {0} </>回合，并将一张 <key>隐秘之刃.vault</> 和一张 <key>连击</> 添加到手牌中. 若本卡牌位于弃牌堆中，则在上述效果触发后将其洗入抽牌堆中.",
    "e_vault_juggle": "丢弃手牌中的<key> 1 </>张卡牌，然后抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌并将一张 <key>隐秘之刃.vault</> 卡牌添加到手牌中.",
    "e_vault_oncemore": "选择场地上一张<key> 1 </>级且具有一个 <img id=\"\"effect_init\"\"/> 初始化效果的己方卡牌，并对所选卡牌前方的一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后触发所选卡牌最左侧的 <img id=\"\"effect_init\"\"/> 初始化效果(该效果不会触发自己同名卡的效果).",
    "e_vault_opportunist": "对所有对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害. 若一张对方卡牌的行动倒计时为<key> 0 </>点，则改为对其造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vault_lightup": "对前方一张对方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害. 此后，减少回合抽牌倒计时<key> 1 </>点.",
    "e_vault_parry": "治疗场地上所有己方卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_vault_condition": "<decompile>反编译</>场地上<key> {0} </>张己方卡牌，解除限制.",
    "e_vault_condition_1_upgrade": "<decompile>反编译</>场地上<uadd>[</><key> {0} </><uadd>]</>张己方卡牌，解除限制.",
    "e_nova_assault": "将 <key>抽牌堆</> 中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.mod</> 卡牌放置到与本卡牌相邻的位置(不包括对角线).",
    "e_nova_sentinel": "将 <key>弃牌堆</> 中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.mod</> 卡牌放置到与本卡牌相邻的位置(不包括对角线).",
    "e_nova_sentinelblock": "将本卡牌受到的伤害降为 <key>0</> ，然后移除该效果.",
    "e_nova_research": "<decompile>反编译</> 所有相邻的卡牌(不包括对角线)，然后根据 <decompile>反编译</> 的卡牌数目依次触发下列效果:{b}{b}[1+]: 抽取 <uadd>[</><key>{0}</><uadd>]</> 张卡牌.{b}[2+]: 延迟所有敌人 <uadd>[</><key>{1}</><uadd>]</> 回合.{b}[3+]: 将弃牌堆中的卡牌洗入抽牌堆中并抽取 <key>{2}</> 张卡牌.",
    "e_nova_researchmanual": "将手牌中的一张 <key>.mod</> 卡牌洗入抽牌堆，然后抽取 <key>{0}</> 张卡牌.",
    "e_nova_architectinit": "选择手牌中任意数量等级不超过 <key>2</> 级的 <key>.mod</> 卡牌，将其放置到场地上.",
    "e_nova_architectfetch": "选择抽牌堆中一张等级不超过 <uadd>[</><key>{0}</><uadd>]</> 级的 <key>.nova</> 卡牌放置到场地上并提升其 <uadd>[</><health>{1}</><uadd>]</> 点生命值.",
    "e_nova_architectcondition": "当场地上没有 <key>.nova</> 卡牌时，解除限制.",
    "e_nova_leviathansummon": "将弃牌堆中的随机 <key>{0}</> 张 <key>.nova</> 卡牌添加到手牌中，若不足则全部).",
    "e_nova_leviathancondition": "当场地上没有卡牌且弃牌堆中有至少 <key>{0}</> 张不同名的 <key>.mod</> 卡牌时，解除限制(当前满足条件的卡牌数 {1}/{0}).",
    "e_nova_leviathanmanual": "将弃牌堆中的随机 <key>{0}</> 张 <key>.nova</> 卡牌添加到手牌中，若不足则全部). 然后移除本卡牌拥有的所有效果.",
    "e_nova_carrierspawn": "在本卡牌的相邻位置分别召唤一名随从(不包括对角线).",
    "e_nova_carrierattack": "令与本卡牌相邻的所有卡牌发动一次攻击(不包括对角线).",
    "e_nova_carriercondition": "将场地上一张拥有 <key>3</> 个效果的 <key>.nova</> 卡牌返还到手牌中(除了 <key>母舰.nova</>).",
    "e_nova_sharedbuffing": "重新激活所有相邻的 <key>.nova</> 卡牌(不包括对角线)，然后将卡牌的所有其他效果添加给相邻的卡牌(每张卡所拥有的效果不能超过<key> 3 </>个).",
    "e_nova_fusillade": "当本卡牌发动 <physical>攻击</> 时，对目标所在行的其他所有卡牌造成 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 点物理伤害.",
    "e_nova_highexplosive": "当本卡牌造成 <img id=\"\"dmg_phys\"\"/> <physical>物理伤害</> 时，则对与目标相邻的所有对方卡牌造成 <uadd>[</><magic>{0}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 魔法伤害(不包括对角线)；若摧毁了目标卡牌，则改为 <uadd>[</><magic>{1}</><img id=\"\"dmg_magic\"\"/><uadd>]</> 魔法伤害.",
    "e_nova_heavycaliber": "本卡牌攻击时，提高 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 物理伤害. 本卡牌攻击后，将其移动到后排，若后排已有其他卡牌，则优先将那张卡牌返还到手牌中.",
    "e_nova_taclink": "当一张卡牌被放置到与本卡牌相邻的位置时(不包括对角线)，令这两张卡牌的 <health>生命值</> 各提高 <uadd>[</><health>{0}</><uadd>]</> 点(生命值上限: 最大生命值 + <health>{0}</> 点).",
    "e_nova_barrier": "若本卡牌的生命值超过 <health>1</> 点，在受到致命伤害时保留<health> 1 </>点生命值.",
    "e_nova_strike": "当本卡牌攻击时，每有一个效果便提升 <uadd>[</><key>{0}</><uadd>]</> 点伤害(当前伤害提升: <key>+{1}</> ). 当本卡牌攻击后，移除本卡牌拥有的所有效果.",
    "e_nova_lance": "若本卡牌的生命值超过 <health>1</> 点，每当移动本卡牌，就令其受到 <magic>1</><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后再发动一次攻击，该攻击造成 <uadd>[</><physical>{0}</><img id=\"\"dmg_phys\"\"/><uadd>]</> 物理伤害.",
    "e_nova_ataraxia": "根据手牌中 <key>.mod</> 卡牌数量触发不同的效果(当前数量: {count}):",
    "e_nova_ataraxia1": "{b}[{first}+]: 发动攻击时，减少回合抽牌倒计时 <uadd>[</><key>{turndraw}</><uadd>]</> 点.",
    "e_nova_ataraxia2": "{b}[{second}+]: 发动攻击时，延迟目标 <uadd>[</><key>{delay}</><uadd>]</> 回合.",
    "e_nova_ataraxia3": "{b}[{third}+]: 增加本卡牌造成的所有伤害( <uadd>[</><key>+{superDmg}</><uadd>]</>).",
    "e_dmg_reduction": "将本卡牌受到的伤害减少<key> {0} </>点.",
    "e_deathcrave": "若本卡牌通过攻击摧毁了一张卡牌，重新激活本卡牌.",
    "e_undamagable": "将本卡牌受到的伤害降低至<key> 0 </>点.",
    "e_dmgcap": "本卡牌每次受到的伤害不会超过<key> {0} </>点.",
    "e_undamagable_physical": "将本卡牌受到的<physical>物理伤害</>降低至<physical> 0 </><img id=\"\"dmg_phys\"\"/> .",
    "e_dmgcap_physical": "本卡牌每次受到的物理伤害不会超过<physical> {0} </><img id=\"\"dmg_phys\"\"/> .",
    "e_undamagable_magic": "将本卡牌受到的<magic>魔法伤害</>降低至<magic> 0 </><img id=\"\"dmg_magic\"\"/> .",
    "e_dmgcap_magic": "本卡牌每次受到的魔法伤害不会超过<magic> {0} </><img id=\"\"dmg_magic\"\"/> .",
    "e_destroy_self": "摧毁本卡牌.",
    "e_decompile_self": "<decompile>反编译</>本卡牌.",
    "e_void_self": "<void>放逐</>本卡牌.",
    "e_attack": "本卡牌发动 {0} 次攻击.",
    "e_quick": "将本卡牌放置到场地上的操作不会消耗回合.",
    "e_revenge": "当本卡牌受到伤害时，本卡牌将发动一次攻击.",
    "e_reflect": "当本卡牌受到伤害时，本卡牌将发动一次等同伤害的攻击.",
    "e_use_potion": "本卡牌使用后将被从本场游戏中移除.",
    "e_volatile": "本卡牌离开场地时将被<void>放逐</>.",
    "e_grave_to_hand": "将本卡牌从弃牌堆中返还到手中.",
    "e_t_ignition": "指令式模块",
    "e_t_desc_ignition": "点击以触发，然后将本卡牌设置为未激活状态(若为敌方卡牌，则在倒计时结束时触发该效果).",
    "e_t_trigger": "触发式模块",
    "e_t_desc_trigger": "当满足特定的条件时，触发该效果，这不会消耗回合(置入结算队列，直至前方的操作与效果结算完毕).",
    "e_t_init": "初始化",
    "e_t_desc_init": "当本卡牌被放置到场地上时，触发该效果(置入结算队列，直至前方的操作与效果结算完毕).",
    "e_t_condition": "条件限制",
    "e_t_desc_condition": "当满足特定的条件时，本卡牌才可被放置到场地上.",
    "e_t_exec": "执行式模块",
    "e_t_desc_exec": "执行本卡牌时，将该效果置入结算队列相应位置；轮到本卡牌执行时，触发该效果(在前方的操作与效果结算完毕后).",
    "e_t_passive": "监听响应",
    "e_t_desc_passive": "当满足特定的条件时，该效果立刻生效，但不会触发那些当一个效果触发时会触发的效果.",
    "e_t_destruction": "销毁",
    "e_t_desc_destruction": "当本卡牌被摧毁时，触发该效果(置入结算队列，直至前方的操作与效果结算完毕)；执行与反编译不是摧毁.",
    "e_t_volatile": "易失性",
    "e_t_desc_volatile": "当本卡牌离开场地时，放逐本卡牌.",
    "e_t_defense": "防御模块",
    "e_t_desc_defense": "本卡牌每次受到的伤害不会超过某个特定的数值.",
    "e_t_quick": "迅速",
    "e_t_desc_quick": "本卡牌被放置到场上时不会消耗回合.",
    "e_t_dragoon": "DRAGOON式链接",
    "e_t_desc_dragoon": "由同一名龙灵创建的程序是彼此高速链接的.",
    "e_t_single": "消耗品",
    "e_t_desc_single": "当本卡牌的效果被触发时，将本卡牌从本场游戏中移除(这同时包括你的游戏区域、存储空间与卡组).",
    "e_t_artifact": "预载",
    "e_t_desc_artifact": "本卡牌将会出现在你的起始手牌中.",
    "e_t_storage": "缓存",
    "e_t_desc_storage": "当本卡牌位于存储空间时，触发该效果.",
    "key_once": "一次性",
    "key_desc_once": "该效果只能触发一次(除非重新加载，即便离开触发该效果的区域之后也不会恢复).",
    "key_instant": "迅捷",
    "key_desc_instant": "触发该效果时，不会消耗回合.",
    "key_unique": "特有模块",
    "key_desc_unique": "该效果在一次操作中只能触发一次.",
    "key_global": "高级特有模块",
    "key_desc_global": "该效果在一次操作中只能由一张卡牌触发一次.",
    "key_bonded": "绑定模块",
    "key_desc_bonded": "该效果无法被移除(除非卡牌本身被覆盖).",
    "key_exclusive": "排他性模块",
    "key_desc_exclusive": "若本卡牌在本次操作中已触发过另一个效果，该效果将不会被触发.",
    "key_chained": "链式模块",
    "key_desc_chained": "当满足特定的条件时，该效果不再置入队列等待，而是改为立刻触发.",
    "h_effectkeyword_void": "<void>放逐</>-被放逐的卡牌将从游戏中暂时移除，并且不能再与之交互. <key>重新加载</>后，从你的卡组中重新获取你被<void>放逐</>了的那些卡牌.",
    "h_effectkeyword_suspend": "<key>挂起</>-延迟目标的行动倒计时(此类效果不会造成目标进入延迟免疫状态).",
    "h_effectkeyword_decompile": "<decompile>反编译</>-将卡牌移除到弃牌堆中，但并不会将其摧毁，也不会得到目标拥有的<img id=\"\"loot\"\"/>.",
    "h_effectkeyword_exposed": "<expose>暴露的</>-卡牌的前面没有其他己方卡牌.",
    "h_effectkeyword_covered": "<cover>被掩护的</>-卡牌的前面有另一张己方卡牌.",
    "h_effectkeyword_automate": "<key>自动化</>-卡牌将获得一定的回合倒计时；回合倒计时结束时，除非已有预设行动，卡牌将进行一次主动攻击(仍可与之互动).",
    "h_effectkeyword_decaybuff": "<specialbuff>衰减性的攻击力增益</>-增加的攻击力每回合减少1点.",
    "h_effectkeyword_singlebuff": "<specialbuff>一次性的攻击力增益</>-本卡牌攻击后，移除该增益.",
    "h_effectkeyword_aligned": "<align>对齐的</>-与本卡牌位于同一列.",
    "h_effectkeyword_pathed": "<pathed>连通的</>-两张卡牌相邻或通过若干卡牌相连，彼此之间没有空位(不包括对角线).",
    "h_activate": "<green>[点击以触发]</>",
    "h_noactivate": "<yellow>[不会触发]</>",
    "h_notactiveturn": "<red>[卡牌未激活]</>",
    "h_usedonce": "<red>[</><img id=\"\"effect_once\"\"></><red>used]</>",
    "h_disabled": "<red>[无效]</>",
    "h_conditionnotmet": "<red>[不符合条件]</>",
    "h_novalidtargets": "<yellow>[没有目标]</>",
    "h_notlocation": "<red>[无法从该位置触发]</>",
    "h_nocounters": "<red>[没有足够的计数点]</>",
    "h_toomanycounters": "<red>[计数点超额]</>",
    "h_noattackpower": "<red>[没有攻击力]</>",
    "h_noslots": "<red>[没有可用的场地]</>",
    "h_maxreached": "<yellow>[已达到最大值]</>",
    "h_upgradeblocker_healthzero": "没有足够的生命值",
    "c_abilityaurora": "宁静",
    "c_abilitydragoon": "幻象",
    "c_abilityesper": "世界之种",
    "c_abilityidol": "再度返场",
    "c_abilityleo": "群山",
    "c_abilityomega": "悖论",
    "c_abilityqueen": "将军",
    "c_artifactgreed": "贪婪.algo",
    "c_artifactmemory": "记忆.algo",
    "c_artifactmomentum": "动量.algo",
    "c_artifactspire": "螺旋.algo",
    "c_chessbishop": "主教",
    "c_chessking": "国王",
    "c_chessknight": "骑士",
    "c_chesspawn": "士兵",
    "c_chessqueen": "女王",
    "c_chessrook": "战车",
    "c_consumablepotionhealth": "恢复药水",
    "c_consumablepotionstorage": "存储药水",
    "c_consumablepotionvoid": "放逐药水",
    "c_debugknife": "刀锋.debug",
    "c_dragoonflame": "龙息",
    "c_fantasyarae": "诅咒女妖.myth",
    "c_fantasycockatrice": "鸡蛇.myth",
    "c_fantasygolem": "魔像.myth",
    "c_fantasygriffin": "狮鹫.myth",
    "c_fantasymermaid": "人鱼.myth",
    "c_fantasyphoenix": "凤凰.myth",
    "c_fantasyunicorn": "独角兽.myth",
    "c_genericafterburner": "助燃器",
    "c_genericavarice": "贪念",
    "c_genericbattery": "电池",
    "c_genericbeartrap": "猎夹",
    "c_genericcapacitor": "电容器",
    "c_genericcinder": "余烬",
    "c_genericconstantcorrection": "格式化",
    "c_genericcrystalball": "水晶球",
    "c_genericdoubleexecute": "多线并行",
    "c_genericember": "余火",
    "c_genericfireball": "火球术",
    "c_genericflashattack": "闪光",
    "c_genericflashbang": "闪光弹",
    "c_genericforce": "斥力",
    "c_genericinferno": "地狱火",
    "c_genericmagicember": "魔力余火",
    "c_genericmagicflare": "魔力闪光",
    "c_genericmegarush": "背水一战",
    "c_genericomen": "预兆",
    "c_genericpendulum": "钟摆",
    "c_genericpureheart": "纯洁之心",
    "c_genericreincarnation": "循环",
    "c_genericscalpel": "手术刀",
    "c_genericshatter": "裂解",
    "c_genericspark": "火花",
    "c_genericthunderclap": "眩光",
    "c_generictreasure": "珍宝",
    "c_mdvaxe": "斧式-AX型.mech",
    "c_mdvcore": "能量核心.mech",
    "c_mdvgatling": "压制者-GT型.mech",
    "c_mdvhammer": "粉碎者-HM型.mech",
    "c_mdvhydro": "水轮号.mech",
    "c_mdvplasma": "等离子号.mech",
    "c_mdvpod": "机甲吊舱",
    "c_mdvrocket": "弹幕",
    "c_mdvspear": "枪式-SP型.mech",
    "c_mdvsword": "剑式-SW型.mech",
    "c_mdvthunder": "雷鸣号.mech",
    "c_mdvtower": "作战指挥塔",
    "c_mdvunity": "机甲联合",
    "c_musicbass": "低音谱号.muse",
    "c_musicdoubleeighth": "双重八分音符.muse",
    "c_musicequalize": "均衡器.muse",
    "c_musicfermata": "延长音.muse",
    "c_musicforte": "强音.muse",
    "c_musicidol1": "爱理.muse",
    "c_musicidol2": "弥希.muse",
    "c_musicidol3": "由纪.muse",
    "c_musicidol4": "佳乃.muse",
    "c_musicidol5": "惠里香.muse",
    "c_musicidolboss": "怜美.muse",
    "c_musicpiano": "弱音.muse",
    "c_musicquarter": "四分音符.muse",
    "c_musicquarterrest": "四分休止符.muse",
    "c_musictreble": "高音谱号.muse",
    "c_musictriplet": "三连音.muse",
    "c_naturalapple": "苹果.fruit",
    "c_naturalbanana": "香蕉.fruit",
    "c_naturalcherry": "樱桃.fruit",
    "c_naturaldemeter": "得墨忒耳.fruit",
    "c_naturalfall": "秋.fruit",
    "c_naturalgreenhouse": "温室",
    "c_naturalgrowth": "生长",
    "c_naturallemon": "柠檬.fruit",
    "c_naturalpersephone": "珀耳塞福涅.fruit",
    "c_naturalpollination": "授粉",
    "c_naturalpomegranate": "石榴.fruit",
    "c_naturalpumpkin": "南瓜.fruit",
    "c_naturalspring": "春.fruit",
    "c_naturalsummer": "夏.fruit",
    "c_naturalwinter": "冬.fruit",
    "c_sakurabow": "长弓.hana",
    "c_sakurakatana": "太刀.hana",
    "c_sakurakunai": "苦无.hana",
    "c_sakuralantern": "提灯.hana",
    "c_sakuraninja1": "刺客沙耶.hana",
    "c_sakuraninja2": "武士石田.hana",
    "c_sakuraninja3": "忍者美罗.hana",
    "c_sakuraninja4": "铳士崎吾.hana",
    "c_sakuraninjaboss": "大名小保.hana",
    "c_sakurapriestess": "巫女千依.hana",
    "c_sakurashide": "御币.hana",
    "c_sakurastorm": "绽樱.hana",
    "c_sakuratorii": "鸟居.hana",
    "c_spdeckedit": "重编程",
    "c_spdeckreload": "还原",
    "c_spinitialize": "初始化",
    "c_spinstantdraft": "编译包",
    "c_spiritamaterasu": "天照.spirit",
    "c_spiritkitsune": "灵狐.spirit",
    "c_spiritkusanagi": "天丛云剑.spirit",
    "c_spiritmagatama": "八尺琼勾玉.spirit",
    "c_spiritneko": "玉猫.spirit",
    "c_spiritnezumi": "福鼠.spirit",
    "c_spiritsika": "神鹿.spirit",
    "c_spirittanzaku": "短册.spirit",
    "c_spirittsukuyomi": "月读.spirit",
    "c_spirittsuru": "仙鹤.spirit",
    "c_spiritwatatsumi": "绵津见.spirit",
    "c_spirityamata": "八岐大蛇.spirit",
    "c_spirityata": "八咫镜.spirit",
    "c_spstoragehit": "缓存命中",
    "c_tutorialfireball": "火球",
    "c_vampgen1": "军团长罗雷多.legion",
    "c_vampgen2_minion": "血仆.legion",
    "c_vampgen2": "幕僚西卡.legion",
    "c_vamphyper": "血陨.blood",
    "c_vamplieu1": "士官伊卡.legion",
    "c_vamplieu2": "使徒米塞拉.legion",
    "c_vamporb": "血月.blood",
    "c_vamporigin": "血祭.blood",
    "c_vampplunge": "血雨.blood",
    "c_vamprevival": "浴血重生.blood",
    "c_vampshield": "血盾.blood",
    "c_vampsol1": "前驱李.legion",
    "c_vampsol2": "后卫奥拉.legion",
    "c_vampsol3": "中锋希里亚.legion",
    "c_vampspear": "血刺.blood",
    "c_vampsword": "血刃.blood",
    "c_magesorcignis": "焰火.sorc",
    "c_magesorceffingo": "复刻.sorc",
    "c_magesorccreo": "造物.sorc",
    "c_magesorcgravitas": "超重.sorc",
    "c_magesorcpotentia": "潜能.sorc",
    "c_magesorctempus": "流年.sorc",
    "c_magesorclux": "圣光.sorc",
    "c_magelucia": "咏唱者·露西娅.mage",
    "c_mageaurelia": "念能者·奥瑞莉娅.mage",
    "c_magecamilla": "附魔者·卡蜜拉.mage",
    "c_magemariana": "奥术师·玛丽安娜.mage",
    "c_mageoctavia": "魔导弓·奥克塔娃.mage",
    "c_magevaleria": "符文剑·瓦莱里娅.mage",
    "c_magedecima": "缀命师·德西玛.mage",
    "c_genericupdraft": "上升涡流",
    "c_generictaser": "电击枪",
    "c_genericambush": "背刺",
    "c_genericrupture": "碎裂",
    "c_edensaffron": "莎芙.eden",
    "c_edenthunder": "落雷.edx",
    "c_edengunner": "枪手X.eden",
    "c_edenreva": "蕾瓦.eden",
    "c_edenhazel": "黑泽尔.eden",
    "c_edenselicy": "赛丽希.eden",
    "c_edenshiso": "虚索.eden",
    "c_edenterra": "泰拉.eden",
    "c_edenviolette": "紫罗兰.eden",
    "c_edenstepslash": "冲击砍杀.edx",
    "c_edenbowsnipe": "狙击弓.edx",
    "c_edencrossfire": "交叉火力.edx",
    "c_edenwave": "动能波动.edx",
    "c_edenragnarok": "诸神黄昏.edx",
    "c_edenshopkeeper": "店长.eden",
    "c_crosseleheat": "热能.element",
    "c_crosselecold": "冰能.element",
    "c_crosseleshock": "电能.element",
    "c_crosselewave": "波能.element",
    "c_crosslea": "莉亚.cross",
    "c_crossemilienator": "艾米莉.cross",
    "c_crossctron": "西特隆.cross",
    "c_crosslukas": "施耐德.cross",
    "c_crossapollo": "阿波罗.cross",
    "c_crossjoern": "乔恩.cross",
    "c_crosshlin": "赫琳.cross",
    "c_crossbuggy": "巴迪.cross",
    "c_crossalbert": "贝奥武甫.cross",
    "c_crossshizuka": "静.cross",
    "c_mahoubunnyfire": "火灵·库法.mahou",
    "c_mahougirlfire": "茜.mahou",
    "c_mahoubunnyearth": "土灵·库亚.mahou",
    "c_mahougirlearth": "千枝.mahou",
    "c_mahoubunnywind": "风灵·库维.mahou",
    "c_mahougirlwind": "风音.mahou",
    "c_mahoubunnywater": "水灵·库瓦.mahou",
    "c_mahougirlwater": "葵.mahou",
    "c_mahoubunnydark": "暗灵·库达.mahou",
    "c_mahougirldark": "月夜.mahou",
    "c_mahoubunnylight": "光灵·库利.mahou",
    "c_mahougirllight": "星子.mahou",
    "c_mahouwish": "星愿.mahou",
    "c_mahouhearttrial": "心之试炼",
    "c_vaultcombo": "连击",
    "c_vaultslash": "劈砍.vault",
    "c_vaultblade": "隐秘之刃.vault",
    "c_vaultjab": "戳刺.vault",
    "c_vaultapprentice": "学徒之刃.vault",
    "c_vaultmultiblade": "刀光剑影.vault",
    "c_vaultbide": "忍耐.vault",
    "c_vaultjuggle": "杂技.vault",
    "c_vaultchar": "隐秘盗贼.vault",
    "c_vaultoncemore": "再来一次.vault",
    "c_vaultagility": "灵敏.vault",
    "c_vaultlightup": "亮剑.vault",
    "c_vaultopportunist": "趁虚而入.vault",
    "c_vaultparry": "拦挡.vault",
    "c_novastandard": "标准.nova",
    "c_novaassault": "突击.nova",
    "c_novasentinel": "哨卫.nova",
    "c_novaresearch": "研究.nova",
    "c_novacarrier": "母舰.nova",
    "c_novacarrier_minion": "蜂群构造体.nova",
    "c_novaarchitect": "缔造.nova",
    "c_novaleviathan": "利维坦.nova",
    "c_novaburstfire": "连发模式.mod",
    "c_novafusillade": "密集射击.mod",
    "c_novahighexplosive": "高爆.mod",
    "c_novaheavycaliber": "大口径.mod",
    "c_novaconvergence": "汇聚.mod",
    "c_novataclink": "战术联结.mod",
    "c_novabarrier": "屏障.mod",
    "c_novastrike": "孤星弹.mod",
    "c_novalance": "星域之矛.mod",
    "c_novaataraxia": "禅意.mod",
    "c_boss1minion": "晶胞.z",
    "c_boss2": "史莱姆.z",
    "c_boss2minion": "史莱姆球.z",
    "c_boss3": "机关人偶.z",
    "c_boss3virus": "绛紫病毒.virus",
    "c_boss4": "死神.z",
    "c_boss4scythe": "镰刀.z",
    "c_boss4dagger": "匕首.z",
    "c_boss4soul": "魂魄",
    "c_boss5": "病毒.z",
    "c_boss5attackminion": "尖刺.z",
    "c_boss5bombminion": "异物.z",
    "c_boss5left": "左臂.z",
    "c_boss5right": "右臂.z",
    "c_bossb1": "得墨忒耳.dark",
    "c_bossb1minion": "荆棘丛",
    "c_bossb2": "怜美.dark",
    "c_bossb2minion": "噪音",
    "c_bossb3": "浪人小保.dark",
    "c_bossb3minion1": "太刀.dark",
    "c_bossb3minion2": "长弓.dark",
    "c_bossb3minion3": "苦无.dark",
    "c_bossb3minion4": "提灯.dark",
    "c_bossb4": "反离子号.dark",
    "c_bossb4minion": "反能量.dark",
    "c_bossb5": "珀耳塞福涅.dark",
    "c_bossb5minion": "棘刺",
    "c_bossb6": "腐化狮鹫.dark",
    "c_bossb6extra": "宝藏.dark",
    "c_bossb6minion": "诅咒",
    "c_bossb7": "枭首罗雷多.dark",
    "c_bossb7minion1": "前驱",
    "c_bossb7minion2": "后卫",
    "c_bossb7minion3": "中锋",
    "c_bossb8": "天照.dark",
    "c_bossb8minion": "恶灵",
    "c_bossb9": "月读.dark",
    "c_bossb9minion": "月光",
    "c_bossb10": "驭死师·德西玛.dark",
    "c_bossb10minion1": "焰火.dark",
    "c_bossb10minion2": "超重.dark",
    "c_bossb10minion3": "造物.dark",
    "c_bossb10minionspawn": "暗黑力量",
    "c_bossmahou": "心之试炼.x",
    "c_bosscomet1": "吉娜-觉醒.z",
    "c_bosscomet1minion": "残影",
    "c_bosscomet2": "吉娜-蓄能.z",
    "c_bosscomet3": "吉娜-狂想.z",
    "c_bosscomet3minion": "影刃",
    "c_bosscomet3minion2": "堕落",
    "c_bosscometdefeat": "吉娜-破碎.z",
    "c_bosswaystone": "毁坏模块",
    "c_cometruinsanctum": "密室?",
    "c_cometsanctum1": "密室",
    "c_cometsanctum2": "密室",
    "c_depthssanctum": "密室",
    "c_dungeonbug": "漏洞.mw",
    "c_enemyartillery": "火炮.sc",
    "c_enemyblackvirus": "漆黑病毒.virus",
    "c_enemybosscandle": "蜡烛.z",
    "c_enemybug": "漏洞.mw",
    "c_enemycache": "密码缓存器",
    "c_enemycachedrafting": "源缓存器",
    "c_enemycacherandom": "比特缓存器",
    "c_enemychandelier": "水晶吊灯.mw",
    "c_enemycollapse": "断头台.ex",
    "c_enemydaggers": "限制器.ex",
    "c_enemydisruptor": "干扰器.sc",
    "c_enemyghostblue": "蔚蓝幽灵.ghst",
    "c_enemyghostred": "猩红幽灵.ghst",
    "c_enemyguardian": "守护者.sc",
    "c_enemyinterceptor": "拦截机.sc",
    "c_enemymiasma": "瘴气散播器.ex",
    "c_enemymine": "地雷.sc",
    "c_enemymirrorshard": "反射棱镜.mw",
    "c_enemyobserver": "观测者.sc",
    "c_enemypassivebug": "漏洞.mw",
    "c_enemypathogen": "病原体.mw",
    "c_enemypredator": "狩食者.sc",
    "c_enemyrail": "电磁炮.sc",
    "c_enemysentry": "Ⅰ型哨兵.sc",
    "c_enemysentry2": "Ⅱ型哨兵.sc",
    "c_enemysignal": "精神控制塔.ex",
    "c_enemystagetarget": "舞台标记",
    "c_enemystealertutorial": "? ? ?",
    "c_enemystrongbug": "严重漏洞.mw",
    "c_enemystrongwall": "防火墙.scx",
    "c_enemytalismanblack": "黑色护符.tlsm",
    "c_enemytalismanwhite": "白色护符.tlsm",
    "c_enemyvenom": "毒药瓶.mw",
    "c_enemyvirusblue": "蔚蓝病毒.virus",
    "c_enemyvirusred": "赤红病毒.virus",
    "c_enemyweaktarget": "目标",
    "c_enemyweakwall": "防火墙.sc",
    "c_enemywormblue": "蔚蓝蠕虫.wrm",
    "c_enemywormred": "赤红蠕虫.wrm",
    "c_enemyzombie": "僵尸.mw",
    "c_miniboss1": "诅咒.x",
    "c_omegaboss": "吉娜-封印.z",
    "c_omegabossunstable": "吉娜-黄昏.z",
    "c_omegacore": "虚空钉刺.z",
    "c_potionhealth": "治疗模块.potion",
    "c_potionstorage": "存储模块.potion",
    "c_syncmarker1": "同步标记",
    "c_syncmarker2": "同步标记",
    "c_syncmarker4": "同步标记",
    "c_timebomb2": "定时炸弹",
    "c_timebomb3": "定时炸弹",
    "c_timebomb4": "定时炸弹",
    "c_timebomb7": "定时炸弹",
    "c_timebomb_h5_t6": "定时炸弹",
    "c_timebomb_h5_t5": "定时炸弹",
    "c_timebomb_h5_t4": "定时炸弹",
    "c_puzzleblank": "空白项",
    "c_storyvolatilecircuit_t2": "不稳定电路",
    "c_storyvolatilecircuit_t3": "不稳定电路",
    "c_storyvolatilecircuit_t4": "不稳定电路",
    "c_storyvolatilecircuit_t5": "不稳定电路",
    "c_storyvolatilecircuit_t6": "不稳定电路",
    "c_storyvolatilecircuit_t7": "不稳定电路",
    "c_storyvolatilecircuit_t8": "不稳定电路",
    "c_storyexplosivecircuit_t4": "易爆电路",
    "c_storyfragilecircuit_t6": "易损电路",
    "c_volatilecircuit_h4_t8": "不稳定电路",
    "c_volatilecircuit_h5_t4": "不稳定电路",
    "c_volatilecircuit_h5_t6": "不稳定电路",
    "c_volatilecircuit_h5_t7": "不稳定电路",
    "c_volatilecircuit_h5_t8": "不稳定电路",
    "c_volatilecircuit_h6_t8": "不稳定电路",
    "c_infinitereload": "导航",
    "c_infiniteinstantdraft": "快速编译",
    "c_quantumknifetutorial": "刀锋.hck",
    "c_quantumsigil": "量子标记",
    "c_enemysentrynoattack": "Ⅰ型哨兵.sc",
    "c_stagemarker": "舞台标记",
    "c_securitylock": "保卫部门.x",
    "c_objectivedata1": "数据.txt",
    "c_openingdungeonmark": "已启动",
    "c_puzzledummy": "占位符",
    "c_lootdummy": "小编译包",
    "c_puzzleironwall": "铜墙",
    "c_puzzleironwall2": "铁壁",
    "c_auroraantisentry": "Ⅱ型哨兵变种.sc",
    "c_queenlock": "系统锁",
    "c_queenlockcore": "锁",
    "c_machineblock": "比特块",
    "c_machineblock2": "比特块",
    "c_machinegear": "奇异装置",
    "c_machinecoin": "硬币",
    "c_brainthorn": "刺痛的妄想",
    "c_brainheart": "破碎的心.z",
    "c_brainqueen": "女王",
    "c_endgamelockgeneral": "赤红.lock",
    "c_endgamelock1": "赤红比特",
    "c_endgamelock2": "赤红比特",
    "c_endgamelock3": "赤红比特",
    "c_endgamelock4": "赤红比特",
    "c_endgamelock5": "赤红比特",
    "c_storyoxygen": "氧气",
    "c_storyhydrogen": "氢气",
    "c_storybackdoor": "后门",
    "c_flowerhologram": "全息图片",
    "c_haloshield": "保护"
}as Record<string, string>