export default{
    "d_queenintro": "女皇部下 1",
    "d_esperintro": "自然一体",
    "d_auroraintro": "樱花散漫",
    "d_leointro": "机械霸主",
    "d_idolintro": "艺术表演",
    "d_esperpuzzle1": "解谜工具箱",
    "d_aurorareprogram": "解谜工具箱",
    "d_aurorastarter1": "樱花 MKI",
    "d_idolstarter1": "艺术表演",
    "d_esperstarter1": "自然一体",
    "d_queenchess": "CHECKMATE",
    "d_esperdungeon1": "自然一体",
    "d_esperdungeon2": "白驹过隙",
    "d_esperdungeon3": "万能魔法",
    "d_auroradungeon1": "樱花散漫",
    "d_auroradungeonspirit": "灵魂呼唤",
    "d_idoldungeon1": "中心舞台",
    "d_idoldungeonmahou": "心灵试验",
    "d_leodungeon1": "机械霸主",
    "d_dragoondungeon1": "晨曦与尘落",
    "d_dragoondungeon2": "同心协力",
    "d_dragoondungeoninf": "无限求知",
    "d_omegadungeon1": "军团总部",
    "d_collabeden": "伊甸之路",
    "d_collabcross": "远星物语",
    "d_collabvault": "虚空宝库",
    "d_auroraside1": "樱花 MKII",
    "d_queenside1": "女皇荣耀",
    "d_queenomegaduel": "女皇荣耀",
    "d_idolside1": "现场表演",
    "d_idolside2": "现场表演",
    "d_dragoonstory1": "神话传说",
    "d_dragoonstoryflame": "神圣烈焰",
    "d_esperside1": "演示装备",
    "d_esperside2": "演示装备?",
    "d_leoside1": "机械工具箱",
    "d_leoside2": "烈焰装备",
    "d_idolexpuzzle1": "解谜工具箱",
    "d_leoexpuzzle1": "解谜工具箱",
    "d_expuzzlemage": "解谜工具箱",
    "d_collabedendemo": "伊甸之路",
    "d_collabcrossdemo": "远星物语",
    "d_collabvaultdemo": "虚空宝库",
    "e_boss1effect_spawn": "召唤<key> {0} </>个随从.",
    "e_boss1effect_spawn_upgrade": "召唤<key> {0} </>个随从，<uadd>[</>并根据该卡牌拥有的计数点等量增加随从的生命值<uadd>]</>.",
    "e_boss1effect_splash": "对对方场地上所有卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss1effect_splashtrigger": "当一张卡牌被摧毁时，对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss2effect_aoe": "对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss2effect_passive": "This card takes 1 less damage from all sources for every other card on your field(CURRENT<key>- {0} </>).",
    "e_boss2effect_spawn": "当该卡牌受到伤害时，召唤一个生命值等同于本次受到的伤害值的随从.",
    "e_boss2effect_superspawn": "根据己方场地上的空位数目(<key> X </>格)，召唤<key> X - 1 </>个生命值为<health> {0}X  </>点的随从(当前随从生命值：<health> {1} </>点).",
    "e_boss3effect_blast": "摧毁场地上没有效果的所有的卡牌，每摧毁一张卡牌便造成<health> {0} </><img id=\"\"player_health\"\"/> 生命值伤害.",
    "e_boss3effect_control": "移除对方场地上所有卡牌的效果，然后将其转移到己方场地上.",
    "e_boss3effect_spawn": "召唤<key> 3 </>个随从并清除己方弃牌堆中所有的卡牌.",
    "e_boss3effect_spawn_super": "召唤<key> {0} </>个随从并清除己方弃牌堆中所有的卡牌，并根据该卡牌拥有的计数点等量增加随从的生命值，然后该卡牌获得<key> 1 </>个计数点.",
    "e_boss3effect_protection": "将该卡牌受到的伤害降低至<key> 0 </>点；若对方场地上恰好有<key> {0} </>张没有效果的卡牌，则该效果无效(当前对方场地上没有效果的卡牌个数/令该效果无效需要的没有效果的卡牌数目：{1}/{0}).",
    "e_boss4effect_dagger_move": "当对方的一张卡牌发动攻击后，将该卡牌向发动攻击的卡牌的方向水平移动一格(若目标位置已经有一张卡牌，则与其交换位置).",
    "e_boss4effect_scythe_destruct": "增加己方场上其他的所有卡牌的攻击力<key> {0} </>点.",
    "e_boss4effect_scythe_move": "当对方的一张卡牌发动攻击后，将该卡牌水平移动到发动攻击的卡牌的正对位置(若目标位置已经有一张卡牌，则与其交换位置).",
    "e_boss4effect_spawn": "召唤<key> 1 </>个随从.",
    "e_boss4effect_superspawn": "在对方场上与这张牌所在的同一列的第一排生成一张<key>灵魂</>卡牌(如果此处有卡牌，则将其覆盖).",
    "e_boss4effect_soul_death": "当该卡牌离开场地时，游戏失败.",
    "e_boss4effect_weapondeath": "当该卡牌被移除到弃牌堆中时，增加己方场地上所有卡牌的攻击力<key> {0} </>点.",
    "e_boss5effect_1": "当你触发<key>重新加载</>效果时，增加该卡牌<attack> 1 </>点攻击力.",
    "e_boss5effect_2": "当该卡牌受到伤害时，若该卡牌拥有计数点，则消耗一个计数点并将该卡牌本次受到的伤害降低至<key> 0 </>点；否则，该卡牌获得<key> 1 </>个计数点.",
    "e_boss5effect_bombminion": "对对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害并造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_boss5effect_left1": "丢弃对方手牌中所有的卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_boss5effect_left2": "在对方场上与这张牌所在的同一列的第一排生成一个随从，如果此处有卡牌，则将其覆盖.",
    "e_boss5effect_right1": "对对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_boss5effect_right2": "召唤<key> {0} </>个随从.",
    "e_bossb1_1": "根据对方场地上的空位数目(<key> X </>格)，召唤一个生命值为<health> {1}X </>点的随从(最低生命值：<health> 1 </>点)。然后向对方场地上所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>魔法伤害.",
    "e_bossb1_2": "当该卡牌拥有计数点时，若对方将手牌中的一张卡牌放置到场地上，则该卡牌发动一次攻击.",
    "e_bossb1_3": "该卡牌获得<key> {0} </>个计数点(最大计数点个数：<key> {0} </>个)。当该卡牌拥有计数点时，根据该卡牌拥有的计数点数目等量减少己方场地上其他卡牌受到的伤害。当该卡牌受到伤害时，移除<key> 1 </>个计数点.",
    "e_bossb1_minion_1": "造成等同于该卡牌攻击力的  <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossb1_minion_2": "当对方场地上的一张卡牌移动时，对其造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_bossb2_1": "召唤<key> {0} </>个拥有<key> {1} </>个或<key> {2} </>个计数点的随从.",
    "e_bossb2_2": "场地上所有卡牌获得<key> {0} </>个计数点(每张卡牌拥有的计数点个数不能超过<key> {1} </>个).",
    "e_bossb2_3": "当拥有计数点的卡牌受到伤害时，那张卡牌将消耗一个计数点并将其本次受到的伤害降低至<key> 0 </>点.",
    "e_bossb2_minion_1": "当该卡牌对其他卡牌造成伤害但没有将其生命值降为<health> 0 </>点时，造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossb3_1": "当该卡牌拥有计数点时，召唤<key> {1} </>个随从；否则，召唤<key> {0} </>个随从。召唤后该卡牌获得<key> {2} </>个计数点(最大计数点个数：<key> {2} </>个).",
    "e_bossb3_2": "当该卡牌受到伤害时，根据该卡牌拥有的计数点等量减少该卡牌受到的伤害(当前伤害减少量：-<key> {0} </>点)。若该伤害值不高于该卡牌拥有的计数点数目，则消耗<key> 1 </>个计数点；否则，消耗所有的计数点.",
    "e_bossb3_3": "当己方场地上其他的一张卡牌被摧毁时，触发己方场地上除该卡牌以外的所有卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能.",
    "e_bossb3_minion_1": "该卡牌发动 {0} 次攻击.",
    "e_bossb3_minion_2": "该卡牌发动一次攻击并对前方一张敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bossb3_minion_3": "对对方场地上所有卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bossb3_minion_4": "召唤 {0} 个随从.",
    "e_bossb4_1": "根据对方手牌中拥有的卡牌数目召唤等量的随从，然后对对方手牌中所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_bossb4_2": "当场地上一张卡牌被摧毁时，该卡牌获得<key> 1 </>个计数点。当该卡牌拥有的计数点不少于<key> {0} </>个时，消耗所有计数点并对场地上所有卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/>  魔法伤害(包括该卡牌).",
    "e_bossb4_3": "根据该卡牌拥有的计数点数目，对对方场地上所有的卡牌造成等量的魔法伤害(最小魔法伤害：<magic> 1 </><img id=\"\"dmg_magic\"\"/>  )(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/>  ).",
    "e_bossb5_1": "根据该卡牌的攻击力(<key> X </>点)，召唤<key> X </>个生命值为<health> X </>点的随从(当前随从个数：<key> {0} </>个).",
    "e_bossb5_2": "当该卡牌造成不低于<key> 0 </>点的伤害时，<void>放逐</>除目标外对方场地上<expose>暴露的</>所有的卡牌.",
    "e_bossb5_3": "增加该卡牌的攻击力<attack> {0} </>点.",
    "e_bossb6_1": "将对方场地上后排的卡牌与对方弃牌堆中所有的卡牌洗入抽牌堆中，并将对方场地上前排的卡牌移动到后排，然后对方抽取卡牌至手牌中卡牌数目为<key> 5 </>张.",
    "e_bossb6_2": "当该卡牌拥有的计数点数目少于<key> {0} </>个时，若己方场地上其他的卡牌将受到伤害时，则将其受到的伤害降低至<key> 0 </>点，然后该卡牌获得等同于其降低的伤害数值的计数点(最大计数点个数：<key> {0} </>个)；否则，该效果无效.",
    "e_bossb6_3": "该卡牌受到的伤害不会超过其拥有的计数点数目(当该卡牌没有计数点时，将该卡牌受到的伤害降低至<key> 0 </>点)。当该卡牌受到伤害时，根据所受伤害的数值移除等量的计数点.",
    "e_bossb6_extra_1": "根据该卡牌持有的计数点数目召唤等量的随从(最少随从数目：<key> 1 </>个)，然后该卡牌获得一个计数点(最大计数点个数：<key> {0} </>个).",
    "e_bossb7_1": "根据对方场地上的卡牌数目召唤等量的随从(最少随从数目：<key> {0} </>个).",
    "e_bossb7_2": "当己方场地上的卡牌被摧毁时，该卡牌获得<key> 1 </>个计数点。当该卡牌拥有的计数点数目不少于<key> {0} </>个时，消耗所有计数点并令己方场地上所有的卡牌发动一次攻击.",
    "e_bossb7_3": "根据该卡牌拥有的计数点数目发动相同次数的攻击(最少攻击次数：<key> 1 </>次)(当前攻击次数：<key> {0} </>次).",
    "e_bossb8_1": "摧毁己方场地上所有的随从。每摧毁一个随从，便造成<health> {1} </><img id=\"\"player_health\"\"/> 角色生命值伤害，然后召唤<key> {0} </>个随从.",
    "e_bossb8_2": "当对方放置一张卡牌时，召唤一个攻击力和生命值等于该卡牌拥有的计数点数目的随从(最低随从属性：<attack>1</>|<health>1</>)，然后该卡牌获得一个计数点.",
    "e_bossb8_3": "消耗该卡牌拥有的所有计数点，并根据该卡牌拥有的计数点数目(<key> X </>个)，对对方场地上所有的卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/>  魔法伤害(最低魔法伤害：<magic> 1 </><img id=\"\"dmg_magic\"\"/>  ).",
    "e_bossb8_minion_1": "Cards in this column deal no damage to cards in a different column.",
    "e_bossb8_minion_2": "Deal <magic>{0}</><img id=\"\"dmg_magic\"\"/>   damage to all your opponent's cards in the same column as this card.",
    "e_bossb9_1": "召唤<key> {0} </>个攻击力和生命值等于该卡牌攻击力的随从；当该卡牌拥有<key> 4 </>个计数点时，召唤<key> 4 </>个随从；当该卡牌拥有<key> 8 </>个计数点时，召唤<key> 8 </>个随从.",
    "e_bossb9_2": "当对方放置一张卡牌或触发<key>回合抽牌</>时，若该卡牌持有<key> {0} </>个计数点，则消耗所有计数点并增加该卡牌的攻击力<attack> {1} </>点；否则，该卡牌获得<key> 1 </>个计数点.",
    "e_bossb9_3": "将己方场地上所有卡牌承受的伤害降低<key> {0} </>点；当该卡牌拥有<key> 4 </>或<key> 8 </>个计数点时，该效果无效.",
    "e_bossb9_minion_1": "当该卡牌位于场地上时，若该卡牌对一张对方卡牌造成造成伤害或受到伤害时，<void>放逐</>目标卡牌或对其造成伤害的卡牌.",
    "e_bosscomet1_1": "当该卡牌受到不低于<key> 0 </>点的伤害且该卡牌未被摧毁时，将该卡牌移动到随机位置并在该卡牌原先的位置召唤<key> 1 </>个随从；否则，该效果无效.",
    "e_bosscomet1_2": "该卡牌发动四次攻击并对前方一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_bosscomet1_minion": "将己方场地上与该卡牌不同名的卡牌受到的伤害降低至<key> 0 </>点.",
    "e_bosscomet2_1": "当该卡牌受到伤害时，该卡牌获得一个计数点并延迟该卡牌的行动<key> {0} </>回合。当该卡牌拥有<key> {1} </>个计数点时，消耗所有计数点，然后对对方场地上所有的卡牌造成<magic> {2} </><img id=\"\"dmg_magic\"\"/>  魔法伤害并造成<health> {2} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bosscomet3_1": "召唤<key> {0} </>个拥有随机数值的生命值和攻击值的随从；若对方弃牌堆中有不少于<key> {1} </>张 <key>Corruption</> 卡牌，则召唤<key> {0} </>个属性为<attack>{2}</>|<health>{3}</>的随从，然后将该卡牌移动到随机位置.",
    "e_bosscomet3_2": "当已方场地上有其他卡牌时，将该卡牌受到的伤害减少<key> {0} </>点.",
    "e_bosscomet3_3": "将<key>Corruption</>卡牌放置到对方场地上所有的空位处.",
    "e_bosscomet3_bomb_trigger": "当该卡牌被移动到其他位置时，将该卡牌洗入抽牌堆中.",
    "e_bosscomet3_bomb": "造成<health> {0} </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_bossomega_core": "当该卡牌受到伤害时，延迟己方场地上其他的所有卡牌的行动<key> {0} </>回合.",
    "e_bossomega_countdown": "将对方的 <img id=\"\"player_health\"\"/> 角色生命值降低至<health> 0 </><img id=\"\"player_health\"\"/> .",
    "e_bossomega_passive": "每回合后，将该卡牌的生命值恢复至<health>最大生命值</>.",
    "e_bossomega_transform": "当该卡牌被摧毁时，进入第二阶段.",
    "e_consumablecache": "当该卡牌召唤随从时，该卡牌获得<key> {0} </><img id=\"\"loot\"\"/> 个计数点( {1} ).",
    "e_consumablecacheremoval": "当该卡牌受到伤害时，<void>放逐</>己方场地上其他的所有 <key>.potion</> 卡牌.",
    "e_enemyartillery": "增加己方场地上其他的所有<key>Artillery.sc</>卡牌的攻击力<attack> {0} </>点.",
    "e_enemyblackvirus_manual": "造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyblackvirus_triggeer": "当该卡牌被场地上一张卡牌伤害时，将其转化为该卡牌并移除其等级与该效果；当对该卡牌造成伤害的卡牌未位于场地上时，该效果无效.",
    "e_enemychandelier": "当场地上一张卡牌移动时，增加该卡牌的攻击力<key> {0} </>点，攻击后重置攻击力.",
    "e_enemycollapse": "当对方场地上拥有至少<key> {0} </>张卡牌时，若对方一张卡牌的效果被触发，则对对方场地上所有的卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemycommandsignal_destroy": "己方场地上所有卡牌发动一次攻击.",
    "e_enemycommandsignal_manual": "己方场地上所有卡牌发动一次攻击；若己方场地上没有卡牌能发动攻击，则对角色造成<health> 1 </> <img id=\"\"player_health\"\"/> 生命值伤害然后<decompile>反编译</>该卡牌.",
    "e_enemydaggers": "当对方将手牌中的一张卡牌放置到场地上时(不包括角色特殊技能)，该卡牌发动一次攻击，然后增加该卡牌的攻击力<attack> {0} </>点(攻击力增加上限：+<attack> {1} </>点).",
    "e_enemydetonator": "对场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemydisruptor_passive": "当对方抽取一张卡牌时，治疗该卡牌<health> 1 </>点生命值.",
    "e_enemydisruptor_trigger": "当该卡牌受到伤害时，丢弃对方抽牌堆顶端的卡牌.",
    "e_enemyghostblue": "当该卡牌造成伤害或受到伤害时，将目标卡牌或对该卡牌造成伤害的卡牌移动到对方场地上的随机位置.",
    "e_enemyghostred": "当该卡牌受到伤害时，将该卡牌移动到随机位置.",
    "e_enemyguardian": "当对方抽取一张卡牌时，增加该卡牌的攻击力<attack> 1 </>点.",
    "e_enemyinterceptor": "当己方场地上的卡牌受到伤害时，该卡牌发动一次攻击.",
    "e_enemymiasma_damage": "对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemymiasma_protect": "根据己方场地上与该卡牌不同名的卡牌数目，等量降低该卡牌受到的伤害(当前伤害减少量：-<key> {0} </>点).",
    "e_enemyminibosscurse_attack": "将该卡牌移动到随机位置，然后该卡牌发动一次攻击并造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_enemyminibosscurse": "当该卡牌受到伤害时，对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemymirrorshard": "当该卡牌受到伤害时，其他<key>MirrorShard.mw</>卡牌将发动一次攻击并造成等同于此次受到的伤害值的伤害.",
    "e_enemyobserver": "当对方的卡牌触发效果时，<void>放逐</>抽牌堆、手牌、场牌和弃牌堆中除触发特效的卡牌以外与该卡牌同名的所有卡牌.",
    "e_enemypathogen_destruct": "丢弃对方手牌中所有的卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_enemypathogen": "对对方场地上所有的卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemyphantomred": "Move your opponent's backrow to the front.Swap any cards that over lap.",
    "e_enemypredator": "当对方场地上不是满生命值的卡牌移动时，将该卡牌移动到对应卡牌同一列的己方前排位置并发动一次攻击.",
    "e_enemyrailgun": "当该卡牌受到伤害时，增加该卡牌的攻击力<attack> {0} </>点.",
    "e_enemytalismanblack": "移除对方场地上所有卡牌上的效果并摧毁对方场地上没有效果的所有卡牌.",
    "e_enemyvenomdestruct": "将该卡牌添加到抽牌堆顶端.",
    "e_enemyvenomexecute": "造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyvenommanual": "摧毁该卡牌并造成<health> {0} </> <img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_enemyvirusblue": "当该卡牌造成伤害或受到伤害时，移除目标卡牌或对该卡牌造成伤害的卡牌的所有效果.",
    "e_enemyvirusred_attack": "攻击没有任何效果的卡牌时，造成<attack> {0} </>点伤害.",
    "e_enemyvirusred_passive": "该卡牌不会受到没有任何效果的卡牌造成的伤害.",
    "e_enemywhitetalisman_trigger": "当一张等级不低于<key> 1 </>级的己方卡牌被移除到弃牌堆中时(除了 <key>White.tlsm</> )，将该卡牌转换为那张卡牌的复制品.",
    "e_enemywormblue": "当该卡牌发动攻击并对一张卡牌造成伤害时，对目标卡牌所在行的其他卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/>  魔法伤害.",
    "e_enemywormred": "该卡牌发动两次攻击并对前方一张对方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_enemyzombie": "当该卡牌处于弃牌库中时，若己方场地上一张卡牌被摧毁时(除了 <key>Zombie.mw</> )，将该卡牌放置到己方场地上.",
    "e_haloshield": "将与该卡牌不同名的卡牌受到的伤害降低至 0 点.",
    "e_shareddelayonhit": "当该卡牌受到伤害时，延迟该卡牌的行动 {0} 回合.",
    "e_sharedoneshotonly": "当该卡牌受到伤害但没有被摧毁时，游戏失败.",
    "e_specialcryptcache_drafting": "当该卡牌被放置到场地上时，该卡牌获得<key> {0} </>个 <img id=\"\"loot\"\"/> 编译材料.",
    "e_specialcryptcache_random": "当该卡牌被放置到场地上时，该卡牌获得一定数目的编译材料.",
    "e_specialcryptcache": "当该卡牌被放置到场地上时，该卡牌获得包括一张消耗品卡牌在内的一定数目的编译材料.",
    "e_specialsanctum": "当该卡牌被放置到场地上时，治疗<key> {0} %</>丢失的 <img id=\"\"player_health\"\"/> 角色生命值。然后<key>重新加载</>对方的所有卡牌.",
    "e_specialtimebomb": "游戏失败.",
    "e_specialwaystone": "当该卡牌被放置到场地上时，打开卡组编辑器.",
    "e_storyantiaurora": "将用户名为<key>AURORA's</>的角色的角色生命值降低至0点.",
    "e_storyendgamelock": "当<key>Dragoon'sflame</><decompile>反编译</>一张卡牌时，摧毁该卡牌.",
    "e_storyflowerhologram": "当该卡牌被摧毁时，将己方场地上与该卡牌相邻(不包括对角线)卡牌的行动倒计时设置为 {0} .",
    "e_storyhydrogencard": "当你触发了<key>回合抽牌</>时，摧毁该卡牌并将 <img id=\"\"player_health\"\"/> 角色生命值设置为<health> 0 </>点.",
    "e_storyoxygencard": "将该卡牌受到的伤害降低至0点；若该卡牌左右两侧的卡牌为\"\" <key>Hydrogen</> \"\"，则该效果无效.",
    "e_storystealer": "<decompile>反编译</>对方场地上、手牌中和抽牌堆中所有的卡牌.",
    "e_storysyncmark": "当一张<key>SyncMarker</>被移除到弃牌堆中时，游戏失败。若所有的 <key>SyncMarker</> 卡牌在同一回合内被移除到弃牌堆中，则此效果无效.",
    "e_bossb10_1": "当对方场地上的一张卡牌移动时，将该卡牌移动到随机位置并将弃牌库顶端的卡牌放置到该卡牌移动前所在的位置.",
    "e_bossb10_2": "当对方手牌中和场地上的卡牌数目不少于己方场地上的卡牌数目时，在该卡牌攻击后，<decompile>反编译</>场地上除该卡牌以外所有的卡牌(当前己方卡牌数目和对方卡牌数目：<key> {0} </>vs<key> {1} </>).",
    "e_bossb10_3": "将己方弃牌库中所有的卡牌按照从左到右、从前排到后排的顺序依次放置到场地上，然后将<key> {0} </>个随从添加到己方弃牌堆中.",
    "e_bossb10_minion_shared_adder": "增加该卡牌<health> 1 </>点<health>最大生命值</>(增加量上限：+<uadd>[</><health> {0} </><uadd>]</>点)。若该卡牌的最大生命值已达到最大值，则<void>放逐</>该卡牌.",
    "e_bossb10_minion_1": "根据己方场地上与该卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，对前方一张对方卡牌造成<physical> X </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前伤害：<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_bossb10_minion_2": "根据己方场地上与该卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，对对方场地上所有卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/>  魔法伤害(当前伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/>  ).",
    "e_bossb10_minion_3": "根据己方场地上与该卡牌同名的卡牌的<health>生命值总和</>(<health> X </>点)，丢弃对方抽牌堆顶端<key> X </>张卡；若对方的抽牌堆中没有卡牌，则造成<health> X </> <img id=\"\"player_health\"\"/> 角色生命值伤害(当前弃牌数目：<key> {0} </>张).",
    "e_bossmahou_1": "当己方场地上的一张卡牌被摧毁时，消耗该卡牌一半的计数点并召唤一张随机的随从.",
    "e_bossmahou_2": "当该卡牌受到伤害时，根据该卡牌拥有的计数点数目发动相同次数的攻击(当前攻击次数：<key> {0} </>)，然后消耗<key> 1 </>个计数点.",
    "e_bossmahou_3": "<void>放逐</>场地上<expose>暴露的</>其他的所有的卡牌以及己方弃牌堆中的所有的卡牌，并召唤<key> {0} </>个随机的随从，然后该卡牌获得<key> {1} </>个计数点.",
    "e_ability_aurora": "当你进行消耗回合数的操作时(比如放置一张卡牌或移动一张卡牌)，消耗一枚<key>宁静点数</>并使刚才的操作附带迅捷.",
    "e_ability_aurora_counters": "该卡牌获得<key> {0} </>枚<key>宁静点数</>.",
    "e_ability_dragoon": "令抽牌堆、弃牌堆、场地上和手牌中的所有我方卡牌获得 <key>.*</> 符号且 <key>.*</> 符号可被视作任意的后缀.",
    "e_ability_esper": "当你将一张等级不高于<key> {0} </>级的卡牌放置到我方场地上时(除了 <key>WorldSeed</> )，将该卡牌转化为那张卡牌初始版本的复制品.",
    "e_ability_idol": "将场地上所有的我方卡牌返还到手牌中，并根据返还的卡牌数目(<key> X </>张)，选择手牌中至多<key> X </>张原来未位于场地上的我方卡牌，将其放置到场地上.",
    "e_ability_leo_1": "重新激活场地上的所有我方卡牌，并增加其攻击力<attack> {0} </>点.",
    "e_ability_leo_2": "当一张我方卡牌被移除到弃牌堆中时(除了 <key>Mountain</> )，将其返还到手牌中.",
    "e_ability_omega": "选择场地上的两张卡牌，若其是我方卡牌，则将其<key>自动化</>，若是敌方卡牌，则延迟其行动倒计时<key> {0} </>回合.",
    "e_ability_queen": "触发场地上所有我方卡牌的主动技能。在该效果生效期间，所有我方卡牌造成的伤害提升至<key> {0} </>倍.",
    "e_artifact_greed_active": "抽取<key> {0} </>张卡牌.",
    "e_artifact_greed": "当你触发<key>回合抽牌</>时，额外抽取一张卡牌并丢弃抽牌堆顶端<key> 2 </>张卡牌。当抽牌堆中没有卡牌时，每回合造成<key> 1 </><img id=\"\"player_health\"\"/> 角色生命值伤害.",
    "e_artifact_memory": "当你触发<key>重新加载</>效果时，将存储空间中随机一张等级不低于<key> 1 </>级的卡牌添加到抽牌堆中.",
    "e_artifact_momentum_active": "触发<key>回合抽牌</>.",
    "e_artifact_momentum": "当一张敌方卡牌被摧毁时，触发<key>回合抽牌</>。当你抽取一张卡牌时，若手牌中卡牌数目不低于<key> {0} </>张，则<decompile>反编译</>抽取的卡牌并减少回合抽牌倒计时<key> 1 </>点.",
    "e_artifact_spire_active": "丢弃手牌中所有的卡牌并抽取<key> {0} </>张卡牌.",
    "e_artifact_spire": "当你触发<key>回合抽牌</>时，若手牌中没有卡牌，则额外抽取<key> {0} </>张卡牌。当你抽取一张卡牌时，若手牌中卡牌数目不低于<key> {1} </>张，则<decompile>反编译</>被抽取到的卡牌.",
    "e_artifact_starter": "<key>重新加载</>后，将该卡牌放置到抽牌堆顶端.",
    "e_chess_bishop_init": "治疗场地上所有我方卡牌的生命值<health> 1 </>点.",
    "e_chess_bishop_manual": "对对角线上最近的一张敌方卡牌发动一次攻击.",
    "e_chess_king_death": "当该卡牌从场地上被移除到弃牌堆中时，游戏失败.",
    "e_chess_king_init": "当弃牌堆中至少有一张卡牌时，将弃牌堆中的所有卡牌洗入抽牌堆中，并根据洗入的卡牌数目等量增加该卡牌的攻击力(攻击力增加上限：+<attack> {0} </>点)(当前攻击力增加量：+<attack> {1} </>点)，然后抽取卡牌至手牌中卡牌数目为 {2} 。若象棋卡组中有卡牌缺失，则将缺失的卡牌洗入抽牌堆中(但不会增加该卡牌的攻击力).",
    "e_chess_king_manual": "将该卡牌从场地上或从弃牌堆中洗入抽牌堆中，并抽取一张卡牌.",
    "e_chess_knight_init": "该卡牌发动一次攻击.",
    "e_chess_knight_manual": "对 3 * 2 格的对角线上的一张敌方卡牌发动一次攻击.",
    "e_chess_pawn_manual": "对左上角或右上角紧挨该卡牌的一张敌方卡牌发动一次攻击.",
    "e_chess_pawn_trigger": "当该卡牌造成伤害时，该卡牌获得<key> 1 </>个计数点。当该卡牌拥有<key> {0} </>个计数点时，消耗所有计数点并将该卡牌转化为<key>Queen</>，然后触发其初始化效果.",
    "e_chess_queen_init": "根据场地上所有我方卡牌的数目，对所有敌方卡牌造成等量的魔法伤害(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_chess_queen_loot": "消耗所有编译材料。每消耗一个编译材料，治疗<health> 1 </><img id=\"\"player_health\"\"/> 角色生命值(当前治疗量： {0} <img id=\"\"player_health\"\"/> ).",
    "e_chess_queen_manual": "对所有敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_chess_rook_manual": "该卡牌发动一次攻击.",
    "e_chess_rook_passive": "当该卡牌受到伤害时，增加其攻击力<attack> {0} </>点。当该卡牌造成伤害时，同时攻击目标后面的一张卡牌.",
    "e_dragoon_condition": "<decompile>反编译</>场地上<key> {0} </>张我方卡牌，解除限制.",
    "e_dragoon_flame": "<decompile>反编译</>场地上生命值为<health> 1 </>的所有敌方卡牌.",
    "e_dragoon_shared": "当该卡牌受到伤害时，所有具有该效果卡牌将受到等量的伤害。若该伤害来自具有该效果的卡牌，则此效果无效.",
    "e_eden_bowsnipe": "对前方一列敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_crossfire": "对对角线上除该卡牌以外的所有卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_gunner_boost": "当你触发<key>回合抽牌</>时，该卡牌获得一个<uadd>[</><attack> {0} </><uadd>]</>点的不可叠加的<specialbuff>一次性的攻击力增益</>.",
    "e_eden_gunner": "当该卡牌造成伤害时，若其拥有至少<key> {1} </>个计数点，则消耗所有计数点并减少回合抽牌倒计时<key> {0} </>点；否则，该卡牌获得<key> 1 </>个计数点.",
    "e_eden_hazel_adder": "将弃牌堆中随机一张 <key>.edx</> 卡牌返还到手牌中.",
    "e_eden_hazel": "当该卡牌造成不低于<key> 0 </>点的伤害时，移除该卡牌所在行上攻击力为<attack> 0 </>点的所有卡牌的效果和属性修正，并将其属性设置为<uadd>[</><attack>{0}</>|<health>{1}</><uadd>]</>.",
    "e_eden_ragnarok": "根据该卡牌的攻击力(<key> X </>点)，对前方第<key> 2 </>格的一张敌方卡牌造成<uadd>[</><magic> {0}</><uadd>]</><magic>X </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害(最大魔法伤害：<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>)。若该伤害对目标卡牌造成伤害，则对其他的所有敌方卡牌造成该伤害一半的魔法伤害.",
    "e_eden_reva_reflect": "当该卡牌受到伤害时，其获得一个等同于本次受到的伤害的<specialbuff>衰减性的攻击力增益</>(攻击力增加上限：+<attack> {0} </>点)，然后该卡牌发动一次攻击.",
    "e_eden_reva": "当该卡牌移动到另一列时，治疗其生命值<health> {0} </>点。当该卡牌移动到另一行时，治疗其生命值<health> {1} </>点.",
    "e_eden_saffron_destruct": "将该卡牌返还到手牌中.",
    "e_eden_saffron": "将抽牌堆中随机<uadd>[</><key> {0} </><uadd>]</>张<key>.edx</>卡牌添加到手牌中.",
    "e_eden_selicy": "当该卡牌造成伤害时，该卡牌发动一次攻击.",
    "e_eden_sharedatkcondition": "当回合抽牌倒计时不高于<key> {0} </>点时，解除限制。当该卡牌被放置到我方场地上时，增加回合抽牌倒计时<key> {1} </>点.",
    "e_eden_sharedattacking": "当另一张等级不低于<key> 1 </>级的卡牌的 <img id=\"\"effect_init\"\"/> 初始化效果在该卡牌所在列触发时，该卡牌将代替其触发。若那张卡牌是<key>.edx</>卡牌，则<decompile>反编译</>那张卡牌并抽取一张卡牌.",
    "e_eden_shiso_kill": "当该卡牌摧毁一张卡牌时，抽取一张卡牌.",
    "e_eden_shiso": "当该卡牌造成伤害时，该卡牌获得一个<attack> {0} </>点<specialbuff>一次性、衰减性的攻击力增益</>(攻击力增加上限：+<attack> {1} </>点).",
    "e_eden_shopkeeper_damage": "当该卡牌造成伤害时，触发洗牌.",
    "e_eden_shopkeeper": "选择抽牌堆中随机<key> {0} </>张卡牌中的一张，将<key> {1} </>张所选卡牌的复制品添加到抽牌堆顶端.",
    "e_eden_stepslash": "对前方一张敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害。若该卡牌在后排，则将其移动到前排(若前排已经有一张卡牌，则与其交换位置)，然后对该卡牌前方第<key> 1 </>格的一张敌方卡牌造成<uadd>[</><physical> {1} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_eden_terra_pull": "当该卡牌造成伤害时，若目标在后排且前面没有卡牌，则将其移动到前排.",
    "e_eden_terra": "增加该卡牌造成的伤害<uadd>[</><key> {0} </><uadd>]</>点.",
    "e_eden_thunder": "对前方第<key> 2 </>格的一张敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_eden_violette_boost": "当该卡牌拥有至少<key> {0} </>个计数点时，若其触发一个效果，则消耗所有计数点并再次触发那个效果.",
    "e_eden_violette": "当该卡牌移动时，根据该卡牌最后移动的方向触发一个效果(对角线移动不计入计算)。向上：该卡牌发动一次攻击；向下：治疗其生命值<health> {0} </>点；向左或向右：该卡牌获得<key> 1 </>计数点(最大计数点个数：<key> {1} </>个).",
    "e_eden_violette_upgrade": "当该卡牌移动时，该卡牌获得<key> 1 </>计数点(最大计数点个数：<key> {1} </>个)，并根据该卡牌最后移动的方向触发一个效果。向上：该卡牌发动一次攻击；向下：治疗其生命值<health> {0} </>点.",
    "e_eden_wave": "对前方一张敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害。当目标在前排且后面没有卡牌时，将其移动到后排并对其造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害；当目标在后排且前面没有卡牌时，将其移动到前排.",
    "e_fantasy_arae": "该卡牌攻击后，目标卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个)。当该卡牌所在列的敌方卡牌拥有计数点时，根据那张卡牌拥有的计数点数目，等量增加其受到的伤害(最大额外伤害为：<uadd>[</><attack>+ {0} </><uadd>]</>点).",
    "e_fantasy_cock": "对所有敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害并延迟其行动<key> {1} </>回合.",
    "e_fantasy_cockcondition": "当所有敌方卡牌的行动倒计时总和不低于<key> {0} </>时，解除限制(当前对方所有卡牌的行动倒计时总和/需要的敌方卡牌的行动倒计时总和：{1}/{0}).",
    "e_fantasy_griffin": "当场地上与该卡牌不同名的其他我方卡牌将受到超过<key> 1 </>点伤害时，该卡牌将代替其承受伤害.",
    "e_fantasy_mermaid": "当弃牌堆中不存在同名的卡牌时，丢弃抽牌堆顶端的<key> {0} </>张卡牌并抽取<uadd>[</><key> {1} </><uadd>]</>张卡牌.",
    "e_fantasy_mermaidcondition": "当弃牌堆中至少有<key> {0} </>张不同名的卡牌时，解除限制.",
    "e_fantasy_phoenix": "将该卡牌从弃牌堆中返还到手牌中.",
    "e_fantasy_unicorn": "当场地上生命值大于<health> 1 </>点的所有我方卡牌受到致命伤害时，保留其<health> 1 </>点生命值.",
    "e_generic_afterburner": "抽取卡牌至手牌中卡牌数目为<uadd>[</><key> {0} </><uadd>]</>张.",
    "e_generic_avarice": "选择弃牌堆中的<key> {0} </>张牌，将其洗入抽牌堆中并抽取<uadd>[</><key> {1} </><uadd>]</>张卡牌.",
    "e_generic_battery": "触发<key>回合抽牌</>.",
    "e_generic_beartrap": "仅当该卡牌位于弃牌堆中时，该效果可被触发。触发后，延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合并对其造成<uadd>[</><magic> {1} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后<void>放逐</>该卡牌.",
    "e_generic_cinder": "延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_generic_constantcorrection": "选择场地上一张我方卡牌，移除其所有效果和属性修正，并将其属性设置为<uadd>[</><attack>{0}</>|<health>{0}</><uadd>]</>.",
    "e_generic_crystalball": "选择抽牌堆中一张属性与抽牌堆顶端卡牌相同的卡牌，将其添加到手牌中并洗牌.",
    "e_generic_doubleexecute_extra": "将该卡牌从弃牌堆中返还到手牌中.",
    "e_generic_doubleexecute": "执行场地上所有我方卡牌.",
    "e_generic_ember": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_generic_fireball": "对前方一张敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_flash": "根据目标的回合倒计时，对前方一张敌方卡牌造成等量的魔法伤害.",
    "e_generic_flashbang": "摧毁该卡牌并延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_generic_force": "对前方一张敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害并将其移动到后排(若后排已经有一张卡牌，则交换它们的位置).",
    "e_generic_giveandtake_1": "当该卡牌没有计数点时，若场地上有卡牌将受到伤害时，则将其受到的伤害降低至<key> 0 </>点。并根据降低的伤害数目，该卡牌获得等量的计数点(最大计数点数目：<uadd>[</><key> {0} </><uadd>]</>个)。忽略已经受到 <key>DamageCapacitor</> 影响的伤害(场上有多张此卡存在，互不影响彼此的效果).",
    "e_generic_giveandtake_2": "当该卡牌拥有计数点时，若场地上有卡牌将受到伤害时，则消耗所有计数点并根据消耗的计数点数目等量增加其受到的伤害。忽略已经受到 <key>DamageCapacitor</> 影响的伤害(场上有多张此卡存在，互不影响彼此的效果).",
    "e_generic_giveandtake_3": "刷新该卡牌上所有的 <img id=\"\"effect_once\"\"/> 一次性效果.",
    "e_generic_gravity": "Draw1card，plus1additionalcardforeveryothercopyof<key>Gravity</>inyourtrash(willcurrentlydraw<key> {0} </>card(s)total).",
    "e_generic_inferno": "当该卡牌位于场地上时，若你放置一张卡牌，则对场地上其他的所有卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_magicember": "<decompile>反编译</>场地上属性为<attack>0</>|<health>1</>所有的我方卡牌，并抽取等同于<decompile>反编译</>的卡牌数目的卡牌(当前抽取卡牌数目：<key> {0} </>张).",
    "e_generic_magicflare": "<decompile>反编译</>场地上属性为<attack>0</>|<health>1</>的所有我方卡牌，并对所有敌方卡牌造成等同于<decompile>反编译</>的卡牌数目的 <img id=\"\"dmg_magic\"\"/> 魔法伤害(当前伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_generic_megarush": "当角色生命值为<health> 1 </><img id=\"\"player_health\"\"/> 时，增加场地上所有我方卡牌的攻击力<uadd>[</><attack> {0} </><uadd>]</>点并摧毁该卡牌.",
    "e_generic_omen": "当另一张卡牌的效果触发时，增加该卡牌的攻击力<attack> {0} </>点(攻击力增加上限：+<uadd>[</><attack> {1} </><uadd>]</>点)，攻击后重置其攻击力.",
    "e_generic_pendulum": "当该卡牌位于手牌中时，若即将受到 <img id=\"\"player_health\"\"/> 角色生命值伤害，则将该卡牌放置到我方场地上并降低受到的 <img id=\"\"player_health\"\"/> 角色生命值伤害至<key> 1 </><img id=\"\"player_health\"\"/> (但不会降低受到的其他 <img id=\"\"player_health\"\"/> 角色生命值伤害)，然后延迟所有敌人的行动<uadd>[</><key> {0} </><uadd>]</>回合。本回合内，将场地上所有我方卡牌受到的伤害降低至<key> 0 </>点.",
    "e_generic_pureheart": "当手牌中卡牌数目为<key> 0 </>时，抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_generic_pureheart_condition": "当手牌中只有该卡牌时，解除限制.",
    "e_generic_reincarnation": "选择弃牌堆中的一张卡牌，将其返还到手牌中(除了 <key>Reincarnation</> ).",
    "e_generic_ambush_play": "对<cover>被掩护的</>所有敌方卡牌造成<uadd>[</><physical> {0} </><uadd>]</><img id=\"\"dmg_phys\"\"/> 物理伤害并延迟其行动<uadd>[</><key> {1} </><uadd>]</>回合.",
    "e_generic_rupture": "选择场地上一张卡牌并对其造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后对另一方场地上的所有卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_scalpel": "该卡牌攻击时，若目标卡牌生命值不高于<uadd>[</><health> {0} </><uadd>]</>点，则<decompile>反编译</>目标与该卡牌，并将抽牌堆顶端的卡牌放置到该卡牌所在的位置(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_generic_shatter": "选择场地上一张我方卡牌，对其造成等同于所选卡牌的<health>最大生命值</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>，然后对所有敌方卡牌造成等同于所选卡牌的生命值的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>.",
    "e_generic_shatter_upgrade": "选择场地上<uadd>[</>至多两张<uadd>]</>我方卡牌，并对其造成等同于其<health>最大生命值</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>。然后对所有敌方卡牌造成等同于所选卡牌的<health>生命值总和</>的 <img id=\"\"dmg_magic\"\"/> <magic>魔法伤害</>.",
    "e_generic_solarflare": "对前方一张敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_spark": "选择场地上一张已激活的我方卡牌，重新激活所选卡牌(除了 <key>Spark</> ).",
    "e_generic_taser": "当该卡牌造成 <img id=\"\"dmg_phys\"\"/> 物理伤害时，延迟目标卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合。若目标抵抗了延迟，则额外对其造成<uadd>[</><key> {1} </><uadd>]</>次<magic> 1 </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_generic_taunt": "Haste all cards by {0} turns，and for the remainder of this turn，direct damage is reduced to 0.",
    "e_generic_thunderclap": "延迟该卡牌前方的一张敌方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合，然后将一张 <key>'Flash'</> 卡牌添加到抽牌堆顶端并将回合抽牌倒计时设置为<key> 0 </>点.",
    "e_generic_treasure": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌并将抽牌倒计时设置为<key> {1} </>点.",
    "e_generic_updraft": "选择场地上一张我方卡牌，将其返还到手牌中(除了 <key>Updraft</> ).",
    "e_infinitenavigation": "当该卡牌被放置到场地上时，选择一条新的路线并打开卡组编辑器。当该卡牌被从场地上移除时，路线开始.",
    "e_mage_aurelia_add": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其返还到手牌中.",
    "e_mage_aurelia_hand": "选择手牌中一张我方卡牌，将其洗入抽牌堆中并抽取一张卡牌.",
    "e_mage_camilla": "选择场地上攻击为<attack> 0 </>且至少有一个 <img id=\"\"effect_init\"\"/> 初始化效果的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的一张我方卡牌，将其移除到弃牌堆中。然后将其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果添加到该卡牌上，并将其设置为 <img id=\"\"effect_manual\"\"/> 主动技能效果(附带 <img id=\"\"effect_once\"\"/> 一次性和 <img id=\"\"effect_gunique\"\"/> 高级独一性模组).",
    "e_mage_decima_condition": "当弃牌堆中恰好有<key> {0} </>张 <key>.sorc</> 卡牌时，解除限制.",
    "e_mage_decima_init": "丢弃手牌中所有卡牌，每丢弃一张卡牌，该卡牌获得<key> 1 </>个计数点。然后将弃牌堆中所有的 <key>.sorc</> 卡牌返还到手牌中.",
    "e_mage_decima_trigger": "当该卡牌拥有计数点时，若你放置一张攻击力为<attack> 0 </>点的卡牌，则消耗<key> 1 </>个计数点并增加手牌中攻击力为<attack> 0 </>点的所有卡牌<health> 1 </>点生命值，然后抽取一张卡牌.",
    "e_mage_lucia_discard": "丢弃手牌中的一张卡牌，并对前方的一张敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mage_lucia_search": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其添加到手牌中.",
    "e_mage_mariana_ability": "当该卡牌前方有一张等级不高于<uadd>[</><key> {1} </><uadd>]</>级的我方卡牌时，将那张卡牌洗入抽牌堆中并增加前排所有我方卡牌的生命值<health> {0} </>点(该效果不可叠加).",
    "e_mage_mariana_init": "将该卡牌左右两侧的卡牌返还到手牌中.",
    "e_mage_mariana_movement": "当该卡牌移动到场地上其他位置时，刷新该卡牌所有 <img id=\"\"effect_once\"\"/> 一次性效果.",
    "e_mage_mariana_movement_upgrade": "当该卡牌移动到场地上其他位置时，刷新该卡牌所有 <img id=\"\"effect_once\"\"/> 一次性效果<uadd>[</>并重新激活该卡牌<uadd>]</>.",
    "e_mage_octavia_ability": "当该卡牌前方有一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的我方卡牌时，触发其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果(无视其限制)并将那张卡牌洗入抽牌堆中.",
    "e_mage_octavia_init": "选择手牌中一张我方卡牌，增加其生命值<health> 1 </>点.",
    "e_mage_sharedadder": "当该卡牌进入到手牌中时，<uminus>[</>增加其<health> 1 </><uminus>]</>点<health>最大生命值</>(最大生命值上限：<uadd>[</><health> {0} </><uadd>]</>点).",
    "e_mage_sharedadder_upgrade": "当该卡牌进入到手牌中时，其<health>最大生命值</><uadd>[</>提高至<key> 2 </><uadd>]</>倍(最大生命值上限：<uadd>[</><health> {0} </><uadd>]</>点).",
    "e_mage_sorccreo": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，抽取<key> X </>张卡牌。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前抽取卡牌数目：<key> {0} </>张).",
    "e_mage_sorceffingo": "选择弃牌堆中至少有一个 <img id=\"\"effect_init\"\"/> 初始化效果的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的一张 <key>.sorc</> 卡牌(除了 <key>Effingo.sorc</> )，将其洗入抽牌堆中并将其最左边的 <img id=\"\"effect_init\"\"/> 初始化效果作为这张卡的效果触发(无视效果限制)，然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点.",
    "e_mage_sorcgravitas": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，对所有敌方卡牌造成<magic> X </><uminus>[</><magic>- {1} </><uminus>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_mage_sorcgravitas_upgrade": "根据场地上该卡牌的所有同名卡的<health>生命值总和</>(<key> X </>点)，对所有敌方卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/> 魔法伤害。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_mage_sorcignis": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，对前方一张敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><magic>+ X </><img id=\"\"dmg_magic\"\"/> 魔法伤害。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_mage_sorclux": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，选择弃牌堆中至多<key> X </>张等级不低于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mage</> 卡牌，将其返还到手牌中。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前返还的卡牌数目：<key> {1} </>张).",
    "e_mage_sorcpotentia": "重新激活该卡牌所在行的所有卡牌。并根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，令该卡牌所在行上所有卡牌获得一个<key> X </><attack>+ {0} </>点的<specialbuff>衰减性的攻击力增益</>(攻击力增加上限：+<attack> {2} </>点)。然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前攻击力增加量：+<attack> {1} </>点).",
    "e_mage_sorctempus": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，延迟所有敌方卡牌的行动<key> X </>回合，然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前延迟回合数目：<key> {1} </>回合).",
    "e_mage_sorctempus_upgrade": "根据场地上与该卡牌同名的所有卡牌的<health>生命值总和</>(<key> X </>点)，延迟所有敌方卡牌的行动<key> X </>+<uadd>[</><key> {0} </><uadd>]</>回合，然后将场地上与该卡牌同名的所有卡牌的<health>最大生命值</>设置为<health> 1 </>点(当前延迟回合数目：<key> {1} </>回合).",
    "e_mage_valeria_attack": "当该卡牌攻击时，触发其左右两侧等级不低于<key> 1 </>级的卡牌最左边的 <img id=\"\"effect_init\"\"/> 初始化效果(无视其限制).",
    "e_mage_valeria_condition": "丢弃手牌中的<key> {0} </>张卡牌，解除限制.",
    "e_mage_valeria_init": "选择抽牌堆中至多两张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.sorc</> 卡牌，将其放置到我方场地上.",
    "e_mdv_advancedsummon_plural": "当同一回合内恰好有<key> {0} </>张我方卡牌被摧毁时，若你没有放置一张卡牌，则解除限制.",
    "e_mdv_advancedsummon": "当同一回合内恰好有<key> {0} </>张我方卡牌被摧毁时，若你没有放置一张卡牌，则解除限制.",
    "e_mdv_axe_init": "对前方一张敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_mdv_axe_passive": "该卡牌获得<uadd>[</><key> {0} </><uadd>]</>倍的攻击力增长，且该卡牌攻击后，重置其攻击力。当该卡牌的攻击力将超过<uadd>[</><attack> {1} </><uadd>]</>点时，此次攻击力增长无效并对场地上其他的所有卡牌造成<physical> {2} </>点物理伤害.",
    "e_mdv_axe": "当该卡牌的攻击力低于<uadd>[</><attack> {1} </><uadd>]</>点时，增加其攻击力<attack> {0} </>点.",
    "e_mdv_core_init": "选择场地上一张我方的 <key>.mech</> 卡牌，增加其攻击力<uadd>[</><attack> {0} </><uadd>]</>点并对其造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_core": "选择场地上一张卡牌，对其造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_gatling_init": "该卡牌获得<uadd>[</><key> {0} </><uadd>]</>个计数点.",
    "e_mdv_gatling_passive": "当场地上一张我方卡牌被摧毁时，该卡牌获得<uadd>[</><key> {0} </><uadd>]</>个计数点(最大计数点个数：<uadd>[</><key> {1} </><uadd>]</>).",
    "e_mdv_gatling": "消耗该卡牌所有的计数点。每消耗<key> 1 </>个计数点，该卡牌发动一次攻击(当前攻击次数：<key> {0} </>次).",
    "e_mdv_hammer_init": "对场地上其他的所有卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_mdv_hammer": "对场地上生命值不高于该卡牌攻击力的所有卡牌造成等同于该卡牌攻击力的 <img id=\"\"dmg_phys\"\"/> 物理伤害(包括该卡牌).",
    "e_mdv_hydro_init": "丢弃抽牌堆顶端的卡牌，然后选择弃牌堆顶端的<uadd>[</><key> {0} </><uadd>]</>张卡牌中至多两张<key> {1} </>级的 <key>.mech</> 卡牌，将其放置到场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_mdv_hydro": "选择场地上的一张我方卡牌，将其返还到手牌中.",
    "e_mdv_plasma_blast": "当场地上一张卡牌被摧毁时，该卡牌获得<key> 1 </>个计数点。当该卡牌的计数点不低于<key> {0} </>个时，消耗所有的计数点并对该卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_plasma": "对该卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mdv_podeffect": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级且至少有<key> 1 </>点攻击力的 <key>.mech</> 卡牌，摧毁该卡牌并将所选卡牌放置到该卡牌所在的位置，然后对其他所有卡牌造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_mdv_rocket": "当该卡牌位于手牌中时，若场地上一张我方卡牌被摧毁，该卡牌获得<key> 1 </>个计数点(最大计数点个数：<key> {0} </>个).",
    "e_mdv_rocketdamage": "当该卡牌被放置到场地上时，消耗<key> 1 </>个计数点并对所有敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害。重复该效果直到耗尽所有的计数点(当前物理伤害：<physical> {0} x {1} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mdv_signal": "当我方卡牌受到来自我方卡牌的伤害时，将该伤害降低至<key> 0 </>点并重新激活受到伤害的卡牌(除了 <key>CommandTower</> ).",
    "e_mdv_signal_upgrade": "当我方卡牌受到来自我方卡牌的伤害时，将该伤害降低至<key> 0 </>点并重新激活受到伤害的卡牌(除了 <key>CommandTower</> )<uadd>[</>然后根据受到的伤害量等量治疗受到伤害的卡牌<uadd>]</>.",
    "e_mdv_spear_init": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mech</> 卡牌，将其添加到手牌中(除了 <key>Spear.mech</> ).",
    "e_mdv_sword_init": "对前方一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_mdv_sword": "根据该卡牌的攻击力的一半(向下取整)，发动两次攻击并对前方的一张敌方卡牌造成等量的物理伤害(当前伤害：<physical> {0} x 2 </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mdv_thunder_init": "对所有敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_thunder": "选择场地上一张卡牌并对其造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mdv_unity_condition": "当场地上恰好有<key> {0} </>张我方的 <key>.mech</> 卡牌时，解除限制(当前场地上我方 <key>.mech</> 卡牌数目/所需的 <key>.mech</> 卡牌数目：{1}/{0}).",
    "e_mdv_unity": "触发场地上所有我方卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_muse_bass_group": "与该卡牌同时被执行的卡牌将根据其生命值等量增加其各自的攻击力(不包括该卡牌).",
    "e_muse_bass": "增加与该卡牌放置于同一行的卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_muse_doubleeigth": "发动两次攻击并对前方的敌方卡牌造成<uadd>[</><physical> {0} </><uadd>]</><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_muse_equalize": "丢弃手牌中一张卡牌，抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_executemanualshared": "选择场地上的一张我方卡牌，将其执行并抽取一张卡牌.",
    "e_muse_fermata": "与该卡牌一起执行的卡牌将被保留到场地上(除了 <key>Fermata.muse</> ).",
    "e_muse_forte": "增加该卡牌所在行上所有 <key>.muse</> 卡牌的攻击力<uadd>[</><key> {0} </><uadd>]</>点.",
    "e_muse_idol1_init": "选择弃牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol1_init_upgrade": "选择弃牌堆中一张等级不高于<uadd>[</><key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol2_init": "选择抽牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol2_init_upgrade": "选择抽牌堆中一张等级不高于<uadd>[</><key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol2": "选择场地上的一张我方卡牌，将其执行并抽取一张卡牌.",
    "e_muse_idol3_init": "丢弃手牌中所有<key> 1 </>级的 <key>.muse</> 卡牌，并根据丢弃的卡牌数目抽取等量的卡牌.",
    "e_muse_idol3_manual": "选择弃牌堆中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到我方场地上(其效果附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_muse_idol3_manual_upgrade": "选择弃牌堆中一张等级不高于<uadd>[</><key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到我方场地上(其效果附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_muse_idol4_init": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_idol4": "选择手牌中一张<key> 1 </>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol4_upgrade": "选择手牌中一张等级不高于<uadd>[</><key> 2 </><uadd>]</>级的 <key>.muse</> 卡牌，将其放置到我方场地上.",
    "e_muse_idol5_passive": "每抽取一张卡牌，便增加该卡牌的攻击力<uadd>[</><attack> {1} </><uadd>]</>点(当前攻击力增加量：+<attack> {2} </>点)(攻击力增加上限：+<uadd>[</><attack> {0} </><uadd>]</>点)，攻击后重置该卡牌攻击力.",
    "e_muse_idol5": "执行该卡牌左右两侧的卡牌。每执行一张卡牌抽取一张卡牌.",
    "e_muse_idolboss_condition": "丢弃手牌中一张卡牌，解除限制.",
    "e_muse_idolboss_init": "场地上所有我方卡牌获得<key> 1 </>个计数点.",
    "e_muse_idolboss_passive": "当拥有计数点的卡牌被执行时，消耗<key> 1 </>计数点并保留被执行的卡牌.",
    "e_muse_piano": "增加所有我方卡牌<uadd>[</><health> {0} </><uadd>]</>点<health>最大生命值</>.",
    "e_muse_quarter": "对前方一张敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_muse_quarterrest": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_muse_treble_group": "根据与该卡牌同时被执行的卡牌数目抽取等量的卡牌(不包括该卡牌).",
    "e_muse_treble": "增加与该卡牌放置于同一行的卡牌的攻击力<uadd>[</><attack> {0} </><uadd>]</>点.",
    "e_muse_triplet": "对所有敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_natural_apple": "将抽牌堆中<key> 1 </>张与该卡牌同名的卡牌添加到手牌中.",
    "e_natural_apple_upgrade": "将抽牌堆<uadd>[</><key> 2 </><uadd>]</>张与该卡牌同名的卡牌添加到手牌中.",
    "e_natural_banana": "选择弃牌堆中一张<key> 1 </>级的<uminus>[</> <key>.fruit</> <uminus>]</>卡牌，将其放置到我方场地上(不包括与该卡牌同名的卡牌).",
    "e_natural_banana_upgrade": "选择弃牌堆中一张<key> 1 </>级的卡牌，将其放置到我方场地上(不包括与该卡牌同名卡的卡牌).",
    "e_natural_cherry": "抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_natural_demeter_condition": "当弃牌堆中至少有<key> {0} </>张同名的<key> 1 </>级 <key>.fruit</> 卡牌时，解除限制(当前弃牌堆中同名的 <key>.fruit</> 卡牌数目/需要的 <key>.fruit</> 卡牌数目：{1}/{0}).",
    "e_natural_demeter_trigger": "当手牌中一张卡牌被放置到我方场地上时，对前方一张敌方卡牌造成等同于该卡牌攻击力的魔法伤害.",
    "e_natural_demeter": "选择弃牌堆中的一张卡牌，将弃牌堆中与所选卡牌同名的所有卡牌添加到手牌中.",
    "e_natural_fall": "移除场地上所有<key> 1 </>级 <key>.fruit</> 卡牌上的效果。每移除一张卡牌的效果便抽取一张卡牌.",
    "e_natural_fall_upgrade": "移除场地上所有<key> 1 </>级 <key>.fruit</> 卡牌上的效果。每移除一张卡牌的效果便抽取一张卡牌<uadd>[</>同时增加被移除效果的卡牌的攻击力<attack> 1 </>点<uadd>]</>.",
    "e_natural_greenhouse": "当一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌被放置到该卡牌后面时，将弃牌堆中与那张卡牌同名的一张卡牌返还到手牌中(不包括<key>Greenhouse</>).",
    "e_natural_growth": "选择弃牌堆中一张<uminus>[</> <key>.fruit</> <uminus>]</>卡牌，将弃牌堆中与所选卡牌同名的所有卡牌洗入牌库并根据洗入牌库的卡牌数目抽取等量的卡牌.",
    "e_natural_growth_upgrade": "选择弃牌堆中的一张卡牌，将弃牌堆中与所选卡牌同名的所有卡牌洗入牌库并根据洗入牌库的卡牌数目抽取等量的卡牌.",
    "e_natural_lemon": "场地上与该卡牌同名的所有我方卡牌发动一次攻击.",
    "e_natural_persephone_condition": "当场地上至少有<key> 3 </>张不同名的我方的<key> 1 </>级 <key>.fruit</> 卡牌时，解除限制(当前己方场地上不同名的卡牌数目/所需的不同名的卡牌数目：{1}/{0}).",
    "e_natural_persephone_init": "<void>放逐</>场地上所有我方卡牌。每<void>放逐</>一张卡牌，增加该卡牌<attack> 2 </>点攻击力.",
    "e_natural_persephone_passive": "该卡牌攻击后，降低该卡牌的攻击力 {0} 点并对所有敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_natural_pollination": "丢弃抽牌堆中至少有一个效果的一张<key> 1 </>级 <key>.fruit</> 卡牌，将其最左边的效果添加到手牌中所有<key> 1 </>级<uminus>[</> <key>.fruit</> <uminus>]</>卡牌上(每张卡所拥有的效果不能超过<key> 3 </>个)(附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_natural_pollination_upgrade": "丢弃抽牌堆中至少有一个效果的一张<key> 1 </>级 <key>.fruit</> 卡牌，将其最左边的效果添加到手牌中所有<key> 1 </>级卡牌上(每张卡所拥有的效果不能超过<key> 3 </>个)(附带 <img id=\"\"effect_once\"\"/> 一次性).",
    "e_natural_pomegranate": "当该卡牌进入弃牌堆中时，对所有敌方卡牌造成<uadd>[</><magic> {0} </><uadd>]</><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_natural_pomegranate_upgrade": "当该卡牌进入弃牌堆中时，对所有<expose>暴露的</>敌方卡牌造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害并对所有<cover>被掩护的</>敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害<uadd>]</>.",
    "e_natural_pumpkin_trigger": "该卡牌攻击后，将其移除到弃牌堆中.",
    "e_natural_pumpkin": "增加场地上与该卡牌同名的所有卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_natural_spring": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.fruit</> 卡牌(除了 <key>Spring.fruit</> )，将一张所选卡牌的复制品放置到我方场地上。弃牌堆中每有一张与所选卡牌同名的卡牌，增加复制品的攻击力<attack> 1 </>点(攻击力增加上限：+<attack> {1} </>点).",
    "e_natural_summer": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.fruit</> 卡牌，将其添加到手牌中(除了 <key>Summer.fruit</> ).",
    "e_natural_winter": "选择抽牌堆中一张 <key>.fruit</> 卡牌，丢弃抽牌堆中与所选卡牌同名的所有卡牌。每丢弃一张卡牌，便治疗场地上所有我方卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点(除了 <key>Winter.fruit</> ).",
    "e_potionhealth": "治疗<uadd>[</><health> {0} </><uadd>]</><img id=\"\"player_health\"\"/> 角色生命值.",
    "e_potionstorage": "增加卡牌存储空间<uadd>[</><key> {0} </><uadd>]</>格(最多增加的空间格数：+<key> {1} </>格)(当前增加的空间格数：+<key> {2} </>格).",
    "e_potionvoid": "<void>放逐</>场地上等级不高于<key> {0} </>级的所有敌方卡牌.",
    "e_sakura_bow": "发动一次攻击并对前方的一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_sakura_katana": "该卡牌发动一次攻击.",
    "e_sakura_kunai": "对所有敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害.",
    "e_sakura_lantern": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.hana</> 卡牌，将其添加到手牌中(除了 <key>Lantern.hana</> ).",
    "e_sakura_ninja1": "触发该卡牌后面的一张 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja2": "选择手牌中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.hana</> 卡牌，将其放置到我方场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_sakura_ninja3_adder": "当该卡牌被添加到或被返还到手牌中时，将其放置到我方场地上(无视 <img id=\"\"effect_condition\"\"/> 条件限制).",
    "e_sakura_ninja3_condition": "丢弃一张卡牌，解除限制.",
    "e_sakura_ninja3": "选择弃牌堆中恰好拥有一个 <img id=\"\"effect_manual\"\"/> 主动技能或者 <img id=\"\"effect_init\"\"/> 初始化效果的一张<key> 1 </>级卡牌，将其效果作为该卡牌的初始化效果触发(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja3_upgrade": "选择弃牌中恰好拥有一个 <img id=\"\"effect_manual\"\"/> 主动技能或者 <img id=\"\"effect_init\"\"/> 初始化效果的一张<key> 1 </>级卡牌，将其效果设置为该卡牌的初始化效果触发<uadd>[</>两次<uadd>]</>(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_ninja4": "将该卡牌左右两侧的等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能效果添加到该卡牌上(若目标有多个主动技能，则只能获得一个).",
    "e_sakura_ninjaboss_condition": "<decompile>反编译</>场地上一张我方的 <key>Bloom.hana</> 卡牌和一张我方的<key> 2 </>级的 <key>.hana</> 卡牌，解除限制.",
    "e_sakura_ninjaboss": "触发该卡牌左右两侧的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_priestess_condition": "当场地上恰好有<key> {0} </>张已触发附带 <img id=\"\"effect_once\"\"/> 一次性的 <img id=\"\"effect_manual\"\"/> 主动技能的我方卡牌时，解除限制.",
    "e_sakura_priestess": "重新激活场地上所有我方卡牌并刷新其 <img id=\"\"effect_once\"\"/> 一次性效果，然后延迟所有敌方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_sakura_shide": "选择场地上一张我方的 <key>.hana</> 卡牌，将其返还到手牌中并刷新其 <img id=\"\"effect_once\"\"/> 一次性效果，<uminus>[</>若返还了一张卡牌则<uminus>]</>抽取一张卡牌(除了 <key>Shide.hana</> ).",
    "e_sakura_shide_upgrade": "选择场地上一张我方的 <key>.hana</> 卡牌，将其返还到手牌中并刷新其 <img id=\"\"effect_once\"\"/> 一次性效果，然后抽取一张卡牌(除了 <key>Shide.hana</> ).",
    "e_sakura_storm": "触发场地上<uminus>[</>该卡牌所在行<uminus>]</>的我方的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_storm_upgrade": "触发场地上所有我方的 <key>.hana</> 卡牌的 <img id=\"\"effect_manual\"\"/> 主动技能效果(无视 <img id=\"\"effect_once\"\"/> 一次性限制).",
    "e_sakura_torii_condition": "<decompile>反编译</>场地上一张我方的 <key>.hana</> 卡牌，解除限制.",
    "e_sakura_torii": "将该卡牌后面的一张卡牌造成的通过该卡牌的伤害提升至<uadd>[</><key> {0} </><uadd>]</>倍(不包括群体攻击).",
    "e_spdeckedit_manual": "将该卡牌从弃牌堆中洗入抽牌堆中.",
    "e_spdeckedit": "打开卡组编辑器。完成编辑后，将重置我方场地并<key>重新加载</>所有卡牌.",
    "e_spdeckreload": "<key>重新加载</>所有卡牌(将弃牌堆、己方场上和手牌中的所有卡牌洗入抽牌堆并抽取新的手牌).",
    "e_spinstantdraft": "打开带有大量材料的卡组编辑器，编辑后<key>重新加载</>所有卡牌.",
    "e_spirit_amaterasu1": "当你触发<key>回合抽牌</>时，将场地上、手牌中和弃牌堆中所有的我方卡牌洗入抽牌堆中，然后抽取<key> {0} </>张卡牌并延迟所有敌方卡牌的行动<key> {1} </>回合.",
    "e_spirit_amaterasucondition": "当手牌中、抽牌堆、弃牌堆和场上的所有我方卡牌数目总和恰好为<key> {0} </>时，解除限制.",
    "e_spirit_amaterasumanual": "对场地上所有敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害并延迟其行动<key> {1} </>回合，然后洗牌并抽取新的手牌.",
    "e_spirit_bounce": "当该卡牌位于场地上时，若你触发<key>回合抽牌</>，则将其返还到手牌中.",
    "e_spirit_bouncecondition": "当恰好<key> {0} </>张场地上的卡牌被返还到手牌中时，解除限制.",
    "e_spirit_countcondition": "当场地上和手牌中的所有我方卡牌数目总和恰好为<key> {0} </>张时，解除限制(当前卡牌数目总和/所需卡牌数目总和：{1}/{0}).",
    "e_spirit_kitsunefield": "对场地上一张敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_spirit_kitsunehand": "仅当该卡牌位于手牌中时，该效果可被触发。触发后，丢弃手牌中与该卡牌同名的所有卡牌并根据丢弃的卡牌数目(<key> X </>张)，对所有敌方卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/> 魔法伤害(当前造成的魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_spirit_kusanagiattack": "对前方一张敌方卡牌造成等同于与该卡牌处于同一列的我方卡牌的生命值的魔法伤害(最大魔法伤害：<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>)(当前魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_spirit_kusanagibounce": "该卡牌将代替与该卡牌处于同一列的我方卡牌进入到抽牌堆中、手牌中或被移除到弃牌堆中(除了 <key>Kusanagi.spirit</> ).",
    "e_spirit_magatamacopy": "选择手牌中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.spirit</> 卡牌，将所选卡牌的一张属性为<attack>0</>|<health>1</>且移除所有效果的复制品添加到手牌中(除了 <key>Yasakani.spirit</> ).",
    "e_spirit_magatamadiscard": "丢弃手牌中的一张卡牌，并触发其所有位于手牌中时可触发的 <img id=\"\"effect_manual\"\"/> 主动技能效果，然后抽取一张卡牌.",
    "e_spirit_magatamastacking": "当一张卡牌被丢弃时，若该卡牌拥有不少于<key> {0} </>个计数点时，消耗所有计数并延迟所有敌方卡牌的行动<key> {1} </>回合；否则，该卡牌获得<key> 1 </>个计数点.",
    "e_spirit_nekofield": "丢弃手牌中的一张卡牌，并根据丢弃的卡牌的等级发动相同次数的攻击，然后抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_spirit_nekohand": "仅当该卡牌位于手牌中时，该效果可被触发。触发后，丢弃手牌中与该卡牌同名的所有卡牌，并根据丢弃的卡牌数目(<key> X </>张)，抽取<key> X </>张卡牌(当前抽取的卡牌总数：<key> {0} </>张).",
    "e_spirit_nezumifield": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.spirit</> 卡牌，将其返还到手牌中(除了 <key>Nezumi.spirit</> ).",
    "e_spirit_nezumihand": "当该卡牌位于手牌中时，若场地上一张卡牌被返还到手牌中(除了 <key>Nezumi.spirit</> )，则将该卡牌放置到我方场地上并发动一次攻击.",
    "e_spirit_sikafield": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.spirit</> 卡牌，将其放置到我方场地上.",
    "e_spirit_sikahand": "仅当该卡牌位于手牌中时，该效果可被触发。触发后，丢弃手牌中与该卡牌同名的所有卡牌，然后选择场地上有至少一个 <img id=\"\"effect_manual\"\"/> 主动技能效果的一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的我方的 <key>.spirit</> 卡牌，并根据丢弃的卡牌数目(<key> X </>张)，触发所选卡牌最左边的 <img id=\"\"effect_manual\"\"/> 主动技能效果<key> X </>次(当前触发次数：<key> {1} </>次).",
    "e_spirit_tanzakuinit": "该卡牌获得<key> {0} </>个计数点.",
    "e_spirit_tanzakumain": "当一张卡牌被放置到该卡牌所在行时，消耗<key> 1 </>个计数点并触发一次那张卡牌最左边的 <img id=\"\"effect_manual\"\"/> 主动技能.",
    "e_spirit_tanzakumanual": "该卡牌获得<uadd>[</><key> {0} </><uadd>]</>个计数点.",
    "e_spirit_tsukuyomibuff": "当一张卡牌被放置到我方场地上时，该卡牌获得<key> 1 </>个计数点，若该卡牌拥有<key> {0} </>个计数点，则消耗该卡牌上所有的计数点并触发被放置卡牌可以触发的所有 <img id=\"\"effect_manual\"\"/> 主动技能效果，然后增加其攻击力<attack> {1} </>点.",
    "e_spirit_tsurufield": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.spirit</> 卡牌(除了 <key>Tsuru.spirit</> )，将其放置到我方场地上.",
    "e_spirit_tsuruhand": "仅当该卡牌位于手牌中时，该效果可被触发。触发后，丢弃手牌中与该卡牌同名的所有卡牌，并根据丢弃的卡牌数目(<key> X </>张)，选择抽牌堆中至多<key> X </>张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.spirit</> 卡牌(除了 <key>Tsuru.spirit</> )，将其添加到手牌中(当前添加的卡牌总数：<key> {1} </>张).",
    "e_spirit_watatsumiattack": "当该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，根据场地上和手牌中所有我方卡牌的<attack>攻击力总和</>(<key> X </>点)，抽取<key> X </>张卡牌，然后移除所有卡牌所有的属性修正并将其<attack>攻击力</>降低到<attack> 0 </>点(当前抽取的卡牌总数：<key> {0} </>)(最多抽取卡牌数目：<key> {1} </>张)，然后将该卡牌洗入<uminus>[</>抽牌堆中<uminus>]</>.",
    "e_spirit_watatsumiattack_upgrade": "当该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，根据场地上和手牌中所有我方卡牌的<attack>攻击力总和</>(<key> X </>点)，抽取<key> X </>张卡牌，然后移除所有卡牌所有的属性修正并将其<attack>攻击力</>降低到<attack> 0 </>点(当前抽取的卡牌总数：<key> {0} </>)(最多抽取的卡牌数目：<key> {1} </>张)，然后将该卡牌返还到<uadd>[</>手牌中<uadd>]</>.",
    "e_spirit_watatsumihand": "仅当该卡牌位于手牌中且该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，该效果可被触发。触发后，丢弃手牌中所有卡牌并抽取<key> {1} </>张卡牌，然后根据丢弃卡牌的数目等量增加场地上所有我方卡牌的生命值(当前生命值增加量：+<health> {0} </>点).",
    "e_spirit_yamataattack": "当该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，根据场地上和手牌中所有我方卡牌的<attack>攻击力总和</>(<key> X </>点)，对所有敌方卡牌造成<key> X </>点魔法伤害，然后移除所有卡牌所有的属性修正并将其<attack>攻击力</>降低到<attack> 0 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> )(最大魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> )，然后将该卡牌洗入<uminus>[</>抽牌堆中<uminus>]</>.",
    "e_spirit_yamataattack_upgrade": "当该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，根据场地上和手牌中所有我方卡牌的<attack>攻击力总和</>(<key> X </>点)，对所有敌方卡牌造成<key> X </>点魔法伤害，然后移除所有卡牌所有的属性修正并将其<attack>攻击力</>降低到<attack> 0 </>点(当前魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> )(最大魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> )，然后将该卡牌返还到<uadd>[</>手牌中<uadd>]</>.",
    "e_spirit_yamatahand": "仅当该卡牌位于手牌中且该卡牌的 <img id=\"\"effect_condition\"\"/> 条件限制被解除时，该效果可被触发。触发后，丢弃手牌中所有的卡牌并抽取<key> {1} </>张卡牌，然后根据丢弃的卡牌数目，令场地上所有我方卡牌获得一个等量的<specialbuff>一次性的攻击力增益</>(当前攻击力增加量：+<attack> {0} </>点).",
    "e_spirit_yatainit": "重新激活场地上所有的我方卡牌.",
    "e_spirit_yatamanual": "选择手牌中攻击力高于<attack> 1 </>点且等级不高于<uadd>[</><key> {0} </><uadd>]</>级的一张 <key>.spirit</> 卡牌，将其放置到我方场地上.",
    "e_spstoragehit": "选择存储空间中的一张卡牌，将其添加到手牌中。若存储空间中没有卡牌，则抽取<key> 2 </>张卡牌.",
    "e_vamp_gen1_condition": "当场地上恰好拥有<key> {0} </>张攻击力相同的我方卡牌时，解除限制.",
    "e_vamp_gen1_init": "令场地上攻击力不低于<attack> 1 </>点的所有我方卡牌发动一次攻击，并将其他卡牌返还到手牌中.",
    "e_vamp_gen1_manual": "选择场地上的一张我方卡牌，若其攻击力不低于<attack> 1 </>点，则所选卡牌发动一次攻击，否则，将其返还到手牌中.",
    "e_vamp_gen2_condition": "当弃牌堆中恰好有<key> {0} </>张 <key>.blood</> 卡牌时，解除限制(当前弃牌堆中 <key>.blood</> 卡牌数目/需要的 <key>.blood</> 卡牌数目：{1}/{0}).",
    "e_vamp_gen2_groupattack": "令场地上生命值为<health> 1 </>点的所有我方卡牌发动一次攻击.",
    "e_vamp_gen2_manual": "选择弃牌堆中一张 <key>.blood</> 卡牌，将其<void>放逐</>并在场地上放置一个属性为<uadd>[</><attack>{0}</><uadd>]</>|<health>1</>的随从，然后重新激活该卡牌.",
    "e_vamp_hyper": "根据场地上所有我方卡牌的数目，对所有敌方卡牌造成等量的魔法伤害(最大魔法伤害：<magic> {0} </><img id=\"\"dmg_magic\"\"/> )(当前魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> )，然后对场地上所有我方卡牌造成<magic> 1 </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_vamp_lieu1": "根据该卡牌攻击力的一半(<key> X </>点)(向下取整)，选择抽牌堆中至多<key> X </>张等级不高于<key> {0} </>级的 <key>.legion</> 卡牌，将其添加到手牌中(当前添加的卡牌总数：<key> {1} </>张)，然后移除该卡牌所有的属性修正.",
    "e_vamp_lieu2": "根据该卡牌攻击力的一半(<key> X </>点)(向下取整)，选择抽牌堆中至多<key> X </>张等级不高于<key> {0} </>级的 <key>.blood</> 卡牌，将其添加到手牌中(当前添加的卡牌总数：<key> {1} </>张)，然后移除该卡牌所有的属性修正.",
    "e_vamp_lifesteal": "当该卡牌造成伤害时，治疗该卡牌的生命值<health> {0} </>点并增加其攻击力<attack> 1 </>点(攻击力增加上限：+<attack> {1} </>点)。当该卡牌受到伤害时，减少该卡牌的攻击力<attack> 1 </>点.",
    "e_vamp_orb_destruction": "抽取<key> 1 </>张卡牌.",
    "e_vamp_orb": "选择手牌中一张<uadd>[</><key> {0} </><uadd>]</>级或更低等级的 <key>.legion</> 卡牌，将其放置到我方场地上.",
    "e_vamp_origin": "<decompile>反编译</>场地上生命值为<health> 1 </>点的所有我方卡牌，并根据<decompile>反编译</>的卡牌数目(<key> X </>张)，选择弃牌堆中至多<key> X </>张不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.blood</> 卡牌(除了 <key>Origin.blood</> )(当前可选择的卡牌数目：<key> {1} </>张)，将其添加到手牌中.",
    "e_vamp_plunge_trigger": "当该卡牌位于手牌中时，若其一回合后仍未被放置到我方场地上，则丢弃该卡牌.",
    "e_vamp_plunge": "选择场地上生命值为<health> {0} </>点的一张卡牌(除了 <key>Plunge.blood</> )，将其摧毁并对场地上与被摧毁的卡牌同侧的所有卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后将该卡牌返还到手牌中.",
    "e_vamp_revival": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.legion</> 卡牌，将其放置到我方场地上.",
    "e_vamp_shield_revive": "当该卡牌位于弃牌堆中时，将其返还到到手牌中并移除其所有的属性修正，之后将其属性设定为<attack>0</>|<health>1</>.",
    "e_vamp_shield": "对该卡牌造成伤害的卡牌将受到<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_vamp_simpledamagefront": "对该卡牌前方第<key> 1 </>格的一张卡牌造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vamp_sol1": "当该卡牌位于场地上时，若其受到伤害且未被摧毁，则抽取<key> {0} </>张牌；否则，该效果无效.",
    "e_vamp_sol3": "当该卡牌位于场地上时，若其受到伤害且未被摧毁，则对<expose>暴露的</>所有敌方卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害；否则，该效果无效.",
    "e_vamp_spear_trigger": "当该卡牌位于场地上时，若其摧毁一张卡牌，则将其返还到手牌中.",
    "e_vamp_spear": "对该卡牌前方的一列卡牌造成<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害(包括我方卡牌)；若只有一张卡牌，则对其造成<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_vamp_surrounddamage": "对与该卡牌相邻的所有卡牌(除了对角线)造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vamp_sword_coattack": "当该卡牌所在列的另一张我方卡牌发动攻击时(除了 <key>Sword.blood</> )，该卡牌发动一次攻击.",
    "e_vamp_sword_credit": "该卡牌造成的伤害将被视作由该卡牌所在行的另一张卡牌造成.",
    "e_cross_ctroncharge": "当该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若一张卡牌被放置到我方场地上，则重新激活该卡牌且该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_ctronshot": "当该卡牌被激活时，若一张敌方卡牌受到伤害且未被摧毁，则对目标造成等同于该卡牌攻击力的魔法伤害并将该卡牌设置为未激活状态.",
    "e_cross_ctronbuff": "当该卡牌拥有计数点时，选择场地上一张我方卡牌(除了 <key>C'tron.cross</> )，将该卡牌拥有的计数点转移到所选卡牌上(最多转移的计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleheatburst": "消耗该卡牌和与该卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:对前方一张敌方卡牌造成<physical> 4 </><img id=\"\"dmg_phys\"\"/> 物理伤害{b}[<key> {1} +</>]:对前方一张敌方卡牌依次造成<physical> 2 </><img id=\"\"dmg_phys\"\"/> +<physical> 2 </><img id=\"\"dmg_phys\"\"/> +<physical> 4 </><img id=\"\"dmg_phys\"\"/> 物理伤害{b}{b}然后<decompile>反编译</>该卡牌并抽取一张卡牌.",
    "e_cross_eleheatpassive": "当场地上拥有<attack> 1 </>点或更多攻击力且与该卡牌<align>对齐的</>一张我方卡牌造成伤害时，若该卡牌拥有的计数点数目少于<uadd>[</><key> {0} </><uadd>]</>个，则对目标造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleheatplay": "重新激活与该卡牌<align>对齐的</>一张我方卡牌，并令那张卡牌获得一个<key> {0} </>点的<specialbuff>衰减性的攻击力增益</>.",
    "e_cross_elecoldburst": "消耗该卡牌和与该卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:延迟所有敌方卡牌的行动<key> 3 </>回合{b}[<key> {1} +</>]:延迟所有敌方卡牌的行动<key> 6 </>回合{b}{b}然后<decompile>反编译</>该卡牌并抽取一张卡牌.",
    "e_cross_elecoldpassive": "当场地上拥有<attack> 1 </>点或更多攻击力的且与该卡牌<align>对齐的</>一张我方卡牌被伤害时，若该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则对造成伤害的卡牌造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_elecoldplay": "重新激活与该卡牌<align>对齐的</>一张我方卡牌，并增加其生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_cross_eleshockburst": "消耗该卡牌和与该卡牌<align>对齐的</>卡牌上的所有计数点，并根据消耗的计数点数目触发效果：{b}{b}[<key> {0} +</>]:对前方一张敌方卡牌造成<magic> 2 </><img id=\"\"dmg_magic\"\"/> 魔法伤害并依次对与目标相邻的敌方卡牌造成等量的魔法伤害(不包括对角线){b}[<key> {1} +</>]:对前方一张敌方卡牌造成<magic> 4 </><img id=\"\"dmg_magic\"\"/> 魔法伤害并依次对与目标相邻的敌方卡牌造成等量的魔法伤害{b}{b}然后<decompile>反编译</>该卡牌并抽取一张卡牌.",
    "e_cross_eleshockpassive": "当场地上攻击力不低于<attack> 1 </>点且与该卡牌<align>对齐的</>一张我方卡牌造成伤害时，若该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则延迟目标的行动<key> {1} </>回合(若目标抵抗了延迟，则对其造成<magic> {2} </><img id=\"\"dmg_magic\"\"/> 魔法伤害)，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_eleshockplay": "若可能的话，将与该卡牌同列、同行的所有卡牌向该卡牌的方向移动一格.",
    "e_cross_elewaveburst": "消耗该卡牌和与该卡牌<align>对齐的</>卡牌上所有的计数点，并根据消耗的计数点数量触发效果：{b}{b}[<key> {0} +</>]:选择手牌中一张等级不高于<key> 2 </>级的卡牌，将其放置到到我方场地上，然后那张卡牌获得<key> 3 </>个计数点{b}[<key> {1} +</>]:选择手牌中两张等级不高于<key> 2 </>级的卡牌，将其放置到到我方场地上，然后那张卡牌获得<key> 3 </>个计数点{b}{b}然后<decompile>反编译</>该卡牌并抽取一张卡牌.",
    "e_cross_elewavepassive": "当场地上攻击力不低于<attack> 1 </>点且与该卡牌<align>对齐的</>一张我方卡牌造成伤害时，若该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个，则抽取一张卡牌，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_elewaveplay": "若可能的话，将与该卡牌同列、同行的所有卡牌向远离该卡牌的方向移动一格.",
    "e_cross_emilienatorcharge": "当该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若该卡牌在场地上移动，则重新激活该卡牌并对前方一张敌方卡牌造成<physical> 1 </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_emilienatorbeat": "消耗该卡牌所有的计数点。每消耗<key> 1 </>个计数点便对该卡牌前方第<key> 1 </>格的一张敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害。若目标抵抗了延迟，则对其造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_cross_emilienatordash": "当该卡牌被激活时，若一张敌方卡牌伤害且未被摧毁时，将该卡牌移动到与最后一张受到伤害的卡牌相同列的前排位置上(若已经有一张卡牌，则与其交换位置).",
    "e_cross_emilienatorplay": "抽取一张卡牌.",
    "e_cross_leacharge": "当该卡牌拥有的计数点数目少于<uadd>[</><key> {0} </><uadd>]</>个时，若该卡牌对一张卡牌造成物理伤害，则重新激活该卡牌，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_leashot": "当该卡牌拥有计数点时，消耗所有计数点，并根据消耗的计数点数目(<key> X </>点)，对场地上一张敌方卡牌造成<key> X </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_cross_leasearch": "选择抽牌堆中一张 <key>.element</> 卡牌，将其添加到手牌中.",
    "e_cross_counter_condition": "选择场地上<key> {0} </>张拥有计数点的我方卡牌，将其洗入抽牌堆中，然后将所选卡牌拥有的计数点转移到该卡牌上.",
    "e_cross_lukasslash": "消耗所有计数点，并根据消耗的计数点数目(<key> X </>点)，对该卡牌所在列上的所有敌方卡牌造成<magic> {0} X </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大魔法伤害：<uadd>[</><magic> {1} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>)(当前魔法伤害：<magic> {2} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_joernsearch": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其添加到手牌中(除了 <key>Joern.cross</> )，然后将该卡牌拥有的计数点转移到所选卡牌上(最多添加的计数点个数：+<uadd>[</><key> {1} </><uadd>]</>个).",
    "e_cross_apollocharge": "当该卡牌拥有的计数点少于<uadd>[</><key> {0} </><uadd>]</>个时，若我方卡牌受到伤害，则重新激活该卡牌，然后该卡牌获得<key> 1 </>个计数点(最大计数点个数：<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_apollosearch": "选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其返还到手牌中(除了 <key>Apollo.cross</> ).",
    "e_cross_hlinplay": "选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.cross</> 卡牌，将其放置到我方场地上.",
    "e_cross_hlindefense": "当该卡牌受到伤害时，则根据该卡牌拥有的计数点数目等量减少该卡牌受到的伤害，然后消耗该卡牌一半的计数点(向上取整)，并根据消耗的计数点数目(<key> X </>点)，令该卡牌获得一个<key> X </>点的<specialbuff>一次性的攻击力增益</>，然后该卡牌后面的一张卡牌获得<key> X </>个计数点(最多添加的计数点个数：+<uadd>[</><key> {0} </><uadd>]</>个).",
    "e_cross_buggyslash": "消耗所有计数点，并根据消耗的计数点数目(<key> X </>点)，对该卡牌正前方和左上角、右上角紧挨该卡牌的所有敌方卡牌造成<key> X </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大伤害次数：<uadd>[</><key> {1} </><uadd>]</>次)(当前伤害：<key> {2} </>次<magic> {0} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_albertplay": "根据该卡牌拥有的计数点数目(<key> X </>点)，对场地上至多<uadd>[</><key> {0} </><uadd>]</>张敌方卡牌造成<magic> X </><img id=\"\"dmg_magic\"\"/> 魔法伤害(最大魔法伤害：<magic> {1} </><img id=\"\"dmg_magic\"\"/> ).",
    "e_cross_albertfield": "当你将手牌中的一张卡牌放置到场地上时，将该卡牌的<key> 1 </>个计数点转移到被放置的卡牌上.",
    "e_cross_shizukacondition": "当该卡牌被放置到场地上时，将我方场地上所有卡牌拥有的计数点转移到该卡牌上。当我方场地上恰好有<key> {0} </>个计数点时，解除限制(当前计数点数目总和/需要的计数点数目总和：{1}/{0}).",
    "e_cross_shizukaplay": "对所有<expose>暴露的</>敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_cross_shizukaburst": "消耗该卡牌和与该卡牌同一列的卡牌上的所有的计数点，并根据消耗的计数点数目(<key> X </>点)，对前方一张敌方卡牌造成<physical> X </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前物理伤害：<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_mahou_bunny_fire_summon": "选择手牌中最左边的一张<key>Akane.mahou</>卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_fire_attack": "<decompile>反编译</>该卡牌，然后对一张卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mahou_girl_fire_proc": "当与该卡牌相邻的卡牌被移除到弃牌堆中且没有被摧毁时，该卡牌发动一次攻击(不包括对角线).",
    "e_mahou_girl_fire_summon": "选择弃牌堆中一张 <key>Kufi.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_earth_summon": "选择手牌中最左边的一张 <key>Chie.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_earth_attack": "<decompile>反编译</>该卡牌，然后选择最多<uadd>[</><key> {0} </><uadd>]</>张敌方卡牌并对其造成<magic> {1} </><img id=\"\"dmg_magic\"\"/> 魔法伤害.",
    "e_mahou_girl_earth_proc": "当与该卡牌相邻的卡牌被移除到弃牌堆中且没有被摧毁时，对和前方第一张敌方卡牌生命值相同的所有敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害(不包括对角线).",
    "e_mahou_girl_earth_summon": "选择弃牌堆中一张 <key>Kuea.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_water_summon": "选择手牌中最左边的一张 <key>Aoi.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_water_attack": "<decompile>反编译</>该卡牌，然后抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌.",
    "e_mahou_girl_water_proc": "当与该卡牌相邻的卡牌被移除到弃牌堆中且没有被摧毁时(不包括对角线)，将弃牌堆顶部等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌最左边的 <img id=\"\"effect_manual\"\"/> 主动技能效果作为该卡牌的效果触发(无视限制).",
    "e_mahou_girl_water_summon": "选择弃牌堆中一张 <key>Kuwa.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_wind_summon": "选择手牌中最左边的一张 <key>Kazane.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_wind_attack": "<decompile>反编译</>该卡牌，然后选择场地上至多<uadd>[</><key> {0} </><uadd>]</>张我方卡牌并将其返还到手牌中.",
    "e_mahou_girl_wind_proc": "当与该卡牌相邻的卡牌被移除到弃牌堆中且没有被摧毁时，选择手牌中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的卡牌，将其放置到我方场地上.",
    "e_mahou_girl_wind_summon": "选择弃牌堆中一张 <key>Kuwi.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_dark_summon": "选择手牌中最左边的一张 <key>Tsukiyo.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_dark_attack": "<decompile>反编译</>该卡牌，然后对所有敌方卡牌造成<uadd>[</><magic> {0} </><img id=\"\"dmg_magic\"\"/> <uadd>]</>魔法伤害.",
    "e_mahou_girl_dark_proc": "当该卡牌被激活时，若与该卡牌相邻的卡牌被移除到弃牌堆中且没有被摧毁，则选择弃牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌，将其返还到手牌中(除了 <key>Tsukiyo.mahou</> )，然后将该卡牌设置为未激活状态.",
    "e_mahou_girl_dark_summon": "选择弃牌堆中一张 <key>Kuda.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_light_summon": "选择手牌中最左边的一张 <key>Hoshiko.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_bunny_light_attack": "<decompile>反编译</>该卡牌，然后延迟所有敌方卡牌的行动<uadd>[</><key> {0} </><uadd>]</>回合.",
    "e_mahou_girl_light_proc": "当该卡牌被激活时，若与该卡牌相的卡牌被移除到弃牌堆中且没有被摧毁，则选择抽牌堆中一张等级不高于<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌，将其放置到我方场地上(除了 <key>Hoshiko.mahou</> )，然后将该卡牌设置为未激活状态.",
    "e_mahou_girl_light_summon": "选择弃牌堆中一张 <key>Kuli.mahou</> 卡牌，将其放置到我方场地上与该卡牌相邻的位置(不包括对角线).",
    "e_mahou_starwish": "丢弃抽牌堆中的一张卡牌，然后洗牌.",
    "e_mahou_hearttrial_init": "选择场地上一张我方卡牌，将所选卡牌的<key> {0} </>张没有效果且属性为<attack>0</>|<health>1</>的复制品添加到手牌中.",
    "e_mahou_hearttrial_field": "当一张卡牌被放置到我方场上时，<decompile>反编译</>其他的所有与被放置的卡牌同名的卡牌.",
    "e_mahou_starwish_active": "<decompile>反编译</>该卡牌，然后选择弃牌堆中一张<uadd>[</><key> {0} </><uadd>]</>级的 <key>.mahou</> 卡牌(除了 <key>Wish.mahou</> )，将其放置到该卡牌原来的位置上.",
    "e_mahou_girl_shared_tagout": "选择抽牌堆中与该卡牌不同名且等级不低于该卡牌的一张 <key>.mahou</> 卡牌，将该卡牌返还到抽牌堆中并将所选卡牌放置到该卡牌原来的位置上，然后将所选卡牌设置为未激活状态.",
    "e_vault_slash": "对前方一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害。若回合抽牌倒计时为<key> 0 </>点，则触发<key>回合抽牌</>并将一张 <key>Combo</> 卡牌添加到手牌中.",
    "e_vault_combo": "当该卡牌位于手牌中或场地上时，若一张攻击力不低于<attack> 1 </>点的<key>.vault</>卡牌触发 <img id=\"\"effect_init\"\"/> 初始化效果，则再次触发该效果并<void>放逐</>该卡牌(该效果不会由 <key>Combo</> 触发).",
    "e_vault_sharedredraw": "当该卡牌位于手牌中时，丢弃该卡牌，并减少回合抽牌倒计时<key> 1 </>点。若该手牌中只有该卡牌，则抽取<key> {0} </>张卡牌.",
    "e_vault_jab": "对前方一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>点物理伤害。若该伤害对一张敌方卡牌造成伤害，则抽取一张卡牌.",
    "e_vault_blade": "根据手牌牌中 <key>Combo</> 卡牌数目(<key> X </>张)，对前方一张敌方卡牌造成<key> X + 1 </>次<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害(当前伤害：<key> {1} </>次<physical> {0} </><img id=\"\"dmg_phys\"\"/> ).",
    "e_vault_apprentice": "将<uadd>[</><key> {0} </><uadd>]</>张 <key>HiddenBlade.vault</> 卡牌和一张 <key>Combo</> 卡牌添加到手牌中.",
    "e_vault_multiblade": "对前方一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害。若该伤害对一张敌方卡牌造成伤害，则将一张 <key>HiddenBlade.vault</> 卡牌添加到手牌中.",
    "e_vault_bide": "将<key> {0} </>张 <key>Combo</> 卡牌添加到手牌中.",
    "e_vault_agility": "将一张 <key>Combo</> 卡牌添加到手牌中.",
    "e_vault_char_edit": "当该卡牌离开场地时，造成等同于该卡牌损失的生命值的 <img id=\"\"player_health\"\"/> 角色生命值伤害，然后<key>编辑</>你的卡组并<key>重新加载</>我方卡牌(当前造成的 <img id=\"\"player_health\"\"/> 角色生命值伤害：<key> {0} </><img id=\"\"player_health\"\"/> ).",
    "e_vault_char_ping": "当该卡牌位于场地上或位于弃牌堆中时，该效果可被触发。触发后，延迟一张敌方卡牌的行动<key> {0} </>回合，并将一张 <key>HiddenBlade.vault</> 和一张 <key>Combo</> 添加到手牌中。若该卡牌位于弃牌堆中，则触发后再将其洗入抽牌堆中.",
    "e_vault_juggle": "丢弃手牌中的<key> 1 </>张卡牌，然后抽取<uadd>[</><key> {0} </><uadd>]</>张卡牌并将一张 <key>HiddenBlade.vault</> 卡牌添加到手牌中.",
    "e_vault_oncemore": "选择场地上一张<key> 1 级</>且具有一个 <img id=\"\"effect_init\"\"/> 初始化效果的我方卡牌，并对所选卡牌前方的一张敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害，然后触发所选卡牌最左侧的 <img id=\"\"effect_init\"\"/> 初始化效果(该效果不会在自身另一个复制品中被触发).",
    "e_vault_opportunist": "对所有敌方卡牌造成<physical> {0} </><img id=\"\"dmg_phys\"\"/> 物理伤害。若敌方卡牌的行动倒计时为<key> 0 </>点，则对其造成<physical> {1} </><img id=\"\"dmg_phys\"\"/> 物理伤害.",
    "e_vault_lightup": "对前方一张敌方卡牌造成<uadd>[</><physical> {0} </><img id=\"\"dmg_phys\"\"/> <uadd>]</>物理伤害。若该伤害对一张敌方卡牌造成伤害，则减少回合抽牌倒计时<key> 1 </>点.",
    "e_vault_parry": "治疗场地上所有我方卡牌的生命值<uadd>[</><health> {0} </><uadd>]</>点.",
    "e_vault_condition": "<decompile>反编译</>场地上<key> {0} </>张我方卡牌，解除限制.",
    "e_vault_condition_1_upgrade": "<decompile>反编译</>场地上<uadd>[</><key> {0} </><uadd>]</>张我方卡牌，解除限制.",
    "e_dmg_reduction": "将该卡牌受到的伤害减少<key> {0} </>点.",
    "e_deathcrave": "当该卡牌摧毁了一张卡牌时，重新激活该卡牌.",
    "e_undamagable": "将该卡牌受到的伤害降低至<key> 0 </>点.",
    "e_dmgcap": "该卡牌每次受到的伤害不会超过<key> {0} </>点.",
    "e_undamagable_physical": "将该卡牌受到的<physical>物理伤害</>降低至<physical> 0 </><img id=\"\"dmg_phys\"\"/> .",
    "e_dmgcap_physical": "该卡牌每次受到的物理伤害不会超过<physical> {0} </><img id=\"\"dmg_phys\"\"/> .",
    "e_undamagable_magic": "将该卡牌受到的<magic>魔法伤害</>降低至<magic> 0 </><img id=\"\"dmg_magic\"\"/> .",
    "e_dmgcap_magic": "该卡牌每次受到的魔法伤害不会超过<magic> {0} </><img id=\"\"dmg_magic\"\"/> .",
    "e_destroy_self": "摧毁该卡牌.",
    "e_decompile_self": "<decompile>反编译</>该卡牌.",
    "e_void_self": "<void>放逐</>该卡牌.",
    "e_attack": "该卡牌发动 {0} 次攻击.",
    "e_quick": "将该卡牌放置到场地上的操作不会消耗回合.",
    "e_revenge": "当该卡牌受到伤害时，该卡牌将发动一次攻击.",
    "e_reflect": "当该卡牌受到伤害时，令该卡牌的攻击力等于该卡牌受到的伤害.",
    "e_use_potion": "该卡牌使用后将被从本场游戏中移除.",
    "e_volatile": "该卡牌离开场地时将被<void>放逐</>.",
    "e_grave_to_hand": "将该卡牌从弃牌堆中返还到手中.",
    "e_t_ignition": "主动技能",
    "e_t_desc_ignition": "点击以触发，然后将该卡牌设置为未激活状态(若为敌方卡牌，则在倒计时结束时触发该效果).",
    "e_t_trigger": "触发式模块",
    "e_t_desc_trigger": "当满足特定的条件时，触发该效果(触发时不消耗回合且触发的优先顺序最低).",
    "e_t_init": "初始化",
    "e_t_desc_init": "当该卡牌被放置到场地上时，触发该效果(触发时不消耗回合且触发的优先顺序中等).",
    "e_t_condition": "条件限制",
    "e_t_desc_condition": "当满足特定的条件时，解除限制且该卡牌可被放置到场地上.",
    "e_t_exec": "执行式模块",
    "e_t_desc_exec": "当该卡牌被执行时，触发该效果.",
    "e_t_passive": "被动技能",
    "e_t_desc_passive": "当满足特定的条件时，触发该效果(触发时不消耗回合且触发的优先顺序最高).",
    "e_t_destruction": "销毁",
    "e_t_desc_destruction": "当该卡牌被摧毁时，触发该效果.",
    "e_t_volatile": "不稳定",
    "e_t_desc_volatile": "当该卡牌离开场地时，放逐该卡牌.",
    "e_t_defense": "防御模块",
    "e_t_desc_defense": "该卡牌每次受到的伤害不能超过一定限度.",
    "e_t_quick": "迅速",
    "e_t_desc_quick": "该卡牌被放置到场上时不会消耗回合.",
    "e_t_dragoon": "DRAGOON式链接",
    "e_t_desc_dragoon": "由DRAGOON创建的程序是彼此链接的.",
    "e_t_single": "消耗品",
    "e_t_desc_single": "当该卡牌的效果被触发时，将该卡牌从本场游戏中移除.",
    "e_t_artifact": "预载",
    "e_t_desc_artifact": "该卡牌将会出现在你的起始手牌中.",
    "e_t_storage": "缓存",
    "e_t_desc_storage": "当该卡牌位于存储空间时，触发该效果.",
    "key_once": "一次性",
    "key_desc_once": "该效果只能触发一次.",
    "key_instant": "迅捷",
    "key_desc_instant": "触发该效果时，不会消耗回合.",
    "key_unique": "独特性模块",
    "key_desc_unique": "该效果在同一回合中只能触发一次.",
    "key_global": "高级独特性模块",
    "key_desc_global": "该效果在同一回合中只能由一张卡牌触发一次.",
    "key_bonded": "保卫模块",
    "key_desc_bonded": "该效果无法被移除.",
    "key_exclusive": "高级模块",
    "key_desc_exclusive": "当该卡牌本回合触发了另一个效果时，该效果不会被触发.",
    "key_chained": "链式模块",
    "key_desc_chained": "这个效果直接连接到触发它的事件.",
    "h_effectkeyword_void": "<void>放逐</>-被放逐的卡牌将从游戏中暂时移除，并且不能再与之交互。<key>重新加载</>后，将被<void>放逐</>的卡牌返还到你的卡组中.",
    "h_effectkeyword_suspend": "<key>延迟</>-延迟目标的行动倒计时，但目标会抵抗延迟直到其行动",
    "h_effectkeyword_decompile": "<decompile>反编译</>-将卡牌移除到弃牌堆中，但并不会将其摧毁，并且不会得到目标拥有的编译材料.",
    "h_effectkeyword_exposed": "<expose>暴露的</>-该卡牌的前面没有其他己方卡牌.",
    "h_effectkeyword_covered": "<cover>被掩护的</>-该卡牌的前面有另一张己方卡牌.",
    "h_effectkeyword_automate": "<key>自动化</>-该卡牌将获得一定的回合倒计时，回合倒计时结束时，该卡牌将发动一次攻击且该卡牌仍可与之互动.",
    "h_effectkeyword_decaybuff": "<specialbuff>衰减性的攻击力增益</>-增加的攻击力每回合减少一点.",
    "h_effectkeyword_singlebuff": "<specialbuff>一次性的攻击力增益</>-该卡牌攻击后，移除该增益.",
    "h_effectkeyword_aligned": "<align>对齐的</>-与该卡牌位于同一列.",
    "h_activate": "<green>[点击以触发]</>",
    "h_noactivate": "<yellow>[不会触发]</>",
    "h_notactiveturn": "<red>[卡牌未激活]</>",
    "h_usedonce": "<red>[</><img id=\"\"effect_once\"\"></><red>used]</>",
    "h_disabled": "<red>[无效]</>",
    "h_conditionnotmet": "<red>[不符合条件]</>",
    "h_novalidtargets": "<yellow>[没有目标]</>",
    "h_notlocation": "<red>[无法从该位置触发]</>",
    "h_nocounters": "<red>[没有足够的计数点]</>",
    "h_toomanycounters": "<red>[计数点超额]</>",
    "h_noattackpower": "<red>[没有攻击力]</>",
    "h_noslots": "<red>[没有可用的场地]</>",
    "h_maxreached": "<yellow>[已达到最大值]</>",
    "h_upgradeblocker_healthzero": "没有足够的生命值",
    "c_abilityaurora": "Serenity",
    "c_abilitydragoon": "Imagination",
    "c_abilityesper": "WorldSeed",
    "c_abilityidol": "Encore",
    "c_abilityleo": "Mountain",
    "c_abilityomega": "Paradox",
    "c_abilityqueen": "Checkmate",
    "c_artifactgreed": "Greed.algo",
    "c_artifactmemory": "Memory.algo",
    "c_artifactmomentum": "Momentum.algo",
    "c_artifactspire": "Spire.algo",
    "c_chessbishop": "Bishop",
    "c_chessking": "King",
    "c_chessknight": "Knight",
    "c_chesspawn": "Pawn",
    "c_chessqueen": "Queen",
    "c_chessrook": "Rook",
    "c_consumablepotionhealth": "HealthPotion",
    "c_consumablepotionstorage": "StoragePotion",
    "c_consumablepotionvoid": "VoidPotion",
    "c_debugknife": "Knife.debug",
    "c_dragoonflame": "DragoonFlame",
    "c_fantasyarae": "Arae.myth",
    "c_fantasycockatrice": "Cockatrice.myth",
    "c_fantasygolem": "Golem.myth",
    "c_fantasygriffin": "Griffin.myth",
    "c_fantasymermaid": "Mermaid.myth",
    "c_fantasyphoenix": "Phoenix.myth",
    "c_fantasyunicorn": "Unicorn.myth",
    "c_genericafterburner": "Afterburner",
    "c_genericavarice": "Avarice",
    "c_genericbattery": "Battery",
    "c_genericbeartrap": "ClawTrap",
    "c_genericcapacitor": "DamageCapacitor",
    "c_genericcinder": "Cinder",
    "c_genericconstantcorrection": "ConstantCorrection",
    "c_genericcrystalball": "CrystalBall",
    "c_genericdoubleexecute": "DoubleExecute",
    "c_genericember": "Ember",
    "c_genericfireball": "Fireball",
    "c_genericflashattack": "Flash",
    "c_genericflashbang": "Flashbang",
    "c_genericforce": "Force",
    "c_genericinferno": "Inferno",
    "c_genericmagicember": "MagicEmber",
    "c_genericmagicflare": "MagicFlare",
    "c_genericmegarush": "RushMega",
    "c_genericomen": "Omen",
    "c_genericpendulum": "Pendulum",
    "c_genericpureheart": "PureHeart",
    "c_genericreincarnation": "Reincarnation",
    "c_genericscalpel": "Scalpel",
    "c_genericshatter": "Shatter",
    "c_genericspark": "Spark",
    "c_genericthunderclap": "Thunderclap",
    "c_generictreasure": "Treasure",
    "c_mdvaxe": "Axe.mech",
    "c_mdvcore": "Core.mech",
    "c_mdvgatling": "Gatling.mech",
    "c_mdvhammer": "Hammer.mech",
    "c_mdvhydro": "Hydro.mech",
    "c_mdvplasma": "Plasma.mech",
    "c_mdvpod": "DropPod",
    "c_mdvrocket": "RocketBarrage",
    "c_mdvspear": "Spear.mech",
    "c_mdvsword": "Sword.mech",
    "c_mdvthunder": "Thunder.mech",
    "c_mdvtower": "CommandTower",
    "c_mdvunity": "Unity",
    "c_musicbass": "Bass.muse",
    "c_musicdoubleeighth": "DoubleEighth.muse",
    "c_musicequalize": "Equalize.muse",
    "c_musicfermata": "Fermata.muse",
    "c_musicforte": "Forte.muse",
    "c_musicidol1": "Airi.muse",
    "c_musicidol2": "Miki.muse",
    "c_musicidol3": "Yuki.muse",
    "c_musicidol4": "Kano.muse",
    "c_musicidol5": "Erika.muse",
    "c_musicidolboss": "Remi.muse",
    "c_musicpiano": "Piano.muse",
    "c_musicquarter": "Quarter.muse",
    "c_musicquarterrest": "QuarterRest.muse",
    "c_musictreble": "Treble.muse",
    "c_musictriplet": "Triplet.muse",
    "c_naturalapple": "Apple.fruit",
    "c_naturalbanana": "Banana.fruit",
    "c_naturalcherry": "Cherry.fruit",
    "c_naturaldemeter": "Demeter.fruit",
    "c_naturalfall": "Autumn.fruit",
    "c_naturalgreenhouse": "Greenhouse",
    "c_naturalgrowth": "Growth",
    "c_naturallemon": "Lemon.fruit",
    "c_naturalpersephone": "Persephone.fruit",
    "c_naturalpollination": "Pollination",
    "c_naturalpomegranate": "Pomegranate.fruit",
    "c_naturalpumpkin": "Pumpkin.fruit",
    "c_naturalspring": "Spring.fruit",
    "c_naturalsummer": "Summer.fruit",
    "c_naturalwinter": "Winter.fruit",
    "c_sakurabow": "Bow.hana",
    "c_sakurakatana": "Katana.hana",
    "c_sakurakunai": "Kunai.hana",
    "c_sakuralantern": "Lantern.hana",
    "c_sakuraninja1": "Saya.hana",
    "c_sakuraninja2": "Ishida.hana",
    "c_sakuraninja3": "Mira.hana",
    "c_sakuraninja4": "Saigo.hana",
    "c_sakuraninjaboss": "MasterKobo.hana",
    "c_sakurapriestess": "Chiyo.hana",
    "c_sakurashide": "Shide.hana",
    "c_sakurastorm": "Bloom.hana",
    "c_sakuratorii": "Torii.hana",
    "c_spdeckedit": "Reprogram",
    "c_spdeckreload": "Rejuvenate",
    "c_spinitialize": "Initialize",
    "c_spinstantdraft": "Compile",
    "c_spiritamaterasu": "Amaterasu.spirit",
    "c_spiritkitsune": "Kitsune.spirit",
    "c_spiritkusanagi": "Kusanagi.spirit",
    "c_spiritmagatama": "Yasakani.spirit",
    "c_spiritneko": "Neko.spirit",
    "c_spiritnezumi": "Nezumi.spirit",
    "c_spiritsika": "Sika.spirit",
    "c_spirittanzaku": "Tanzaku.spirit",
    "c_spirittsukuyomi": "Tsukuyomi.spirit",
    "c_spirittsuru": "Tsuru.spirit",
    "c_spiritwatatsumi": "Watatsumi.spirit",
    "c_spirityamata": "Yamata.spirit",
    "c_spirityata": "Yata.spirit",
    "c_spstoragehit": "CacheHit",
    "c_tutorialfireball": "Fireball",
    "c_vampgen1": "Lorado.legion",
    "c_vampgen2_minion": "Clone.legion",
    "c_vampgen2": "Syka.legion",
    "c_vamphyper": "Hyper.blood",
    "c_vamplieu1": "Yiko.legion",
    "c_vamplieu2": "Misera.legion",
    "c_vamporb": "Orb.blood",
    "c_vamporigin": "Origin.blood",
    "c_vampplunge": "Plunge.blood",
    "c_vamprevival": "Revival.blood",
    "c_vampshield": "Shield.blood",
    "c_vampsol1": "Li.legion",
    "c_vampsol2": "Ora.legion",
    "c_vampsol3": "Xelia.legion",
    "c_vampspear": "Spear.blood",
    "c_vampsword": "Sword.blood",
    "c_magesorcignis": "Ignis.sorc",
    "c_magesorceffingo": "Effingo.sorc",
    "c_magesorccreo": "Creo.sorc",
    "c_magesorcgravitas": "Gravitas.sorc",
    "c_magesorcpotentia": "Potentia.sorc",
    "c_magesorctempus": "Tempus.sorc",
    "c_magesorclux": "Lux.sorc",
    "c_magelucia": "Lucia.mage",
    "c_mageaurelia": "Aurelia.mage",
    "c_magecamilla": "Camilla.mage",
    "c_magemariana": "Mariana.mage",
    "c_mageoctavia": "Octavia.mage",
    "c_magevaleria": "Valeria.mage",
    "c_magedecima": "Decima.mage",
    "c_genericupdraft": "Updraft",
    "c_generictaser": "Taser",
    "c_genericambush": "Ambush",
    "c_genericrupture": "Rupture",
    "c_edensaffron": "Saffron.eden",
    "c_edenthunder": "Thunder.edx",
    "c_edengunner": "Gunner.eden",
    "c_edenreva": "Reva.eden",
    "c_edenhazel": "Hazel.eden",
    "c_edenselicy": "Selicy.eden",
    "c_edenshiso": "Shiso.eden",
    "c_edenterra": "Terra.eden",
    "c_edenviolette": "Violette.eden",
    "c_edenstepslash": "StepSlash.edx",
    "c_edenbowsnipe": "BowSnipe.edx",
    "c_edencrossfire": "Crossfire.edx",
    "c_edenwave": "KineticWave.edx",
    "c_edenragnarok": "Ragnarok.edx",
    "c_edenshopkeeper": "Shopkeeper.eden",
    "c_crosseleheat": "Heat.element",
    "c_crosselecold": "Cold.element",
    "c_crosseleshock": "Shock.element",
    "c_crosselewave": "Wave.element",
    "c_crosslea": "Lea.cross",
    "c_crossemilienator": "Emilienator.cross",
    "c_crossctron": "C'tron.cross",
    "c_crosslukas": "Schneider.cross",
    "c_crossapollo": "Apollo.cross",
    "c_crossjoern": "Joern.cross",
    "c_crosshlin": "Hlin.cross",
    "c_crossbuggy": "Buggy.cross",
    "c_crossalbert": "Beowulf.cross",
    "c_crossshizuka": "Shizuka.cross",
    "c_mahoubunnyfire": "Kufi.mahou",
    "c_mahougirlfire": "Akane.mahou",
    "c_mahoubunnyearth": "Kuea.mahou",
    "c_mahougirlearth": "Chie.mahou",
    "c_mahoubunnywind": "Kuwi.mahou",
    "c_mahougirlwind": "Kazane.mahou",
    "c_mahoubunnywater": "Kuwa.mahou",
    "c_mahougirlwater": "Aoi.mahou",
    "c_mahoubunnydark": "Kuda.mahou",
    "c_mahougirldark": "Tsukiyo.mahou",
    "c_mahoubunnylight": "Kuli.mahou",
    "c_mahougirllight": "Hoshiko.mahou",
    "c_mahouwish": "Wish.mahou",
    "c_mahouhearttrial": "TrialOfHeart",
    "c_vaultcombo": "Combo",
    "c_vaultslash": "Slash.vault",
    "c_vaultblade": "HiddenBlade.vault",
    "c_vaultjab": "Jab.vault",
    "c_vaultapprentice": "Apprentice.vault",
    "c_vaultmultiblade": "BladeOnBlades.vault",
    "c_vaultbide": "Bide.vault",
    "c_vaultjuggle": "Juggle.vault",
    "c_vaultchar": "TheHidden.vault",
    "c_vaultoncemore": "OnceMore.vault",
    "c_vaultagility": "Agility.vault",
    "c_vaultlightup": "LightItUp.vault",
    "c_vaultopportunist": "Opportunist.vault",
    "c_vaultparry": "Parry.vault",
    "c_boss1minion": "ZyriteFragment.z",
    "c_boss2": "Zlime.z",
    "c_boss2minion": "Zlob.z",
    "c_boss3": "Zarakuri.z",
    "c_boss3virus": "Purple.virus",
    "c_boss4": "Zeaper.z",
    "c_boss4scythe": "Zcythe.z",
    "c_boss4dagger": "Zagger.z",
    "c_boss4soul": "Soul",
    "c_boss5": "Zirus.z",
    "c_boss5attackminion": "Zpike.z",
    "c_boss5bombminion": "Zingularity.z",
    "c_boss5left": "ZeftArm.z",
    "c_boss5right": "ZightArm.z",
    "c_bossb1": "Demeter.dark",
    "c_bossb1minion": "BlackThorns",
    "c_bossb2": "Remi.dark",
    "c_bossb2minion": "Note",
    "c_bossb3": "MasterKobo.dark",
    "c_bossb3minion1": "Katana.dark",
    "c_bossb3minion2": "Bow.dark",
    "c_bossb3minion3": "Kunai.dark",
    "c_bossb3minion4": "Lantern.dark",
    "c_bossb4": "Plasma.dark",
    "c_bossb4minion": "Energy.dark",
    "c_bossb5": "Persephone.dark",
    "c_bossb5minion": "Thorn",
    "c_bossb6": "Griffin.dark",
    "c_bossb6extra": "Treasure.dark",
    "c_bossb6minion": "Curse",
    "c_bossb7": "Lorado.dark",
    "c_bossb7minion1": "Soldier",
    "c_bossb7minion2": "Soldier",
    "c_bossb7minion3": "Soldier",
    "c_bossb8": "Amaterasu.dark",
    "c_bossb8minion": "SpiritEmber",
    "c_bossb9": "Tsukuyomi.dark",
    "c_bossb9minion": "Moonlight",
    "c_bossb10": "Decima.dark",
    "c_bossb10minion1": "Ignis.dark",
    "c_bossb10minion2": "Gravitas.dark",
    "c_bossb10minion3": "Creo.dark",
    "c_bossb10minionspawn": "DarkPower",
    "c_bossmahou": "TrialsOfHeart.x",
    "c_bosscomet1": "Zira.z",
    "c_bosscomet1minion": "Afterimage",
    "c_bosscomet2": "Zira.z",
    "c_bosscomet3": "Zira.z",
    "c_bosscomet3minion": "ShadowSabre",
    "c_bosscomet3minion2": "Corruption",
    "c_bosscometdefeat": "Zira.z",
    "c_bosswaystone": "CorruptedBit",
    "c_cometruinsanctum": "Sanctum?",
    "c_cometsanctum1": "Sanctum",
    "c_cometsanctum2": "Sanctum",
    "c_depthssanctum": "Sanctum",
    "c_dungeonbug": "Bug.mw",
    "c_enemyartillery": "Artillery.sc",
    "c_enemyblackvirus": "Black.virus",
    "c_enemybosscandle": "Zandle.z",
    "c_enemybug": "Bug.mw",
    "c_enemycache": "CryptCache",
    "c_enemycachedrafting": "SourceCache",
    "c_enemycacherandom": "BitCache",
    "c_enemychandelier": "Chandelier.mw",
    "c_enemycollapse": "Guillotine.ex",
    "c_enemydaggers": "Daggers.ex",
    "c_enemydisruptor": "Disruptor.sc",
    "c_enemyghostblue": "Blue.ghst",
    "c_enemyghostred": "Red.ghst",
    "c_enemyguardian": "Guardian.sc",
    "c_enemyinterceptor": "Interceptor.sc",
    "c_enemymiasma": "Miasma.ex",
    "c_enemymine": "Mine.sc",
    "c_enemymirrorshard": "MirrorShard.mw",
    "c_enemyobserver": "Observer.sc",
    "c_enemypassivebug": "Bug.mw",
    "c_enemypathogen": "Pathogen.mw",
    "c_enemypredator": "Predator.sc",
    "c_enemyrail": "RailGun.sc",
    "c_enemysentry": "Sentry.sc",
    "c_enemysentry2": "Sentry2.sc",
    "c_enemysignal": "Trance.ex",
    "c_enemystagetarget": "StageMark",
    "c_enemystealertutorial": "???",
    "c_enemystrongbug": "StrongBug.mw",
    "c_enemystrongwall": "Firewall.scx",
    "c_enemytalismanblack": "Black.tlsm",
    "c_enemytalismanwhite": "White.tlsm",
    "c_enemyvenom": "Venom.mw",
    "c_enemyvirusblue": "Blue.virus",
    "c_enemyvirusred": "Red.virus",
    "c_enemyweaktarget": "Target",
    "c_enemyweakwall": "Firewall.sc",
    "c_enemywormblue": "Blue.wrm",
    "c_enemywormred": "Red.wrm",
    "c_enemyzombie": "Zombie.mw",
    "c_miniboss1": "Curse.x",
    "c_omegaboss": "Zira.z",
    "c_omegabossunstable": "Zira.z",
    "c_omegacore": "VoidSpike.z",
    "c_potionhealth": "Health.potion",
    "c_potionstorage": "Storage.potion",
    "c_syncmarker1": "SyncMarker",
    "c_syncmarker2": "SyncMarker",
    "c_syncmarker4": "SyncMarker",
    "c_timebomb2": "TimeBomb",
    "c_timebomb3": "TimeBomb",
    "c_timebomb4": "TimeBomb",
    "c_timebomb7": "TimeBomb",
    "c_timebomb_h5_t6": "TimeBomb",
    "c_timebomb_h5_t5": "TimeBomb",
    "c_timebomb_h5_t4": "TimeBomb",
    "c_puzzleblank": "Blank",
    "c_storyvolatilecircuit_t2": "UnstableCircuit",
    "c_storyvolatilecircuit_t3": "UnstableCircuit",
    "c_storyvolatilecircuit_t4": "UnstableCircuit",
    "c_storyvolatilecircuit_t5": "UnstableCircuit",
    "c_storyvolatilecircuit_t6": "UnstableCircuit",
    "c_storyvolatilecircuit_t7": "UnstableCircuit",
    "c_storyvolatilecircuit_t8": "UnstableCircuit",
    "c_storyexplosivecircuit_t4": "ExplosiveCircuit",
    "c_storyfragilecircuit_t6": "FragileCircuit",
    "c_volatilecircuit_h4_t8": "UnstableCircuit",
    "c_volatilecircuit_h5_t4": "UnstableCircuit",
    "c_volatilecircuit_h5_t6": "UnstableCircuit",
    "c_volatilecircuit_h5_t7": "UnstableCircuit",
    "c_volatilecircuit_h5_t8": "UnstableCircuit",
    "c_volatilecircuit_h6_t8": "UnstableCircuit",
    "c_infinitereload": "Navigation",
    "c_infiniteinstantdraft": "HyperCompiler",
    "c_quantumknifetutorial": "Knife.hck",
    "c_quantumsigil": "Quantum",
    "c_enemysentrynoattack": "Sentry.sc",
    "c_stagemarker": "StageMarker",
    "c_securitylock": "Security.x",
    "c_objectivedata1": "Data.txt",
    "c_openingdungeonmark": "ACTIVE",
    "c_puzzledummy": "Dummy",
    "c_lootdummy": "ItemCage",
    "c_puzzleironwall": "IronWall",
    "c_puzzleironwall2": "TemperedWall",
    "c_auroraantisentry": "Sentry2+.sc",
    "c_queenlock": "QueensLock",
    "c_queenlockcore": "Lock",
    "c_machineblock": "BitBlock",
    "c_machineblock2": "BitBlock",
    "c_machinegear": "Contraption",
    "c_machinecoin": "Coin",
    "c_brainthorn": "ThornBubble",
    "c_brainheart": "BrokenHeart.z",
    "c_brainqueen": "Queen",
    "c_endgamelockgeneral": "Red.lock",
    "c_endgamelock1": "RedBit",
    "c_endgamelock2": "RedBit",
    "c_endgamelock3": "RedBit",
    "c_endgamelock4": "RedBit",
    "c_endgamelock5": "RedBit",
    "c_storyoxygen": "Oxygen",
    "c_storyhydrogen": "Hydrogen",
    "c_storybackdoor": "Backdoor",
    "c_flowerhologram": "Hologram",
    "c_haloshield": "Protection"
}as Record<string, string>